// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: offers.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Offers.Protos.ProtoFiles {
  public static partial class IOffers
  {
    static readonly string __ServiceName = "IOffers";

    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.OfferGroup> __Marshaller_OfferGroup = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.OfferGroup.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.Id> __Marshaller_Id = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.Id.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.BoolMessage> __Marshaller_BoolMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.BoolMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.DeleteItem> __Marshaller_DeleteItem = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.DeleteItem.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.EmptyParam> __Marshaller_EmptyParam = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.EmptyParam.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.OfferGroupList> __Marshaller_OfferGroupList = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.OfferGroupList.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.OfferRule> __Marshaller_OfferRule = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.OfferRule.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.OfferCreationSuccessStatus> __Marshaller_OfferCreationSuccessStatus = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.OfferCreationSuccessStatus.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.OfferDetailList> __Marshaller_OfferDetailList = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.OfferDetailList.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.Offer> __Marshaller_Offer = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.Offer.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.OfferList> __Marshaller_OfferList = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.OfferList.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.OfferCriteria> __Marshaller_OfferCriteria = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.OfferCriteria.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.OfferWithCategoryDetailList> __Marshaller_OfferWithCategoryDetailList = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.OfferWithCategoryDetailList.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.OfferCategoryMappingList> __Marshaller_OfferCategoryMappingList = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.OfferCategoryMappingList.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.CategoryMasterList> __Marshaller_CategoryMasterList = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.CategoryMasterList.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.ModelRuleList> __Marshaller_ModelRuleList = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.ModelRuleList.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.CityRuleList> __Marshaller_CityRuleList = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.CityRuleList.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.VersionIdList> __Marshaller_VersionIdList = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.VersionIdList.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.OfferCriteriaList> __Marshaller_OfferCriteriaList = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.OfferCriteriaList.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Offers.Protos.ProtoFiles.OfferAvailabiltyDetailsList> __Marshaller_OfferAvailabiltyDetailsList = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Offers.Protos.ProtoFiles.OfferAvailabiltyDetailsList.Parser.ParseFrom);

    static readonly grpc::Method<global::Offers.Protos.ProtoFiles.OfferGroup, global::Offers.Protos.ProtoFiles.Id> __Method_CreateOfferGroup = new grpc::Method<global::Offers.Protos.ProtoFiles.OfferGroup, global::Offers.Protos.ProtoFiles.Id>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateOfferGroup",
        __Marshaller_OfferGroup,
        __Marshaller_Id);

    static readonly grpc::Method<global::Offers.Protos.ProtoFiles.OfferGroup, global::Offers.Protos.ProtoFiles.BoolMessage> __Method_UpdateOfferGroup = new grpc::Method<global::Offers.Protos.ProtoFiles.OfferGroup, global::Offers.Protos.ProtoFiles.BoolMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateOfferGroup",
        __Marshaller_OfferGroup,
        __Marshaller_BoolMessage);

    static readonly grpc::Method<global::Offers.Protos.ProtoFiles.DeleteItem, global::Offers.Protos.ProtoFiles.BoolMessage> __Method_DeleteOfferGroup = new grpc::Method<global::Offers.Protos.ProtoFiles.DeleteItem, global::Offers.Protos.ProtoFiles.BoolMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteOfferGroup",
        __Marshaller_DeleteItem,
        __Marshaller_BoolMessage);

    static readonly grpc::Method<global::Offers.Protos.ProtoFiles.Id, global::Offers.Protos.ProtoFiles.OfferGroup> __Method_GetOfferGroup = new grpc::Method<global::Offers.Protos.ProtoFiles.Id, global::Offers.Protos.ProtoFiles.OfferGroup>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetOfferGroup",
        __Marshaller_Id,
        __Marshaller_OfferGroup);

    static readonly grpc::Method<global::Offers.Protos.ProtoFiles.EmptyParam, global::Offers.Protos.ProtoFiles.OfferGroupList> __Method_GetAllOfferGroup = new grpc::Method<global::Offers.Protos.ProtoFiles.EmptyParam, global::Offers.Protos.ProtoFiles.OfferGroupList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAllOfferGroup",
        __Marshaller_EmptyParam,
        __Marshaller_OfferGroupList);

    static readonly grpc::Method<global::Offers.Protos.ProtoFiles.OfferRule, global::Offers.Protos.ProtoFiles.OfferCreationSuccessStatus> __Method_CreateOfferRules = new grpc::Method<global::Offers.Protos.ProtoFiles.OfferRule, global::Offers.Protos.ProtoFiles.OfferCreationSuccessStatus>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateOfferRules",
        __Marshaller_OfferRule,
        __Marshaller_OfferCreationSuccessStatus);

    static readonly grpc::Method<global::Offers.Protos.ProtoFiles.OfferRule, global::Offers.Protos.ProtoFiles.OfferCreationSuccessStatus> __Method_UpdateOfferRules = new grpc::Method<global::Offers.Protos.ProtoFiles.OfferRule, global::Offers.Protos.ProtoFiles.OfferCreationSuccessStatus>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateOfferRules",
        __Marshaller_OfferRule,
        __Marshaller_OfferCreationSuccessStatus);

    static readonly grpc::Method<global::Offers.Protos.ProtoFiles.Id, global::Offers.Protos.ProtoFiles.OfferDetailList> __Method_GetOfferDetailsByOfferGroupId = new grpc::Method<global::Offers.Protos.ProtoFiles.Id, global::Offers.Protos.ProtoFiles.OfferDetailList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetOfferDetailsByOfferGroupId",
        __Marshaller_Id,
        __Marshaller_OfferDetailList);

    static readonly grpc::Method<global::Offers.Protos.ProtoFiles.Id, global::Offers.Protos.ProtoFiles.Offer> __Method_GetOfferById = new grpc::Method<global::Offers.Protos.ProtoFiles.Id, global::Offers.Protos.ProtoFiles.Offer>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetOfferById",
        __Marshaller_Id,
        __Marshaller_Offer);

    static readonly grpc::Method<global::Offers.Protos.ProtoFiles.Id, global::Offers.Protos.ProtoFiles.OfferList> __Method_GetOfferByOfferGroupId = new grpc::Method<global::Offers.Protos.ProtoFiles.Id, global::Offers.Protos.ProtoFiles.OfferList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetOfferByOfferGroupId",
        __Marshaller_Id,
        __Marshaller_OfferList);

    static readonly grpc::Method<global::Offers.Protos.ProtoFiles.OfferCriteria, global::Offers.Protos.ProtoFiles.OfferWithCategoryDetailList> __Method_GetOffersOnCriteria = new grpc::Method<global::Offers.Protos.ProtoFiles.OfferCriteria, global::Offers.Protos.ProtoFiles.OfferWithCategoryDetailList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetOffersOnCriteria",
        __Marshaller_OfferCriteria,
        __Marshaller_OfferWithCategoryDetailList);

    static readonly grpc::Method<global::Offers.Protos.ProtoFiles.DeleteItem, global::Offers.Protos.ProtoFiles.BoolMessage> __Method_DeleteOffer = new grpc::Method<global::Offers.Protos.ProtoFiles.DeleteItem, global::Offers.Protos.ProtoFiles.BoolMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteOffer",
        __Marshaller_DeleteItem,
        __Marshaller_BoolMessage);

    static readonly grpc::Method<global::Offers.Protos.ProtoFiles.Id, global::Offers.Protos.ProtoFiles.OfferCategoryMappingList> __Method_GetOfferCategoryMappingByOfferId = new grpc::Method<global::Offers.Protos.ProtoFiles.Id, global::Offers.Protos.ProtoFiles.OfferCategoryMappingList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetOfferCategoryMappingByOfferId",
        __Marshaller_Id,
        __Marshaller_OfferCategoryMappingList);

    static readonly grpc::Method<global::Offers.Protos.ProtoFiles.EmptyParam, global::Offers.Protos.ProtoFiles.CategoryMasterList> __Method_GetAllCategoryMaster = new grpc::Method<global::Offers.Protos.ProtoFiles.EmptyParam, global::Offers.Protos.ProtoFiles.CategoryMasterList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAllCategoryMaster",
        __Marshaller_EmptyParam,
        __Marshaller_CategoryMasterList);

    static readonly grpc::Method<global::Offers.Protos.ProtoFiles.Id, global::Offers.Protos.ProtoFiles.ModelRuleList> __Method_GetAllModelRulesByRuleId = new grpc::Method<global::Offers.Protos.ProtoFiles.Id, global::Offers.Protos.ProtoFiles.ModelRuleList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAllModelRulesByRuleId",
        __Marshaller_Id,
        __Marshaller_ModelRuleList);

    static readonly grpc::Method<global::Offers.Protos.ProtoFiles.Id, global::Offers.Protos.ProtoFiles.CityRuleList> __Method_GetAllCityRulesByRuleId = new grpc::Method<global::Offers.Protos.ProtoFiles.Id, global::Offers.Protos.ProtoFiles.CityRuleList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAllCityRulesByRuleId",
        __Marshaller_Id,
        __Marshaller_CityRuleList);

    static readonly grpc::Method<global::Offers.Protos.ProtoFiles.OfferCriteria, global::Offers.Protos.ProtoFiles.VersionIdList> __Method_GetVersionsWithOffers = new grpc::Method<global::Offers.Protos.ProtoFiles.OfferCriteria, global::Offers.Protos.ProtoFiles.VersionIdList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetVersionsWithOffers",
        __Marshaller_OfferCriteria,
        __Marshaller_VersionIdList);

    static readonly grpc::Method<global::Offers.Protos.ProtoFiles.OfferCriteriaList, global::Offers.Protos.ProtoFiles.OfferAvailabiltyDetailsList> __Method_CheckModelCityOfferAvailability = new grpc::Method<global::Offers.Protos.ProtoFiles.OfferCriteriaList, global::Offers.Protos.ProtoFiles.OfferAvailabiltyDetailsList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CheckModelCityOfferAvailability",
        __Marshaller_OfferCriteriaList,
        __Marshaller_OfferAvailabiltyDetailsList);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Offers.Protos.ProtoFiles.OffersReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of IOffers</summary>
    public abstract partial class IOffersBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Offers.Protos.ProtoFiles.Id> CreateOfferGroup(global::Offers.Protos.ProtoFiles.OfferGroup request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Offers.Protos.ProtoFiles.BoolMessage> UpdateOfferGroup(global::Offers.Protos.ProtoFiles.OfferGroup request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Offers.Protos.ProtoFiles.BoolMessage> DeleteOfferGroup(global::Offers.Protos.ProtoFiles.DeleteItem request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Offers.Protos.ProtoFiles.OfferGroup> GetOfferGroup(global::Offers.Protos.ProtoFiles.Id request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Offers.Protos.ProtoFiles.OfferGroupList> GetAllOfferGroup(global::Offers.Protos.ProtoFiles.EmptyParam request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Offers.Protos.ProtoFiles.OfferCreationSuccessStatus> CreateOfferRules(global::Offers.Protos.ProtoFiles.OfferRule request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Offers.Protos.ProtoFiles.OfferCreationSuccessStatus> UpdateOfferRules(global::Offers.Protos.ProtoFiles.OfferRule request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Offers.Protos.ProtoFiles.OfferDetailList> GetOfferDetailsByOfferGroupId(global::Offers.Protos.ProtoFiles.Id request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Offers.Protos.ProtoFiles.Offer> GetOfferById(global::Offers.Protos.ProtoFiles.Id request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Offers.Protos.ProtoFiles.OfferList> GetOfferByOfferGroupId(global::Offers.Protos.ProtoFiles.Id request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Offers.Protos.ProtoFiles.OfferWithCategoryDetailList> GetOffersOnCriteria(global::Offers.Protos.ProtoFiles.OfferCriteria request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Offers.Protos.ProtoFiles.BoolMessage> DeleteOffer(global::Offers.Protos.ProtoFiles.DeleteItem request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Offers.Protos.ProtoFiles.OfferCategoryMappingList> GetOfferCategoryMappingByOfferId(global::Offers.Protos.ProtoFiles.Id request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Offers.Protos.ProtoFiles.CategoryMasterList> GetAllCategoryMaster(global::Offers.Protos.ProtoFiles.EmptyParam request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Offers.Protos.ProtoFiles.ModelRuleList> GetAllModelRulesByRuleId(global::Offers.Protos.ProtoFiles.Id request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Offers.Protos.ProtoFiles.CityRuleList> GetAllCityRulesByRuleId(global::Offers.Protos.ProtoFiles.Id request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Offers.Protos.ProtoFiles.VersionIdList> GetVersionsWithOffers(global::Offers.Protos.ProtoFiles.OfferCriteria request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Offers.Protos.ProtoFiles.OfferAvailabiltyDetailsList> CheckModelCityOfferAvailability(global::Offers.Protos.ProtoFiles.OfferCriteriaList request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for IOffers</summary>
    public partial class IOffersClient : grpc::ClientBase<IOffersClient>
    {
      /// <summary>Creates a new client for IOffers</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public IOffersClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for IOffers that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public IOffersClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected IOffersClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected IOffersClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Offers.Protos.ProtoFiles.Id CreateOfferGroup(global::Offers.Protos.ProtoFiles.OfferGroup request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateOfferGroup(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Offers.Protos.ProtoFiles.Id CreateOfferGroup(global::Offers.Protos.ProtoFiles.OfferGroup request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateOfferGroup, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.Id> CreateOfferGroupAsync(global::Offers.Protos.ProtoFiles.OfferGroup request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateOfferGroupAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.Id> CreateOfferGroupAsync(global::Offers.Protos.ProtoFiles.OfferGroup request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateOfferGroup, null, options, request);
      }
      public virtual global::Offers.Protos.ProtoFiles.BoolMessage UpdateOfferGroup(global::Offers.Protos.ProtoFiles.OfferGroup request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateOfferGroup(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Offers.Protos.ProtoFiles.BoolMessage UpdateOfferGroup(global::Offers.Protos.ProtoFiles.OfferGroup request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateOfferGroup, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.BoolMessage> UpdateOfferGroupAsync(global::Offers.Protos.ProtoFiles.OfferGroup request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateOfferGroupAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.BoolMessage> UpdateOfferGroupAsync(global::Offers.Protos.ProtoFiles.OfferGroup request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateOfferGroup, null, options, request);
      }
      public virtual global::Offers.Protos.ProtoFiles.BoolMessage DeleteOfferGroup(global::Offers.Protos.ProtoFiles.DeleteItem request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteOfferGroup(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Offers.Protos.ProtoFiles.BoolMessage DeleteOfferGroup(global::Offers.Protos.ProtoFiles.DeleteItem request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteOfferGroup, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.BoolMessage> DeleteOfferGroupAsync(global::Offers.Protos.ProtoFiles.DeleteItem request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteOfferGroupAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.BoolMessage> DeleteOfferGroupAsync(global::Offers.Protos.ProtoFiles.DeleteItem request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteOfferGroup, null, options, request);
      }
      public virtual global::Offers.Protos.ProtoFiles.OfferGroup GetOfferGroup(global::Offers.Protos.ProtoFiles.Id request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetOfferGroup(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Offers.Protos.ProtoFiles.OfferGroup GetOfferGroup(global::Offers.Protos.ProtoFiles.Id request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetOfferGroup, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.OfferGroup> GetOfferGroupAsync(global::Offers.Protos.ProtoFiles.Id request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetOfferGroupAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.OfferGroup> GetOfferGroupAsync(global::Offers.Protos.ProtoFiles.Id request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetOfferGroup, null, options, request);
      }
      public virtual global::Offers.Protos.ProtoFiles.OfferGroupList GetAllOfferGroup(global::Offers.Protos.ProtoFiles.EmptyParam request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetAllOfferGroup(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Offers.Protos.ProtoFiles.OfferGroupList GetAllOfferGroup(global::Offers.Protos.ProtoFiles.EmptyParam request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAllOfferGroup, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.OfferGroupList> GetAllOfferGroupAsync(global::Offers.Protos.ProtoFiles.EmptyParam request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetAllOfferGroupAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.OfferGroupList> GetAllOfferGroupAsync(global::Offers.Protos.ProtoFiles.EmptyParam request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAllOfferGroup, null, options, request);
      }
      public virtual global::Offers.Protos.ProtoFiles.OfferCreationSuccessStatus CreateOfferRules(global::Offers.Protos.ProtoFiles.OfferRule request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateOfferRules(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Offers.Protos.ProtoFiles.OfferCreationSuccessStatus CreateOfferRules(global::Offers.Protos.ProtoFiles.OfferRule request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateOfferRules, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.OfferCreationSuccessStatus> CreateOfferRulesAsync(global::Offers.Protos.ProtoFiles.OfferRule request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateOfferRulesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.OfferCreationSuccessStatus> CreateOfferRulesAsync(global::Offers.Protos.ProtoFiles.OfferRule request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateOfferRules, null, options, request);
      }
      public virtual global::Offers.Protos.ProtoFiles.OfferCreationSuccessStatus UpdateOfferRules(global::Offers.Protos.ProtoFiles.OfferRule request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateOfferRules(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Offers.Protos.ProtoFiles.OfferCreationSuccessStatus UpdateOfferRules(global::Offers.Protos.ProtoFiles.OfferRule request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateOfferRules, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.OfferCreationSuccessStatus> UpdateOfferRulesAsync(global::Offers.Protos.ProtoFiles.OfferRule request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateOfferRulesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.OfferCreationSuccessStatus> UpdateOfferRulesAsync(global::Offers.Protos.ProtoFiles.OfferRule request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateOfferRules, null, options, request);
      }
      public virtual global::Offers.Protos.ProtoFiles.OfferDetailList GetOfferDetailsByOfferGroupId(global::Offers.Protos.ProtoFiles.Id request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetOfferDetailsByOfferGroupId(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Offers.Protos.ProtoFiles.OfferDetailList GetOfferDetailsByOfferGroupId(global::Offers.Protos.ProtoFiles.Id request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetOfferDetailsByOfferGroupId, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.OfferDetailList> GetOfferDetailsByOfferGroupIdAsync(global::Offers.Protos.ProtoFiles.Id request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetOfferDetailsByOfferGroupIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.OfferDetailList> GetOfferDetailsByOfferGroupIdAsync(global::Offers.Protos.ProtoFiles.Id request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetOfferDetailsByOfferGroupId, null, options, request);
      }
      public virtual global::Offers.Protos.ProtoFiles.Offer GetOfferById(global::Offers.Protos.ProtoFiles.Id request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetOfferById(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Offers.Protos.ProtoFiles.Offer GetOfferById(global::Offers.Protos.ProtoFiles.Id request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetOfferById, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.Offer> GetOfferByIdAsync(global::Offers.Protos.ProtoFiles.Id request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetOfferByIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.Offer> GetOfferByIdAsync(global::Offers.Protos.ProtoFiles.Id request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetOfferById, null, options, request);
      }
      public virtual global::Offers.Protos.ProtoFiles.OfferList GetOfferByOfferGroupId(global::Offers.Protos.ProtoFiles.Id request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetOfferByOfferGroupId(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Offers.Protos.ProtoFiles.OfferList GetOfferByOfferGroupId(global::Offers.Protos.ProtoFiles.Id request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetOfferByOfferGroupId, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.OfferList> GetOfferByOfferGroupIdAsync(global::Offers.Protos.ProtoFiles.Id request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetOfferByOfferGroupIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.OfferList> GetOfferByOfferGroupIdAsync(global::Offers.Protos.ProtoFiles.Id request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetOfferByOfferGroupId, null, options, request);
      }
      public virtual global::Offers.Protos.ProtoFiles.OfferWithCategoryDetailList GetOffersOnCriteria(global::Offers.Protos.ProtoFiles.OfferCriteria request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetOffersOnCriteria(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Offers.Protos.ProtoFiles.OfferWithCategoryDetailList GetOffersOnCriteria(global::Offers.Protos.ProtoFiles.OfferCriteria request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetOffersOnCriteria, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.OfferWithCategoryDetailList> GetOffersOnCriteriaAsync(global::Offers.Protos.ProtoFiles.OfferCriteria request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetOffersOnCriteriaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.OfferWithCategoryDetailList> GetOffersOnCriteriaAsync(global::Offers.Protos.ProtoFiles.OfferCriteria request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetOffersOnCriteria, null, options, request);
      }
      public virtual global::Offers.Protos.ProtoFiles.BoolMessage DeleteOffer(global::Offers.Protos.ProtoFiles.DeleteItem request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteOffer(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Offers.Protos.ProtoFiles.BoolMessage DeleteOffer(global::Offers.Protos.ProtoFiles.DeleteItem request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteOffer, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.BoolMessage> DeleteOfferAsync(global::Offers.Protos.ProtoFiles.DeleteItem request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteOfferAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.BoolMessage> DeleteOfferAsync(global::Offers.Protos.ProtoFiles.DeleteItem request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteOffer, null, options, request);
      }
      public virtual global::Offers.Protos.ProtoFiles.OfferCategoryMappingList GetOfferCategoryMappingByOfferId(global::Offers.Protos.ProtoFiles.Id request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetOfferCategoryMappingByOfferId(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Offers.Protos.ProtoFiles.OfferCategoryMappingList GetOfferCategoryMappingByOfferId(global::Offers.Protos.ProtoFiles.Id request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetOfferCategoryMappingByOfferId, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.OfferCategoryMappingList> GetOfferCategoryMappingByOfferIdAsync(global::Offers.Protos.ProtoFiles.Id request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetOfferCategoryMappingByOfferIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.OfferCategoryMappingList> GetOfferCategoryMappingByOfferIdAsync(global::Offers.Protos.ProtoFiles.Id request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetOfferCategoryMappingByOfferId, null, options, request);
      }
      public virtual global::Offers.Protos.ProtoFiles.CategoryMasterList GetAllCategoryMaster(global::Offers.Protos.ProtoFiles.EmptyParam request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetAllCategoryMaster(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Offers.Protos.ProtoFiles.CategoryMasterList GetAllCategoryMaster(global::Offers.Protos.ProtoFiles.EmptyParam request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAllCategoryMaster, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.CategoryMasterList> GetAllCategoryMasterAsync(global::Offers.Protos.ProtoFiles.EmptyParam request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetAllCategoryMasterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.CategoryMasterList> GetAllCategoryMasterAsync(global::Offers.Protos.ProtoFiles.EmptyParam request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAllCategoryMaster, null, options, request);
      }
      public virtual global::Offers.Protos.ProtoFiles.ModelRuleList GetAllModelRulesByRuleId(global::Offers.Protos.ProtoFiles.Id request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetAllModelRulesByRuleId(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Offers.Protos.ProtoFiles.ModelRuleList GetAllModelRulesByRuleId(global::Offers.Protos.ProtoFiles.Id request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAllModelRulesByRuleId, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.ModelRuleList> GetAllModelRulesByRuleIdAsync(global::Offers.Protos.ProtoFiles.Id request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetAllModelRulesByRuleIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.ModelRuleList> GetAllModelRulesByRuleIdAsync(global::Offers.Protos.ProtoFiles.Id request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAllModelRulesByRuleId, null, options, request);
      }
      public virtual global::Offers.Protos.ProtoFiles.CityRuleList GetAllCityRulesByRuleId(global::Offers.Protos.ProtoFiles.Id request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetAllCityRulesByRuleId(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Offers.Protos.ProtoFiles.CityRuleList GetAllCityRulesByRuleId(global::Offers.Protos.ProtoFiles.Id request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAllCityRulesByRuleId, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.CityRuleList> GetAllCityRulesByRuleIdAsync(global::Offers.Protos.ProtoFiles.Id request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetAllCityRulesByRuleIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.CityRuleList> GetAllCityRulesByRuleIdAsync(global::Offers.Protos.ProtoFiles.Id request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAllCityRulesByRuleId, null, options, request);
      }
      public virtual global::Offers.Protos.ProtoFiles.VersionIdList GetVersionsWithOffers(global::Offers.Protos.ProtoFiles.OfferCriteria request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetVersionsWithOffers(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Offers.Protos.ProtoFiles.VersionIdList GetVersionsWithOffers(global::Offers.Protos.ProtoFiles.OfferCriteria request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetVersionsWithOffers, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.VersionIdList> GetVersionsWithOffersAsync(global::Offers.Protos.ProtoFiles.OfferCriteria request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetVersionsWithOffersAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.VersionIdList> GetVersionsWithOffersAsync(global::Offers.Protos.ProtoFiles.OfferCriteria request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetVersionsWithOffers, null, options, request);
      }
      public virtual global::Offers.Protos.ProtoFiles.OfferAvailabiltyDetailsList CheckModelCityOfferAvailability(global::Offers.Protos.ProtoFiles.OfferCriteriaList request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CheckModelCityOfferAvailability(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Offers.Protos.ProtoFiles.OfferAvailabiltyDetailsList CheckModelCityOfferAvailability(global::Offers.Protos.ProtoFiles.OfferCriteriaList request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CheckModelCityOfferAvailability, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.OfferAvailabiltyDetailsList> CheckModelCityOfferAvailabilityAsync(global::Offers.Protos.ProtoFiles.OfferCriteriaList request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CheckModelCityOfferAvailabilityAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Offers.Protos.ProtoFiles.OfferAvailabiltyDetailsList> CheckModelCityOfferAvailabilityAsync(global::Offers.Protos.ProtoFiles.OfferCriteriaList request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CheckModelCityOfferAvailability, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override IOffersClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new IOffersClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(IOffersBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateOfferGroup, serviceImpl.CreateOfferGroup)
          .AddMethod(__Method_UpdateOfferGroup, serviceImpl.UpdateOfferGroup)
          .AddMethod(__Method_DeleteOfferGroup, serviceImpl.DeleteOfferGroup)
          .AddMethod(__Method_GetOfferGroup, serviceImpl.GetOfferGroup)
          .AddMethod(__Method_GetAllOfferGroup, serviceImpl.GetAllOfferGroup)
          .AddMethod(__Method_CreateOfferRules, serviceImpl.CreateOfferRules)
          .AddMethod(__Method_UpdateOfferRules, serviceImpl.UpdateOfferRules)
          .AddMethod(__Method_GetOfferDetailsByOfferGroupId, serviceImpl.GetOfferDetailsByOfferGroupId)
          .AddMethod(__Method_GetOfferById, serviceImpl.GetOfferById)
          .AddMethod(__Method_GetOfferByOfferGroupId, serviceImpl.GetOfferByOfferGroupId)
          .AddMethod(__Method_GetOffersOnCriteria, serviceImpl.GetOffersOnCriteria)
          .AddMethod(__Method_DeleteOffer, serviceImpl.DeleteOffer)
          .AddMethod(__Method_GetOfferCategoryMappingByOfferId, serviceImpl.GetOfferCategoryMappingByOfferId)
          .AddMethod(__Method_GetAllCategoryMaster, serviceImpl.GetAllCategoryMaster)
          .AddMethod(__Method_GetAllModelRulesByRuleId, serviceImpl.GetAllModelRulesByRuleId)
          .AddMethod(__Method_GetAllCityRulesByRuleId, serviceImpl.GetAllCityRulesByRuleId)
          .AddMethod(__Method_GetVersionsWithOffers, serviceImpl.GetVersionsWithOffers)
          .AddMethod(__Method_CheckModelCityOfferAvailability, serviceImpl.CheckModelCityOfferAvailability).Build();
    }

  }
}
#endregion
