// budget
export const UPDATE_MODEL_DATA= 'UPDATE_MODEL_DATA'
export const UPDATE_DOWNPAYMENT_SLIDER_VALUE = 'UPDATE_DOWNPAYMENT_SLIDER_VALUE'
export const UPDATE_DOWNPAYMENT_INPUT_VALUE = 'UPDATE_DOWNPAYMENT_INPUT_VALUE'
export const UPDATE_TENURE_SLIDER_VALUE = 'UPDATE_TENURE_SLIDER_VALUE'
export const UPDATE_TENURE_INPUT_VALUE = 'UPDATE_TENURE_INPUT_VALUE'
export const UPDATE_INTEREST_SLIDER_VALUE = 'UPDATE_INTEREST_SLIDER_VALUE'
export const UPDATE_INTEREST_INPUT_VALUE = 'UPDATE_INTEREST_INPUT_VALUE'
export const UPDATE_PIE_VALUE = 'UPDATE_PIE_VALUE'
export const SHOW_EMI_POPUP = 'SHOW_EMI_POPUP'
export const HIDE_EMI_POPUP = 'HIDE_EMI_POPUP'

// set model id for emi
export const SET_EMI_MODEL = 'SET_EMI_MODEL'
export const UPDATE_EMI_MODEL = 'UPDATE_EMI_MODEL'
export const SET_DOWNPAYMENT_SNAPPOINT = 'SET_DOWNPAYMENT_SNAPPOINT'
export const SET_IS_EMI_VALID = 'SET_IS_EMI_VALID'
