
namespace Bikewale.Entities.BikeBooking
{
    /// <summary>
    /// Created By : Vivek Gupta on 29 aug 2016
    /// </summary>
    public enum LeadSourceEnum
    {
        DPQ_Desktop = 1,
        DPQ_Mobile = 2,
        Model_Mobile = 4,
        Model_Desktop = 3,
        PriceInCity_Desktop = 5,
        PriceInCity_Mobile = 6,
        EMI_Calculator_ModelPage_Desktop = 34,
        EMI_Calculator_ModelPage_Mobile = 35,
        ModelPage_Floating_Mobile = 37,
        ModelPage_EmiCalculator_Mobile = 38,
        ModelPage_TopCard_Mobile = 39,
        ModelPage_MLA_Mobile = 40,
        PriceInCity_Floating_Mobile = 41,
        PriceInCity_PriceBreakUpLink_Mobile = 42,
        PriceInCity_TopCard_Mobile = 43,
        PriceInCity_EmiCalculator_Mobile = 44,
        PriceInCity_MLA_Mobile = 45,
        DPQ_Floating_Mobile = 46,
        DPQ_PriceBreakUpLink_Mobile = 47,
        DPQ_TopCard_Mobile = 48,
        DPQ_EmiCalculator_Mobile = 49,
        DPQ_MLA_Mobile = 50,
        DealersShowroomList_LeadForm_Mobile = 51,
        DealersShowroomList_MLA_Mobile = 52,
        DealersShowroomDetail_Floating_Mobile = 53,
        DealersShowroomDetail_MLA_Mobile = 54,
        BikeBooking_Mobile = 55,
        ModelPage_PriceLink_Desktop = 56,
        ModelPage_EmiCalculator_Desktop = 57,
        ModelPage_TopCard_Desktop = 58,
        ModelPage_MLA_Desktop = 59,
        PriceInCity_PriceBreakUpLink_Desktop = 60,
        PriceInCity_TopCard_Desktop = 61,
        PriceInCity_EmiCalculator_Desktop = 62,
        PriceInCity_MLA_Desktop = 63,
        DPQ_PriceBreakUpLink_Desktop = 64,
        DPQ_TopCard_Desktop = 65,
        DPQ_EmiCalculator_Desktop = 66,
        DPQ_MLA_Desktop = 67,
        DealersShowroomList_LeadForm_Desktop = 68,
        DealersShowroomList_MLA_Desktop = 69,
        DealersShowroomDetail_TopCard_Desktop = 70,
        DealersShowroomDetail_MLA_Desktop = 71,
        BikeBooking_Desktop = 72,
        PriceInCity_MLA_AMP = 73,
        PriceInCity_Floating_AMP = 74,
        PriceInCity_PriceBreakUpLink_AMP = 75,
        PriceInCity_TopCard_AMP = 76,
        PriceInCity_EmiCalculator_AMP = 77,
        ModelPage_Floating_AMP = 78,
        ModelPage_EmiCalculator_AMP = 79,
        ModelPage_TopCard_AMP = 80,
        ModelPage_MLA_AMP = 81,
        AdsLeadCapture = 82,
        ModelPage_VersionPriceList_Mobile = 83
    }
}
