// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Adtargeting.proto
// Original file comments:
// Copyright 2015, Google Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Adtargeting {
  /// <summary>
  /// The greeting service definition.
  /// </summary>
  public static partial class UserData
  {
    static readonly string __ServiceName = "Adtargeting.UserData";

    static readonly grpc::Marshaller<global::Adtargeting.CookieRequest> __Marshaller_CookieRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Adtargeting.CookieRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Adtargeting.UserDataResponse> __Marshaller_UserDataResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Adtargeting.UserDataResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Adtargeting.GrpcInt> __Marshaller_GrpcInt = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Adtargeting.GrpcInt.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Adtargeting.ElectricCarViewStatus> __Marshaller_ElectricCarViewStatus = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Adtargeting.ElectricCarViewStatus.Parser.ParseFrom);

    static readonly grpc::Method<global::Adtargeting.CookieRequest, global::Adtargeting.UserDataResponse> __Method_GetUserData = new grpc::Method<global::Adtargeting.CookieRequest, global::Adtargeting.UserDataResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetUserData",
        __Marshaller_CookieRequest,
        __Marshaller_UserDataResponse);

    static readonly grpc::Method<global::Adtargeting.GrpcInt, global::Adtargeting.GrpcInt> __Method_CheckHeartBit = new grpc::Method<global::Adtargeting.GrpcInt, global::Adtargeting.GrpcInt>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CheckHeartBit",
        __Marshaller_GrpcInt,
        __Marshaller_GrpcInt);

    static readonly grpc::Method<global::Adtargeting.CookieRequest, global::Adtargeting.ElectricCarViewStatus> __Method_IsElectricCarViewed = new grpc::Method<global::Adtargeting.CookieRequest, global::Adtargeting.ElectricCarViewStatus>(
        grpc::MethodType.Unary,
        __ServiceName,
        "IsElectricCarViewed",
        __Marshaller_CookieRequest,
        __Marshaller_ElectricCarViewStatus);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Adtargeting.AdtargetingReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of UserData</summary>
    public abstract partial class UserDataBase
    {
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Adtargeting.UserDataResponse> GetUserData(global::Adtargeting.CookieRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// update model
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Adtargeting.GrpcInt> CheckHeartBit(global::Adtargeting.GrpcInt request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Adtargeting.ElectricCarViewStatus> IsElectricCarViewed(global::Adtargeting.CookieRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for UserData</summary>
    public partial class UserDataClient : grpc::ClientBase<UserDataClient>
    {
      /// <summary>Creates a new client for UserData</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UserDataClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UserData that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UserDataClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UserDataClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UserDataClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Adtargeting.UserDataResponse GetUserData(global::Adtargeting.CookieRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetUserData(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Adtargeting.UserDataResponse GetUserData(global::Adtargeting.CookieRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetUserData, null, options, request);
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Adtargeting.UserDataResponse> GetUserDataAsync(global::Adtargeting.CookieRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetUserDataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Adtargeting.UserDataResponse> GetUserDataAsync(global::Adtargeting.CookieRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetUserData, null, options, request);
      }
      /// <summary>
      /// update model
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Adtargeting.GrpcInt CheckHeartBit(global::Adtargeting.GrpcInt request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CheckHeartBit(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// update model
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Adtargeting.GrpcInt CheckHeartBit(global::Adtargeting.GrpcInt request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CheckHeartBit, null, options, request);
      }
      /// <summary>
      /// update model
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Adtargeting.GrpcInt> CheckHeartBitAsync(global::Adtargeting.GrpcInt request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CheckHeartBitAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// update model
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Adtargeting.GrpcInt> CheckHeartBitAsync(global::Adtargeting.GrpcInt request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CheckHeartBit, null, options, request);
      }
      public virtual global::Adtargeting.ElectricCarViewStatus IsElectricCarViewed(global::Adtargeting.CookieRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return IsElectricCarViewed(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Adtargeting.ElectricCarViewStatus IsElectricCarViewed(global::Adtargeting.CookieRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_IsElectricCarViewed, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Adtargeting.ElectricCarViewStatus> IsElectricCarViewedAsync(global::Adtargeting.CookieRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return IsElectricCarViewedAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Adtargeting.ElectricCarViewStatus> IsElectricCarViewedAsync(global::Adtargeting.CookieRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_IsElectricCarViewed, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UserDataClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UserDataClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(UserDataBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetUserData, serviceImpl.GetUserData)
          .AddMethod(__Method_CheckHeartBit, serviceImpl.CheckHeartBit)
          .AddMethod(__Method_IsElectricCarViewed, serviceImpl.IsElectricCarViewed).Build();
    }

  }
}
#endregion
