IF EXISTS(
SELECT *
   FROM sys.views
     WHERE schema_id = SCHEMA_ID('dbo'))
     name = 'CUSTOMERCREDIT' AND
     DROP VIEW dbo.CUSTOMERCREDIT
GO

	
CREATE VIEW CUSTOMERCREDIT AS 
SELECT CM.ID AS CUSTCRID ,
(SELECT ISNULL(SUM(AMOUNT),'0') FROM CUSTOMERCREDITS AS CR WHERE CR.ACCOUNTID = CM.ID ) AS CRAMT,
(SELECT ISNULL(SUM(AMOUNT),'0') FROM CUSTOMERCREDITS AS CR WHERE CR.ACCOUNTID = CM.ID AND ENCASHED = 0 ) AS CRENCASH
FROM ACCOUNTCUSTOMERS CM 


