IF EXISTS(
SELECT *
   FROM sys.views
     WHERE schema_id = SCHEMA_ID('dbo'))
     name = 'VIWCUSTOMERDEBIT' AND
     DROP VIEW dbo.VIWCUSTOMERDEBIT
GO

	
CREATE VIEW VIWCUSTOMERDEBIT AS 
SELECT CM.ID , 
(SELECT ISNULL(SUM(AMOUNT),'0') FROM CUSTOMERDEBITS CD WHERE CD.ACCOUNTID = CM.ID ) AS DBAMT
FROM ACCOUNTCUSTOMERS CM

