IF EXISTS(
SELECT *
   FROM sys.views
     WHERE schema_id = SCHEMA_ID('dbo'))
     name = 'VIWLISTSEGMENT' AND
     DROP VIEW dbo.VIWLISTSEGMENT
GO

	
/*THIS IS THE VIEW FOR THE LIST OF SELLINQUIRIES ACCORDING TO THE
SEGMENT. ALSO WE HAVE TO GET THE COUNTS FOR 
THE NUMBER OF INQUIRIES MADE ACCORDING TO THAT YEAR
*/
CREATE VIEW VIWLISTSEGMENT AS 
SELECT 
S.ID AS ID,
S.Name AS Segment,
COUNT(SI.ID) AS SegmentCount
FROM
CarSegments AS S,
CarVersions AS CV,
SellInquiries AS SI
WHERE 
CV.SegmentId = S.ID AND
SI.CarVersionId = CV.ID AND
SI.IsArchived = 0
GROUP BY
S.ID, S.Name





