IF EXISTS(
SELECT *
   FROM sys.views
     WHERE schema_id = SCHEMA_ID('dbo'))
     name = 'VIWLISTMODEL' AND
     DROP VIEW dbo.VIWLISTMODEL
GO

	
/*THIS IS THE VIEW FOR THE LIST OF SELLINQUIRIES ACCORDING TO THE
MODEL. ALSO WE HAVE TO GET THE COUNTS FOR 
THE NUMBER OF INQUIRIES MADE ACCORDING TO THAT YEAR
*/
CREATE VIEW VIWLISTMODEL AS 
SELECT 
CM.ID AS ID, 
CM.CarMakeId As MakeId,
CM.Name AS Model,
COUNT(SI.ID) AS ModelCount
FROM
CarModels AS CM,
CarVersions AS CV,
SellInquiries AS SI
WHERE 
CM.IsDeleted = 0 AND
CV.CarModelId = CM.ID AND
SI.CarVersionId = CV.ID AND
SI.IsArchived = 0 
GROUP BY
CM.ID, CM.CarMakeId, CM.Name








