IF EXISTS(
SELECT *
   FROM sys.views
     WHERE schema_id = SCHEMA_ID('dbo'))
     name = 'VIWLISTYEAR' AND
     DROP VIEW dbo.VIWLISTYEAR
GO

	
/*THIS IS THE VIEW FOR THE LIST OF SELLINQUIRIES ACCORDING TO THE
YEAR. ALSO WE HAVE TO GET THE COUNTS FOR 
THE NUMBER OF INQUIRIES MADE ACCORDING TO THAT YEAR
*/
CREATE VIEW VIWLISTYEAR AS 
SELECT 
YEAR(SI.MakeYear) AS MakeYear,
COUNT(SI.ID) AS YearCount
FROM 
SellInquiries AS SI
WHERE 
SI.IsArchived = 0
GROUP BY
YEAR(SI.MakeYear)







