IF EXISTS(
SELECT *
   FROM sys.views
     WHERE schema_id = SCHEMA_ID('dbo'))
     name = 'VIWLISTMAKE' AND
     DROP VIEW dbo.VIWLISTMAKE
GO

	
/*THIS IS THE VIEW FOR THE LIST OF SELLINQUIRIES ACCORDING TO THE
MANUFACTURERS NAME(CARMAKES). ALSO WE HAVE TO GET THE COUNTS FOR 
THE NUMBER OF INQUIRIES MADE ACCORDING TO THAT CARMAKE
*/
CREATE VIEW VIWLISTMAKE AS 
SELECT 
CM.ID AS ID,
CM.Name AS CarMake,
CM.LogoUrl AS LogoUrl,
COUNT(SI.ID) AS MakeCount
FROM 
CarMakes AS CM,
CarModels AS CMO,
CarVersions AS CV,
SellInquiries AS SI
WHERE 
CM.IsDeleted = 0 AND
CMO.CarMakeId = CM.ID AND
CV.CarModelId = CMO.ID AND
SI.CarVersionId = CV.ID AND
SI.IsArchived = 0
GROUP BY
CM.ID, CM.Name , CM.LogoUrl, SI.DEALERID




