IF EXISTS(
SELECT *
   FROM sys.views
     WHERE schema_id = SCHEMA_ID('dbo'))
     name = 'VIWLISTBODYSTYLE' AND
     DROP VIEW dbo.VIWLISTBODYSTYLE
GO

	
/*THIS IS THE VIEW FOR THE LIST OF SELLINQUIRIES ACCORDING TO THE
BODYSTYLE. ALSO WE HAVE TO GET THE COUNTS FOR 
THE NUMBER OF INQUIRIES MADE ACCORDING TO THAT YEAR
*/
CREATE VIEW VIWLISTBODYSTYLE AS 
SELECT 
BS.ID AS ID,
BS.Name AS BodyStyle,
BS.ImageUrl AS ImageUrl,
COUNT(SI.ID) AS BodyCount
FROM 
CarBodyStyles AS BS,
CarVersions AS CV,
SellInquiries AS SI
WHERE 
CV.BodyStyleId = BS.ID AND
SI.CarVersionId = CV.ID AND
SI.IsArchived = 0
GROUP BY
BS.ID, BS.Name, BS.ImageUrl





