IF EXISTS (
    SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[EDITDEALERSTEMP]') 
    AND xtype IN (N'P')
)
    DROP PROCEDURE [dbo].[EDITDEALERSTEMP]
GO

	
--THIS PROCEDURE INSERTS THE VALUES FOR THE FEALER REGISTRATION ITO A TEMP TABLE TEMPDEALERS

CREATE PROCEDURE [dbo].[EDITDEALERSTEMP]
	@LOGINID		VARCHAR(30), 
	@FIRSTNAME		VARCHAR(50), 
	@LASTNAME		VARCHAR(50), 
	@EMAILID		VARCHAR(60), 
	@ORGANIZATION	VARCHAR(60), 
	@ADDRESS1		VARCHAR(100), 
	@ADDRESS2		VARCHAR(100), 
	@AREAID		NUMERIC, 
	@CITYID		NUMERIC, 
	@STATEID		NUMERIC, 
	@PINCODE		VARCHAR(6), 
	@PHONENO		VARCHAR(15), 
	@FAXNO		VARCHAR(15), 
	@MOBILENO		VARCHAR(15), 
	@ENTRYDATE		DATETIME, 
	@WEBSITEURL	VARCHAR(50), 
	@CONTACTPERSON	VARCHAR(60), 
	@CONTACTHOURS	VARCHAR(20), 
	@CONTACTEMAIL	VARCHAR(60),
	@ID			NUMERIC
 AS
	
BEGIN
	--NOW UPDATE THE DATA INTO THE TABLE
	UPDATE TEMPDEALERS SET 
			 LOGINID	=	@LOGINID ,
			 FIRSTNAME	=	@FIRSTNAME , 
			LASTNAME	=	@LASTNAME, 
			EMAILID	=	@EMAILID, 
			ORGANIZATION=	@ORGANIZATION, 
			ADDRESS1	=	@ADDRESS1,
			ADDRESS2	=	@ADDRESS2,
			AREAID	=	@AREAID,	 
			CITYID		=	@CITYID, 
			STATEID	=	@STATEID,
			PINCODE	=	@PINCODE,
			PHONENO	=	@PHONENO, 
			FAXNO		=	@FAXNO,
			MOBILENO	=	@MOBILENO,
			ENTRYDATE	=	@ENTRYDATE, 
			WEBSITEURL	=	@WEBSITEURL,
			CONTACTPERSON=	@CONTACTPERSON, 
			CONTACTHOURS =	@CONTACTHOURS, 
			CONTACTEMAIL =	@CONTACTEMAIL,
			ROLE		=	'DEALERS' 
		WHERE
			ID = @ID ;

		 
	
	
END
