IF EXISTS (
    SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[ENTRYWALLPAPERS]') 
    AND xtype IN (N'P')
)
    DROP PROCEDURE [dbo].[ENTRYWALLPAPERS]
GO

	
--THIS PROCEDURE IS FOR INSERTING AND UPDATING RECORDS FOR CAR WALLPAPERS
--ID, Title, ModelId, VersionId, VersionSpecific, Eight, Thousand, RandomString, EightFileSize, ThousandFileSize

CREATE PROCEDURE [dbo].[ENTRYWALLPAPERS]
	@ID			NUMERIC,		--ID. IF IT IS -1 THEN IT IS FOR INSERT, ELSE IT IS FOR UPDATE FOR THE ID 		        	
	@TITLE		VARCHAR(50),		--TITLE 
	@MODELID		NUMERIC,		--ID OF THE MODEL
	@VERSIONID		NUMERIC,		--ID OF THE VERSION
	@VERSIONSPECIFIC	BIT,
	@EIGHT		BIT,
	@THOUSAND		BIT,
	@RANDOMSTRING	VARCHAR(200),		--THE INITIALS OF THE FILE
	@EIGHTFILESIZE	VARCHAR(15),
	@THOUSANDFILESIZE	VARCHAR(15),
	@ENTRYDATE 	DATETIME		--DATE
	
 AS
	
BEGIN
	
	IF @ID = -1
	BEGIN
		--IT IS FOR THE INSERT
		INSERT INTO WALLPAPERS
			( TITLE, MODELID, VERSIONID, VERSIONSPECIFIC, EIGHT, 
			  THOUSAND, RANDOMSTRING, EIGHTFILESIZE, THOUSANDFILESIZE, ENTRYDATE) 
		VALUES
			( @TITLE, @MODELID, @VERSIONID, @VERSIONSPECIFIC, @EIGHT, 
			  @THOUSAND, @RANDOMSTRING, @EIGHTFILESIZE, @THOUSANDFILESIZE, @ENTRYDATE)
		
		
	END
	ELSE
	BEGIN
		--IT IS FOR THE UPDATE
		
		UPDATE WALLPAPERS SET 
			TITLE = @TITLE
		WHERE
			ID = @ID	
	END
	
		
END
