IF EXISTS (
    SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[ENTRYREVIEWS]') 
    AND xtype IN (N'P')
)
    DROP PROCEDURE [dbo].[ENTRYREVIEWS]
GO

	
--THIS PROCEDURE IS FOR INSERTING AND UPDATING RECORDS FOR CAR REVIEWS

CREATE PROCEDURE [dbo].[ENTRYREVIEWS]
	@ID			NUMERIC,		--ID. IF IT IS -1 THEN IT IS FOR INSERT, ELSE IT IS FOR UPDATE FOR THE ID 		        	
	@MODELID		NUMERIC,		--ID OF THE MODEL
	@TITLE		VARCHAR(200),		--TITLE OF THE REVIEW
	@Summary		VARCHAR(200),		--Summary OF THE REVIEW
	@REVIEWDATE 	DATETIME,		--DATE OF THE REVIEW
	@REVIEWID		NUMERIC OUTPUT
 AS
	
BEGIN
	
	IF @ID = -1
	BEGIN
		--IT IS FOR THE INSERT
		INSERT INTO REVIEWS(MODELID, TITLE, Summary,  REVIEWDATE, ISACTIVE) 
			VALUES(@MODELID, @TITLE, @Summary, @REVIEWDATE, 1)

		SET @REVIEWID = SCOPE_IDENTITY()
	END
	ELSE
	BEGIN
		--IT IS FOR THE UPDATE
		UPDATE REVIEWS SET 
			MODELID 	= @MODELID,
			Summary	= @Summary,
			TITLE 		= @TITLE,
			REVIEWDATE 	= @REVIEWDATE
		 WHERE 
			ID = @ID

		SET @REVIEWID = @ID
	END
	
		
END
