IF EXISTS (
    SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[GetUsedCarResponses]') 
    AND xtype IN (N'P')
)
    DROP PROCEDURE [dbo].[GetUsedCarResponses]
GO

	-- =============================================
-- AUTHOR:		PRACHI PHALAJK
-- CREATE DATE: 22ND FEB,2016
-- DESCRIPTION:	FOR DISPLAYING USED CAR DAILY,MONTHLY AND YESTERDAY RESPONSES.
-- =============================================
CREATE PROCEDURE [dbo].[GetUsedCarResponses] 
	-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE
@DAILYCOUNT INT OUTPUT,
@YESTERDAYCOUNT INT OUTPUT,
@MONTHLYCOUNT INT OUTPUT
AS
BEGIN
	-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
	-- INTERFERING WITH SELECT STATEMENTS.
	SET NOCOUNT ON;

-- QUERY TO FETCH DAILY LEADS COUNT
SELECT @DAILYCOUNT = (
	(	SELECT COUNT(UCP.ID)
		FROM SELLINQUIRIES SI WITH (NOLOCK)
		LEFT JOIN USEDCARPURCHASEINQUIRIES UCP  WITH (NOLOCK) ON UCP.SELLINQUIRYID = SI.ID
		WHERE	CAST(UCP.REQUESTDATETIME  AS DATE)=CAST(GETDATE() AS DATE)
	)	+
	(
		SELECT COUNT(UCP.ID)
		FROM CUSTOMERSELLINQUIRIES SI WITH (NOLOCK)
		LEFT JOIN CLASSIFIEDREQUESTS UCP WITH (NOLOCK)  ON UCP.SELLINQUIRYID = SI.ID
		WHERE  CAST(UCP.REQUESTDATETIME  AS DATE)=CAST(GETDATE() AS DATE)
	)	+
	(
		SELECT COUNT(MM.MM_INQUIRIESID)
		FROM MM_INQUIRIES MM  WITH (NOLOCK)
		LEFT JOIN DEALERS D WITH (NOLOCK) ON D.ID = MM.CONSUMERID 
		WHERE D.TC_DEALERTYPEID = 1
		AND   CAST(MM.CALLSTARTDATE AS DATE) = CAST(GETDATE() AS DATE)
		)
	) 
-- QUERY TO FETCH YESTERDAY'S LEAD COUNT
	SELECT  @YESTERDAYCOUNT = (
		(
			SELECT COUNT(UCP.ID)
			FROM SELLINQUIRIES SI WITH (NOLOCK)
			LEFT JOIN USEDCARPURCHASEINQUIRIES UCP  WITH (NOLOCK) ON UCP.SELLINQUIRYID = SI.ID
			WHERE CAST(UCP.REQUESTDATETIME  AS DATE)=CAST(GETDATE()-1 AS DATE)
			
		)	+
		(
			SELECT COUNT(UCP.ID)
			FROM CUSTOMERSELLINQUIRIES SI WITH (NOLOCK)
			LEFT JOIN CLASSIFIEDREQUESTS UCP WITH (NOLOCK)  ON UCP.SELLINQUIRYID = SI.ID
			WHERE CAST(UCP.REQUESTDATETIME  AS DATE)=CAST(GETDATE()-1 AS DATE)
			
		)	+
		(
			SELECT COUNT(MM.MM_INQUIRIESID)
			FROM MM_INQUIRIES MM  WITH (NOLOCK)
			LEFT JOIN DEALERS D WITH (NOLOCK) ON D.ID = MM.CONSUMERID 
			WHERE D.TC_DEALERTYPEID = 1
			AND   CAST(MM.CALLSTARTDATE AS DATE) = CAST(GETDATE()-1 AS DATE)
		) 
	)
--QUERY TO FETCH MONTHLY LEADS COUNT
	SELECT  @MONTHLYCOUNT =  (
		(
			SELECT COUNT(UCP.ID)
			FROM SELLINQUIRIES SI WITH (NOLOCK)
			LEFT JOIN USEDCARPURCHASEINQUIRIES UCP  WITH (NOLOCK) ON UCP.SELLINQUIRYID = SI.ID
			WHERE 
			MONTH(UCP.REQUESTDATETIME) = MONTH(GETDATE())
			AND YEAR(UCP.REQUESTDATETIME) = YEAR(GETDATE())
		)	+
		(
			SELECT COUNT(UCP.ID)
			FROM CUSTOMERSELLINQUIRIES SI WITH (NOLOCK)
			LEFT JOIN CLASSIFIEDREQUESTS UCP WITH (NOLOCK)  ON UCP.SELLINQUIRYID = SI.ID
			WHERE  
			MONTH(UCP.REQUESTDATETIME) = MONTH(GETDATE())
						AND YEAR(UCP.REQUESTDATETIME) = YEAR(GETDATE())
		)	+
		(
			SELECT COUNT(MM.MM_INQUIRIESID)
			FROM MM_INQUIRIES MM  WITH (NOLOCK)
			LEFT JOIN DEALERS D WITH (NOLOCK) ON D.ID = MM.CONSUMERID 
			WHERE D.TC_DEALERTYPEID = 1

					AND MONTH(MM.CALLSTARTDATE) = MONTH(GETDATE())
					AND YEAR(MM.CALLSTARTDATE) = YEAR(GETDATE())
		)
	)

	END
