IF EXISTS (
    SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[INSERTASSOCIATES]') 
    AND xtype IN (N'P')
)
    DROP PROCEDURE [dbo].[INSERTASSOCIATES]
GO

	
--THIS PROCEDURE INSERTS THE ASOOCIATED MEMBERS LIST INTO THE DEALERASSOCIATES TABLE.
--THIS GETS TAS INPUT THE DEALER ID AND A STRING OF IDS FOR THE ASSOCIATED MEMBERS ID
--also the user can not add its own id

CREATE PROCEDURE [dbo].[INSERTASSOCIATES]
	@DEALERID		NUMERIC,
	@ASSOCIATELIST	VARCHAR(3000)	--THIS LIST CAONTAINS AL THE RANGEID INCLUDED IN THE PROJECT SEPARATED WITH COMMA
 
AS
	DECLARE
		@STARTINDEX	AS INT,		--HOLDS STARTINDEX 
		@ENDINDEX		AS INT,		--HOLDS ENDINDEX
		@TEMPID		AS NUMERIC
  	
BEGIN

		--set @ENDINDEX to 0
		SET @ENDINDEX = 0
		SET @STARTINDEX = 0

		WHILE @ENDINDEX < LEN(@ASSOCIATELIST)		
		BEGIN
			
			SET @ENDINDEX = CHARINDEX(',',@ASSOCIATELIST,@ENDINDEX+1)
	
			SET @TEMPID = SUBSTRING(@ASSOCIATELIST, @STARTINDEX, @ENDINDEX - @STARTINDEX)
			
			print  @STARTINDEX
			print  @ENDINDEX

			--NOW INSERT THE DEALERID AND THE ASSOCIATE ID INTO DEALERASSOCIATES TABLE
			--CHECK THAT THE DEALERID AND THE ASSOCIATE D ARE NOT THE SAME
			IF @DEALERID <> @TEMPID
				INSERT INTO DEALERASSOCIATES (DEALERID, ASSOCIATEID) VALUES(@DEALERID, @TEMPID)
			
			SET @STARTINDEX = @ENDINDEX + 1

			--check whether @ENDINDEX < LEN(@ASSOCIATELIST)	
			IF @ENDINDEX >= LEN(@ASSOCIATELIST)
				BREAK;
			
				
		
		END
	
END
