IF EXISTS (
    SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[INSERTDAILYLOGS]') 
    AND xtype IN (N'P')
)
    DROP PROCEDURE [dbo].[INSERTDAILYLOGS]
GO

	
--THIS PROCEDURE IS FOR INSERTING AND UPDATING RECORDS FOR DAILYLOGS  TABLE
--BEFORE INSERTING OR UPDATING CHECK FOR THE DUPLICATE ENTRIES

CREATE PROCEDURE [dbo].[INSERTDAILYLOGS]
	@ENTRYDATE		DATETIME,		--DATE FOR WHICH THE PARTICULAR VALUES HAVE BEEN ASSIGNED .
	@ID			NUMERIC,		--ID. IF IT IS -1 THEN IT IS FOR INSERT, ELSE IT IS FOR UPDATE FOR THE ID 		
	@USERREG		NUMERIC,		--COUNT OF USERS REGISTRATION 
	@UVISITOR		NUMERIC,		--COUNT OF UNIQUE VISITORS 
	@HITS			NUMERIC,		--COUNT OF  HITS
	@NEWPURINQ		NUMERIC,		--COUNT OF  NEW PURCHASE  INQUIRIES
	@USEDPURINQD	NUMERIC,		--COUNT OF  USED PURCHASE  INQUIRIES   FOR DEALERS
	@USEDPURINQI	NUMERIC,		--COUNT OF  USED PURCHASE  INQUIRIES   FOR INDIVIDUALS
	@USEDPURINQT	NUMERIC,		--COUNT OF  USED PURCHASE  INQUIRIES   FOR TOTAL
	@FINANCEPURINQ	NUMERIC,		--COUNT OF  FINANCE PURCHASE  INQUIRIES  
	@SELLINQD		NUMERIC,		--COUNT OF  SELL  INQUIRIES FOR DEALERS
	@SELLINQI		NUMERIC,		--COUNT OF  SELL  INQUIRIES FOR INDIVIDUALS
	@SELLINQT		NUMERIC,		--COUNT OF  SELL  INQUIRIES FOR TOTAL
	@DEALERREG		NUMERIC,		--COUNT OF DEALERS REGISTRATION 
	@PAGEVIEWS		NUMERIC,
    @STATUS 		INTEGER OUTPUT	--return value, 0 FOR SUCCESSFULL  ATTEMPT, AND -1 FOR DUPLICATE ENTRY
 AS
	
BEGIN
	
	IF @ID = -1
	BEGIN
		--IT IS FOR THE INSERT
		INSERT INTO DAILYLOGS
		(
			ENTRYDATE , USERREGISTRATION , UNIQUEVISITORS , HITS , NEWPURCHASEINQ ,
			USEDPURCHASEINQDEALER,USEDPURCHASEINQINDIVIDUAL,USEDPURCHASEINQTOTAL , FINANCEPURCHASEINQ ,
			DEALERSCARSSELLINQ,INDIVIDUALCARSSELLINQ,SELLINQTOTAL , DEALERREGISTRATION, PAGEVIEWS 
		)
		 VALUES
		(
			@ENTRYDATE , @USERREG , @UVISITOR , @HITS ,@NEWPURINQ ,
			@USEDPURINQD,@USEDPURINQI,@USEDPURINQT , @FINANCEPURINQ , 
			@SELLINQD ,@SELLINQI,@SELLINQT, @DEALERREG, @PAGEVIEWS
		)
	END
	ELSE
	BEGIN
		--IT IS FOR THE UPDATE
		UPDATE DAILYLOGS SET
			
		USERREGISTRATION 			= @USERREG ,
		UNIQUEVISITORS 			= @UVISITOR ,
		HITS		              		= @HITS ,
		NEWPURCHASEINQ			 = @NEWPURINQ ,
		USEDPURCHASEINQDEALER 		 = @USEDPURINQD ,
		USEDPURCHASEINQINDIVIDUAL 	 = @USEDPURINQI ,
		USEDPURCHASEINQTOTAL 		= @USEDPURINQT ,
		FINANCEPURCHASEINQ 		= @FINANCEPURINQ ,
		DEALERSCARSSELLINQ		   	= @SELLINQD ,
		INDIVIDUALCARSSELLINQ		= @SELLINQI ,
		SELLINQTOTAL		  	= @SELLINQT ,
		DEALERREGISTRATION		= @DEALERREG,
		PAGEVIEWS				= @PAGEVIEWS
		
		WHERE ID = @ID
	END
	
	--CHECK THE ERROR. IF IT IS NOT 0, THEN THERE IS ERROR IN INSERTING THE QUERY. IN THIS CASE THIS WILL BE DUE TO
	--DUPLICATE ENTRY
	IF @@ERROR <> 0
	BEGIN
		SET @STATUS = @@ERROR
	END
	ELSE
		SET @STATUS = 0	
	
END
