IF EXISTS (
    SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[INSERTRESTRICTED]') 
    AND xtype IN (N'P')
)
    DROP PROCEDURE [dbo].[INSERTRESTRICTED]
GO

	
--THIS PROCEDURE INSERTS THE ASOOCIATED MEMBERS LIST INTO THE DEALERRESTRICTED TABLE.
--THIS GETS TAS INPUT THE DEALER ID AND A STRING OF IDS FOR THE IGNORED MEMBERS ID
--ALSO CHECK THAT THE DEALER DONT ADD ITS OWN ID

CREATE PROCEDURE [dbo].[INSERTRESTRICTED]
	@DEALERID		NUMERIC,
	@RESTRICTEDLIST	VARCHAR(3000)	
 
AS
	DECLARE
		@STARTINDEX	AS INT,		--HOLDS STARTINDEX 
		@ENDINDEX		AS INT,		--HOLDS ENDINDEX
		@TEMPID		AS NUMERIC
  	
BEGIN

		--set @ENDINDEX to 0
		SET @ENDINDEX = 0
		SET @STARTINDEX = 0

		WHILE @ENDINDEX < LEN(@RESTRICTEDLIST)		
		BEGIN
			
			SET @ENDINDEX = CHARINDEX(',',@RESTRICTEDLIST,@ENDINDEX+1)
	
			SET @TEMPID = SUBSTRING(@RESTRICTEDLIST, @STARTINDEX, @ENDINDEX - @STARTINDEX)
			
			print  @STARTINDEX
			print  @ENDINDEX

			--NOW INSERT THE DEALERID AND THE IGNORED ID INTO DEALERIGNORED TABLE
			--ALSO CHECK THAT THE DEALER DONT ADD ITS OWN ID
			IF @DEALERID <> @TEMPID
				INSERT INTO DEALERRESTRICTED (DEALERID, RESTRICTEDID) VALUES(@DEALERID, @TEMPID)
			
			SET @STARTINDEX = @ENDINDEX + 1

			--check whether @ENDINDEX < LEN(@RESTRICTEDLIST)	
			IF @ENDINDEX >= LEN(@RESTRICTEDLIST)
				BREAK;
			
				
		
		END
	
END
