// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Article.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace Grpc.CMS {
  public static class GrpcArticle
  {
    static readonly string __ServiceName = "GrpcArticleController.GrpcArticle";

    static readonly Marshaller<global::Grpc.CMS.GrpcArticleByCatURI> __Marshaller_GrpcArticleByCatURI = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.CMS.GrpcArticleByCatURI.Parser.ParseFrom);
    static readonly Marshaller<global::Grpc.CMS.GrpcCMSContent> __Marshaller_GrpcCMSContent = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.CMS.GrpcCMSContent.Parser.ParseFrom);
    static readonly Marshaller<global::Grpc.CMS.GrpcArticleBySubCatURI> __Marshaller_GrpcArticleBySubCatURI = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.CMS.GrpcArticleBySubCatURI.Parser.ParseFrom);
    static readonly Marshaller<global::Grpc.CMS.GrpcArticleContentURI> __Marshaller_GrpcArticleContentURI = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.CMS.GrpcArticleContentURI.Parser.ParseFrom);
    static readonly Marshaller<global::Grpc.CMS.GrpcArticleDetails> __Marshaller_GrpcArticleDetails = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.CMS.GrpcArticleDetails.Parser.ParseFrom);
    static readonly Marshaller<global::Grpc.CMS.GrpcArticlePageDetails> __Marshaller_GrpcArticlePageDetails = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.CMS.GrpcArticlePageDetails.Parser.ParseFrom);
    static readonly Marshaller<global::Grpc.CMS.GrpcArticleRecentURI> __Marshaller_GrpcArticleRecentURI = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.CMS.GrpcArticleRecentURI.Parser.ParseFrom);
    static readonly Marshaller<global::Grpc.CMS.GrpcArticleSummaryList> __Marshaller_GrpcArticleSummaryList = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.CMS.GrpcArticleSummaryList.Parser.ParseFrom);
    static readonly Marshaller<global::Grpc.CMS.GrpcArticleFeatureURI> __Marshaller_GrpcArticleFeatureURI = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.CMS.GrpcArticleFeatureURI.Parser.ParseFrom);
    static readonly Marshaller<global::Grpc.CMS.GrpcArticleRelatedURI> __Marshaller_GrpcArticleRelatedURI = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.CMS.GrpcArticleRelatedURI.Parser.ParseFrom);
    static readonly Marshaller<global::Grpc.CMS.GrpcMakeDetailURI> __Marshaller_GrpcMakeDetailURI = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.CMS.GrpcMakeDetailURI.Parser.ParseFrom);
    static readonly Marshaller<global::Grpc.CMS.GrpcMakeAndModelDetailList> __Marshaller_GrpcMakeAndModelDetailList = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.CMS.GrpcMakeAndModelDetailList.Parser.ParseFrom);
    static readonly Marshaller<global::Grpc.CMS.GrpcModelDetailURI> __Marshaller_GrpcModelDetailURI = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.CMS.GrpcModelDetailURI.Parser.ParseFrom);

    static readonly Method<global::Grpc.CMS.GrpcArticleByCatURI, global::Grpc.CMS.GrpcCMSContent> __Method_ListByCategory = new Method<global::Grpc.CMS.GrpcArticleByCatURI, global::Grpc.CMS.GrpcCMSContent>(
        MethodType.Unary,
        __ServiceName,
        "ListByCategory",
        __Marshaller_GrpcArticleByCatURI,
        __Marshaller_GrpcCMSContent);

    static readonly Method<global::Grpc.CMS.GrpcArticleBySubCatURI, global::Grpc.CMS.GrpcCMSContent> __Method_ListBySubCategory = new Method<global::Grpc.CMS.GrpcArticleBySubCatURI, global::Grpc.CMS.GrpcCMSContent>(
        MethodType.Unary,
        __ServiceName,
        "ListBySubCategory",
        __Marshaller_GrpcArticleBySubCatURI,
        __Marshaller_GrpcCMSContent);

    static readonly Method<global::Grpc.CMS.GrpcArticleContentURI, global::Grpc.CMS.GrpcArticleDetails> __Method_ContentDetail = new Method<global::Grpc.CMS.GrpcArticleContentURI, global::Grpc.CMS.GrpcArticleDetails>(
        MethodType.Unary,
        __ServiceName,
        "ContentDetail",
        __Marshaller_GrpcArticleContentURI,
        __Marshaller_GrpcArticleDetails);

    static readonly Method<global::Grpc.CMS.GrpcArticleContentURI, global::Grpc.CMS.GrpcArticlePageDetails> __Method_ContentPageDetail = new Method<global::Grpc.CMS.GrpcArticleContentURI, global::Grpc.CMS.GrpcArticlePageDetails>(
        MethodType.Unary,
        __ServiceName,
        "ContentPageDetail",
        __Marshaller_GrpcArticleContentURI,
        __Marshaller_GrpcArticlePageDetails);

    static readonly Method<global::Grpc.CMS.GrpcArticleRecentURI, global::Grpc.CMS.GrpcArticleSummaryList> __Method_MostRecentList = new Method<global::Grpc.CMS.GrpcArticleRecentURI, global::Grpc.CMS.GrpcArticleSummaryList>(
        MethodType.Unary,
        __ServiceName,
        "MostRecentList",
        __Marshaller_GrpcArticleRecentURI,
        __Marshaller_GrpcArticleSummaryList);

    static readonly Method<global::Grpc.CMS.GrpcArticleFeatureURI, global::Grpc.CMS.GrpcArticleSummaryList> __Method_FeaturedList = new Method<global::Grpc.CMS.GrpcArticleFeatureURI, global::Grpc.CMS.GrpcArticleSummaryList>(
        MethodType.Unary,
        __ServiceName,
        "FeaturedList",
        __Marshaller_GrpcArticleFeatureURI,
        __Marshaller_GrpcArticleSummaryList);

    static readonly Method<global::Grpc.CMS.GrpcArticleRelatedURI, global::Grpc.CMS.GrpcArticleSummaryList> __Method_RelatedList = new Method<global::Grpc.CMS.GrpcArticleRelatedURI, global::Grpc.CMS.GrpcArticleSummaryList>(
        MethodType.Unary,
        __ServiceName,
        "RelatedList",
        __Marshaller_GrpcArticleRelatedURI,
        __Marshaller_GrpcArticleSummaryList);

    static readonly Method<global::Grpc.CMS.GrpcMakeDetailURI, global::Grpc.CMS.GrpcMakeAndModelDetailList> __Method_MakeList = new Method<global::Grpc.CMS.GrpcMakeDetailURI, global::Grpc.CMS.GrpcMakeAndModelDetailList>(
        MethodType.Unary,
        __ServiceName,
        "MakeList",
        __Marshaller_GrpcMakeDetailURI,
        __Marshaller_GrpcMakeAndModelDetailList);

    static readonly Method<global::Grpc.CMS.GrpcModelDetailURI, global::Grpc.CMS.GrpcMakeAndModelDetailList> __Method_ModelListByMake = new Method<global::Grpc.CMS.GrpcModelDetailURI, global::Grpc.CMS.GrpcMakeAndModelDetailList>(
        MethodType.Unary,
        __ServiceName,
        "ModelListByMake",
        __Marshaller_GrpcModelDetailURI,
        __Marshaller_GrpcMakeAndModelDetailList);

    // service descriptor
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Grpc.CMS.ArticleReflection.Descriptor.Services[0]; }
    }

    // client interface
    public interface IGrpcArticleClient
    {
      global::Grpc.CMS.GrpcCMSContent ListByCategory(global::Grpc.CMS.GrpcArticleByCatURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::Grpc.CMS.GrpcCMSContent ListByCategory(global::Grpc.CMS.GrpcArticleByCatURI request, CallOptions options);
      AsyncUnaryCall<global::Grpc.CMS.GrpcCMSContent> ListByCategoryAsync(global::Grpc.CMS.GrpcArticleByCatURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::Grpc.CMS.GrpcCMSContent> ListByCategoryAsync(global::Grpc.CMS.GrpcArticleByCatURI request, CallOptions options);
      global::Grpc.CMS.GrpcCMSContent ListBySubCategory(global::Grpc.CMS.GrpcArticleBySubCatURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::Grpc.CMS.GrpcCMSContent ListBySubCategory(global::Grpc.CMS.GrpcArticleBySubCatURI request, CallOptions options);
      AsyncUnaryCall<global::Grpc.CMS.GrpcCMSContent> ListBySubCategoryAsync(global::Grpc.CMS.GrpcArticleBySubCatURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::Grpc.CMS.GrpcCMSContent> ListBySubCategoryAsync(global::Grpc.CMS.GrpcArticleBySubCatURI request, CallOptions options);
      global::Grpc.CMS.GrpcArticleDetails ContentDetail(global::Grpc.CMS.GrpcArticleContentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::Grpc.CMS.GrpcArticleDetails ContentDetail(global::Grpc.CMS.GrpcArticleContentURI request, CallOptions options);
      AsyncUnaryCall<global::Grpc.CMS.GrpcArticleDetails> ContentDetailAsync(global::Grpc.CMS.GrpcArticleContentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::Grpc.CMS.GrpcArticleDetails> ContentDetailAsync(global::Grpc.CMS.GrpcArticleContentURI request, CallOptions options);
      global::Grpc.CMS.GrpcArticlePageDetails ContentPageDetail(global::Grpc.CMS.GrpcArticleContentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::Grpc.CMS.GrpcArticlePageDetails ContentPageDetail(global::Grpc.CMS.GrpcArticleContentURI request, CallOptions options);
      AsyncUnaryCall<global::Grpc.CMS.GrpcArticlePageDetails> ContentPageDetailAsync(global::Grpc.CMS.GrpcArticleContentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::Grpc.CMS.GrpcArticlePageDetails> ContentPageDetailAsync(global::Grpc.CMS.GrpcArticleContentURI request, CallOptions options);
      global::Grpc.CMS.GrpcArticleSummaryList MostRecentList(global::Grpc.CMS.GrpcArticleRecentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::Grpc.CMS.GrpcArticleSummaryList MostRecentList(global::Grpc.CMS.GrpcArticleRecentURI request, CallOptions options);
      AsyncUnaryCall<global::Grpc.CMS.GrpcArticleSummaryList> MostRecentListAsync(global::Grpc.CMS.GrpcArticleRecentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::Grpc.CMS.GrpcArticleSummaryList> MostRecentListAsync(global::Grpc.CMS.GrpcArticleRecentURI request, CallOptions options);
      global::Grpc.CMS.GrpcArticleSummaryList FeaturedList(global::Grpc.CMS.GrpcArticleFeatureURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::Grpc.CMS.GrpcArticleSummaryList FeaturedList(global::Grpc.CMS.GrpcArticleFeatureURI request, CallOptions options);
      AsyncUnaryCall<global::Grpc.CMS.GrpcArticleSummaryList> FeaturedListAsync(global::Grpc.CMS.GrpcArticleFeatureURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::Grpc.CMS.GrpcArticleSummaryList> FeaturedListAsync(global::Grpc.CMS.GrpcArticleFeatureURI request, CallOptions options);
      global::Grpc.CMS.GrpcArticleSummaryList RelatedList(global::Grpc.CMS.GrpcArticleRelatedURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::Grpc.CMS.GrpcArticleSummaryList RelatedList(global::Grpc.CMS.GrpcArticleRelatedURI request, CallOptions options);
      AsyncUnaryCall<global::Grpc.CMS.GrpcArticleSummaryList> RelatedListAsync(global::Grpc.CMS.GrpcArticleRelatedURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::Grpc.CMS.GrpcArticleSummaryList> RelatedListAsync(global::Grpc.CMS.GrpcArticleRelatedURI request, CallOptions options);
      global::Grpc.CMS.GrpcMakeAndModelDetailList MakeList(global::Grpc.CMS.GrpcMakeDetailURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::Grpc.CMS.GrpcMakeAndModelDetailList MakeList(global::Grpc.CMS.GrpcMakeDetailURI request, CallOptions options);
      AsyncUnaryCall<global::Grpc.CMS.GrpcMakeAndModelDetailList> MakeListAsync(global::Grpc.CMS.GrpcMakeDetailURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::Grpc.CMS.GrpcMakeAndModelDetailList> MakeListAsync(global::Grpc.CMS.GrpcMakeDetailURI request, CallOptions options);
      global::Grpc.CMS.GrpcMakeAndModelDetailList ModelListByMake(global::Grpc.CMS.GrpcModelDetailURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      global::Grpc.CMS.GrpcMakeAndModelDetailList ModelListByMake(global::Grpc.CMS.GrpcModelDetailURI request, CallOptions options);
      AsyncUnaryCall<global::Grpc.CMS.GrpcMakeAndModelDetailList> ModelListByMakeAsync(global::Grpc.CMS.GrpcModelDetailURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken));
      AsyncUnaryCall<global::Grpc.CMS.GrpcMakeAndModelDetailList> ModelListByMakeAsync(global::Grpc.CMS.GrpcModelDetailURI request, CallOptions options);
    }

    // server-side interface
    public interface IGrpcArticle
    {
      Task<global::Grpc.CMS.GrpcCMSContent> ListByCategory(global::Grpc.CMS.GrpcArticleByCatURI request, ServerCallContext context);
      Task<global::Grpc.CMS.GrpcCMSContent> ListBySubCategory(global::Grpc.CMS.GrpcArticleBySubCatURI request, ServerCallContext context);
      Task<global::Grpc.CMS.GrpcArticleDetails> ContentDetail(global::Grpc.CMS.GrpcArticleContentURI request, ServerCallContext context);
      Task<global::Grpc.CMS.GrpcArticlePageDetails> ContentPageDetail(global::Grpc.CMS.GrpcArticleContentURI request, ServerCallContext context);
      Task<global::Grpc.CMS.GrpcArticleSummaryList> MostRecentList(global::Grpc.CMS.GrpcArticleRecentURI request, ServerCallContext context);
      Task<global::Grpc.CMS.GrpcArticleSummaryList> FeaturedList(global::Grpc.CMS.GrpcArticleFeatureURI request, ServerCallContext context);
      Task<global::Grpc.CMS.GrpcArticleSummaryList> RelatedList(global::Grpc.CMS.GrpcArticleRelatedURI request, ServerCallContext context);
      Task<global::Grpc.CMS.GrpcMakeAndModelDetailList> MakeList(global::Grpc.CMS.GrpcMakeDetailURI request, ServerCallContext context);
      Task<global::Grpc.CMS.GrpcMakeAndModelDetailList> ModelListByMake(global::Grpc.CMS.GrpcModelDetailURI request, ServerCallContext context);
    }

    // client stub
    public class GrpcArticleClient : ClientBase, IGrpcArticleClient
    {
      public GrpcArticleClient(Channel channel) : base(channel)
      {
      }
      public global::Grpc.CMS.GrpcCMSContent ListByCategory(global::Grpc.CMS.GrpcArticleByCatURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_ListByCategory, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::Grpc.CMS.GrpcCMSContent ListByCategory(global::Grpc.CMS.GrpcArticleByCatURI request, CallOptions options)
      {
        var call = CreateCall(__Method_ListByCategory, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpc.CMS.GrpcCMSContent> ListByCategoryAsync(global::Grpc.CMS.GrpcArticleByCatURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_ListByCategory, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpc.CMS.GrpcCMSContent> ListByCategoryAsync(global::Grpc.CMS.GrpcArticleByCatURI request, CallOptions options)
      {
        var call = CreateCall(__Method_ListByCategory, options);
        return Calls.AsyncUnaryCall(call, request);
      }
      public global::Grpc.CMS.GrpcCMSContent ListBySubCategory(global::Grpc.CMS.GrpcArticleBySubCatURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_ListBySubCategory, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::Grpc.CMS.GrpcCMSContent ListBySubCategory(global::Grpc.CMS.GrpcArticleBySubCatURI request, CallOptions options)
      {
        var call = CreateCall(__Method_ListBySubCategory, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpc.CMS.GrpcCMSContent> ListBySubCategoryAsync(global::Grpc.CMS.GrpcArticleBySubCatURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_ListBySubCategory, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpc.CMS.GrpcCMSContent> ListBySubCategoryAsync(global::Grpc.CMS.GrpcArticleBySubCatURI request, CallOptions options)
      {
        var call = CreateCall(__Method_ListBySubCategory, options);
        return Calls.AsyncUnaryCall(call, request);
      }
      public global::Grpc.CMS.GrpcArticleDetails ContentDetail(global::Grpc.CMS.GrpcArticleContentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_ContentDetail, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::Grpc.CMS.GrpcArticleDetails ContentDetail(global::Grpc.CMS.GrpcArticleContentURI request, CallOptions options)
      {
        var call = CreateCall(__Method_ContentDetail, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpc.CMS.GrpcArticleDetails> ContentDetailAsync(global::Grpc.CMS.GrpcArticleContentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_ContentDetail, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpc.CMS.GrpcArticleDetails> ContentDetailAsync(global::Grpc.CMS.GrpcArticleContentURI request, CallOptions options)
      {
        var call = CreateCall(__Method_ContentDetail, options);
        return Calls.AsyncUnaryCall(call, request);
      }
      public global::Grpc.CMS.GrpcArticlePageDetails ContentPageDetail(global::Grpc.CMS.GrpcArticleContentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_ContentPageDetail, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::Grpc.CMS.GrpcArticlePageDetails ContentPageDetail(global::Grpc.CMS.GrpcArticleContentURI request, CallOptions options)
      {
        var call = CreateCall(__Method_ContentPageDetail, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpc.CMS.GrpcArticlePageDetails> ContentPageDetailAsync(global::Grpc.CMS.GrpcArticleContentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_ContentPageDetail, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpc.CMS.GrpcArticlePageDetails> ContentPageDetailAsync(global::Grpc.CMS.GrpcArticleContentURI request, CallOptions options)
      {
        var call = CreateCall(__Method_ContentPageDetail, options);
        return Calls.AsyncUnaryCall(call, request);
      }
      public global::Grpc.CMS.GrpcArticleSummaryList MostRecentList(global::Grpc.CMS.GrpcArticleRecentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_MostRecentList, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::Grpc.CMS.GrpcArticleSummaryList MostRecentList(global::Grpc.CMS.GrpcArticleRecentURI request, CallOptions options)
      {
        var call = CreateCall(__Method_MostRecentList, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpc.CMS.GrpcArticleSummaryList> MostRecentListAsync(global::Grpc.CMS.GrpcArticleRecentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_MostRecentList, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpc.CMS.GrpcArticleSummaryList> MostRecentListAsync(global::Grpc.CMS.GrpcArticleRecentURI request, CallOptions options)
      {
        var call = CreateCall(__Method_MostRecentList, options);
        return Calls.AsyncUnaryCall(call, request);
      }
      public global::Grpc.CMS.GrpcArticleSummaryList FeaturedList(global::Grpc.CMS.GrpcArticleFeatureURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_FeaturedList, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::Grpc.CMS.GrpcArticleSummaryList FeaturedList(global::Grpc.CMS.GrpcArticleFeatureURI request, CallOptions options)
      {
        var call = CreateCall(__Method_FeaturedList, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpc.CMS.GrpcArticleSummaryList> FeaturedListAsync(global::Grpc.CMS.GrpcArticleFeatureURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_FeaturedList, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpc.CMS.GrpcArticleSummaryList> FeaturedListAsync(global::Grpc.CMS.GrpcArticleFeatureURI request, CallOptions options)
      {
        var call = CreateCall(__Method_FeaturedList, options);
        return Calls.AsyncUnaryCall(call, request);
      }
      public global::Grpc.CMS.GrpcArticleSummaryList RelatedList(global::Grpc.CMS.GrpcArticleRelatedURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_RelatedList, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::Grpc.CMS.GrpcArticleSummaryList RelatedList(global::Grpc.CMS.GrpcArticleRelatedURI request, CallOptions options)
      {
        var call = CreateCall(__Method_RelatedList, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpc.CMS.GrpcArticleSummaryList> RelatedListAsync(global::Grpc.CMS.GrpcArticleRelatedURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_RelatedList, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpc.CMS.GrpcArticleSummaryList> RelatedListAsync(global::Grpc.CMS.GrpcArticleRelatedURI request, CallOptions options)
      {
        var call = CreateCall(__Method_RelatedList, options);
        return Calls.AsyncUnaryCall(call, request);
      }
      public global::Grpc.CMS.GrpcMakeAndModelDetailList MakeList(global::Grpc.CMS.GrpcMakeDetailURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_MakeList, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::Grpc.CMS.GrpcMakeAndModelDetailList MakeList(global::Grpc.CMS.GrpcMakeDetailURI request, CallOptions options)
      {
        var call = CreateCall(__Method_MakeList, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpc.CMS.GrpcMakeAndModelDetailList> MakeListAsync(global::Grpc.CMS.GrpcMakeDetailURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_MakeList, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpc.CMS.GrpcMakeAndModelDetailList> MakeListAsync(global::Grpc.CMS.GrpcMakeDetailURI request, CallOptions options)
      {
        var call = CreateCall(__Method_MakeList, options);
        return Calls.AsyncUnaryCall(call, request);
      }
      public global::Grpc.CMS.GrpcMakeAndModelDetailList ModelListByMake(global::Grpc.CMS.GrpcModelDetailURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_ModelListByMake, new CallOptions(headers, deadline, cancellationToken));
        return Calls.BlockingUnaryCall(call, request);
      }
      public global::Grpc.CMS.GrpcMakeAndModelDetailList ModelListByMake(global::Grpc.CMS.GrpcModelDetailURI request, CallOptions options)
      {
        var call = CreateCall(__Method_ModelListByMake, options);
        return Calls.BlockingUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpc.CMS.GrpcMakeAndModelDetailList> ModelListByMakeAsync(global::Grpc.CMS.GrpcModelDetailURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        var call = CreateCall(__Method_ModelListByMake, new CallOptions(headers, deadline, cancellationToken));
        return Calls.AsyncUnaryCall(call, request);
      }
      public AsyncUnaryCall<global::Grpc.CMS.GrpcMakeAndModelDetailList> ModelListByMakeAsync(global::Grpc.CMS.GrpcModelDetailURI request, CallOptions options)
      {
        var call = CreateCall(__Method_ModelListByMake, options);
        return Calls.AsyncUnaryCall(call, request);
      }
    }

    // creates service definition that can be registered with a server
    public static ServerServiceDefinition BindService(IGrpcArticle serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder(__ServiceName)
          .AddMethod(__Method_ListByCategory, serviceImpl.ListByCategory)
          .AddMethod(__Method_ListBySubCategory, serviceImpl.ListBySubCategory)
          .AddMethod(__Method_ContentDetail, serviceImpl.ContentDetail)
          .AddMethod(__Method_ContentPageDetail, serviceImpl.ContentPageDetail)
          .AddMethod(__Method_MostRecentList, serviceImpl.MostRecentList)
          .AddMethod(__Method_FeaturedList, serviceImpl.FeaturedList)
          .AddMethod(__Method_RelatedList, serviceImpl.RelatedList)
          .AddMethod(__Method_MakeList, serviceImpl.MakeList)
          .AddMethod(__Method_ModelListByMake, serviceImpl.ModelListByMake).Build();
    }

    // creates a new client
    public static GrpcArticleClient NewClient(Channel channel)
    {
      return new GrpcArticleClient(channel);
    }

  }
}
#endregion
