// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace EditCMSWindowsService.Messages {
  public static class EditCMSGrpcService
  {
    static readonly string __ServiceName = "EditCMSWindowsService.EditCMSGrpcService";

    static readonly Marshaller<global::EditCMSWindowsService.Messages.GrpcArticleRecentURI> __Marshaller_GrpcArticleRecentURI = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EditCMSWindowsService.Messages.GrpcArticleRecentURI.Parser.ParseFrom);
    static readonly Marshaller<global::EditCMSWindowsService.Messages.GrpcArticleSummaryList> __Marshaller_GrpcArticleSummaryList = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EditCMSWindowsService.Messages.GrpcArticleSummaryList.Parser.ParseFrom);
    static readonly Marshaller<global::EditCMSWindowsService.Messages.GrpcArticleByCatURI> __Marshaller_GrpcArticleByCatURI = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EditCMSWindowsService.Messages.GrpcArticleByCatURI.Parser.ParseFrom);
    static readonly Marshaller<global::EditCMSWindowsService.Messages.GrpcCMSContent> __Marshaller_GrpcCMSContent = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EditCMSWindowsService.Messages.GrpcCMSContent.Parser.ParseFrom);
    static readonly Marshaller<global::EditCMSWindowsService.Messages.GrpcArticleContentURI> __Marshaller_GrpcArticleContentURI = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EditCMSWindowsService.Messages.GrpcArticleContentURI.Parser.ParseFrom);
    static readonly Marshaller<global::EditCMSWindowsService.Messages.GrpcArticleDetails> __Marshaller_GrpcArticleDetails = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EditCMSWindowsService.Messages.GrpcArticleDetails.Parser.ParseFrom);
    static readonly Marshaller<global::EditCMSWindowsService.Messages.GrpcArticlePageDetails> __Marshaller_GrpcArticlePageDetails = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EditCMSWindowsService.Messages.GrpcArticlePageDetails.Parser.ParseFrom);
    static readonly Marshaller<global::EditCMSWindowsService.Messages.GrpcModelPhotoURI> __Marshaller_GrpcModelPhotoURI = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EditCMSWindowsService.Messages.GrpcModelPhotoURI.Parser.ParseFrom);
    static readonly Marshaller<global::EditCMSWindowsService.Messages.GrpcModelImageList> __Marshaller_GrpcModelImageList = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EditCMSWindowsService.Messages.GrpcModelImageList.Parser.ParseFrom);
    static readonly Marshaller<global::EditCMSWindowsService.Messages.GrpcFeatureCarURI> __Marshaller_GrpcFeatureCarURI = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EditCMSWindowsService.Messages.GrpcFeatureCarURI.Parser.ParseFrom);
    static readonly Marshaller<global::EditCMSWindowsService.Messages.GrpcInt> __Marshaller_GrpcInt = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EditCMSWindowsService.Messages.GrpcInt.Parser.ParseFrom);

    static readonly Method<global::EditCMSWindowsService.Messages.GrpcArticleRecentURI, global::EditCMSWindowsService.Messages.GrpcArticleSummaryList> __Method_GetMostRecentArticles = new Method<global::EditCMSWindowsService.Messages.GrpcArticleRecentURI, global::EditCMSWindowsService.Messages.GrpcArticleSummaryList>(
        MethodType.Unary,
        __ServiceName,
        "GetMostRecentArticles",
        __Marshaller_GrpcArticleRecentURI,
        __Marshaller_GrpcArticleSummaryList);

    static readonly Method<global::EditCMSWindowsService.Messages.GrpcArticleByCatURI, global::EditCMSWindowsService.Messages.GrpcCMSContent> __Method_GetContentListByCategory = new Method<global::EditCMSWindowsService.Messages.GrpcArticleByCatURI, global::EditCMSWindowsService.Messages.GrpcCMSContent>(
        MethodType.Unary,
        __ServiceName,
        "GetContentListByCategory",
        __Marshaller_GrpcArticleByCatURI,
        __Marshaller_GrpcCMSContent);

    static readonly Method<global::EditCMSWindowsService.Messages.GrpcArticleContentURI, global::EditCMSWindowsService.Messages.GrpcArticleDetails> __Method_GetContentDetails = new Method<global::EditCMSWindowsService.Messages.GrpcArticleContentURI, global::EditCMSWindowsService.Messages.GrpcArticleDetails>(
        MethodType.Unary,
        __ServiceName,
        "GetContentDetails",
        __Marshaller_GrpcArticleContentURI,
        __Marshaller_GrpcArticleDetails);

    static readonly Method<global::EditCMSWindowsService.Messages.GrpcArticleContentURI, global::EditCMSWindowsService.Messages.GrpcArticlePageDetails> __Method_GetContentPages = new Method<global::EditCMSWindowsService.Messages.GrpcArticleContentURI, global::EditCMSWindowsService.Messages.GrpcArticlePageDetails>(
        MethodType.Unary,
        __ServiceName,
        "GetContentPages",
        __Marshaller_GrpcArticleContentURI,
        __Marshaller_GrpcArticlePageDetails);

    static readonly Method<global::EditCMSWindowsService.Messages.GrpcModelPhotoURI, global::EditCMSWindowsService.Messages.GrpcModelImageList> __Method_GetModelPhotosList = new Method<global::EditCMSWindowsService.Messages.GrpcModelPhotoURI, global::EditCMSWindowsService.Messages.GrpcModelImageList>(
        MethodType.Unary,
        __ServiceName,
        "GetModelPhotosList",
        __Marshaller_GrpcModelPhotoURI,
        __Marshaller_GrpcModelImageList);

    static readonly Method<global::EditCMSWindowsService.Messages.GrpcArticleContentURI, global::EditCMSWindowsService.Messages.GrpcModelImageList> __Method_GetArticlePhotos = new Method<global::EditCMSWindowsService.Messages.GrpcArticleContentURI, global::EditCMSWindowsService.Messages.GrpcModelImageList>(
        MethodType.Unary,
        __ServiceName,
        "GetArticlePhotos",
        __Marshaller_GrpcArticleContentURI,
        __Marshaller_GrpcModelImageList);

    static readonly Method<global::EditCMSWindowsService.Messages.GrpcFeatureCarURI, global::EditCMSWindowsService.Messages.GrpcInt> __Method_GrpcGetFeaturedCar = new Method<global::EditCMSWindowsService.Messages.GrpcFeatureCarURI, global::EditCMSWindowsService.Messages.GrpcInt>(
        MethodType.Unary,
        __ServiceName,
        "GrpcGetFeaturedCar",
        __Marshaller_GrpcFeatureCarURI,
        __Marshaller_GrpcInt);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::EditCMSWindowsService.Messages.MessagesReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of EditCMSGrpcService</summary>
    public abstract class EditCMSGrpcServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::EditCMSWindowsService.Messages.GrpcArticleSummaryList> GetMostRecentArticles(global::EditCMSWindowsService.Messages.GrpcArticleRecentURI request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::EditCMSWindowsService.Messages.GrpcCMSContent> GetContentListByCategory(global::EditCMSWindowsService.Messages.GrpcArticleByCatURI request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::EditCMSWindowsService.Messages.GrpcArticleDetails> GetContentDetails(global::EditCMSWindowsService.Messages.GrpcArticleContentURI request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::EditCMSWindowsService.Messages.GrpcArticlePageDetails> GetContentPages(global::EditCMSWindowsService.Messages.GrpcArticleContentURI request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::EditCMSWindowsService.Messages.GrpcModelImageList> GetModelPhotosList(global::EditCMSWindowsService.Messages.GrpcModelPhotoURI request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::EditCMSWindowsService.Messages.GrpcModelImageList> GetArticlePhotos(global::EditCMSWindowsService.Messages.GrpcArticleContentURI request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::EditCMSWindowsService.Messages.GrpcInt> GrpcGetFeaturedCar(global::EditCMSWindowsService.Messages.GrpcFeatureCarURI request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for EditCMSGrpcService</summary>
    public class EditCMSGrpcServiceClient : ClientBase<EditCMSGrpcServiceClient>
    {
      /// <summary>Creates a new client for EditCMSGrpcService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public EditCMSGrpcServiceClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for EditCMSGrpcService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public EditCMSGrpcServiceClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected EditCMSGrpcServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected EditCMSGrpcServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::EditCMSWindowsService.Messages.GrpcArticleSummaryList GetMostRecentArticles(global::EditCMSWindowsService.Messages.GrpcArticleRecentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetMostRecentArticles(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EditCMSWindowsService.Messages.GrpcArticleSummaryList GetMostRecentArticles(global::EditCMSWindowsService.Messages.GrpcArticleRecentURI request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetMostRecentArticles, null, options, request);
      }
      public virtual AsyncUnaryCall<global::EditCMSWindowsService.Messages.GrpcArticleSummaryList> GetMostRecentArticlesAsync(global::EditCMSWindowsService.Messages.GrpcArticleRecentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetMostRecentArticlesAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::EditCMSWindowsService.Messages.GrpcArticleSummaryList> GetMostRecentArticlesAsync(global::EditCMSWindowsService.Messages.GrpcArticleRecentURI request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetMostRecentArticles, null, options, request);
      }
      public virtual global::EditCMSWindowsService.Messages.GrpcCMSContent GetContentListByCategory(global::EditCMSWindowsService.Messages.GrpcArticleByCatURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetContentListByCategory(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EditCMSWindowsService.Messages.GrpcCMSContent GetContentListByCategory(global::EditCMSWindowsService.Messages.GrpcArticleByCatURI request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetContentListByCategory, null, options, request);
      }
      public virtual AsyncUnaryCall<global::EditCMSWindowsService.Messages.GrpcCMSContent> GetContentListByCategoryAsync(global::EditCMSWindowsService.Messages.GrpcArticleByCatURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetContentListByCategoryAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::EditCMSWindowsService.Messages.GrpcCMSContent> GetContentListByCategoryAsync(global::EditCMSWindowsService.Messages.GrpcArticleByCatURI request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetContentListByCategory, null, options, request);
      }
      public virtual global::EditCMSWindowsService.Messages.GrpcArticleDetails GetContentDetails(global::EditCMSWindowsService.Messages.GrpcArticleContentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetContentDetails(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EditCMSWindowsService.Messages.GrpcArticleDetails GetContentDetails(global::EditCMSWindowsService.Messages.GrpcArticleContentURI request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetContentDetails, null, options, request);
      }
      public virtual AsyncUnaryCall<global::EditCMSWindowsService.Messages.GrpcArticleDetails> GetContentDetailsAsync(global::EditCMSWindowsService.Messages.GrpcArticleContentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetContentDetailsAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::EditCMSWindowsService.Messages.GrpcArticleDetails> GetContentDetailsAsync(global::EditCMSWindowsService.Messages.GrpcArticleContentURI request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetContentDetails, null, options, request);
      }
      public virtual global::EditCMSWindowsService.Messages.GrpcArticlePageDetails GetContentPages(global::EditCMSWindowsService.Messages.GrpcArticleContentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetContentPages(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EditCMSWindowsService.Messages.GrpcArticlePageDetails GetContentPages(global::EditCMSWindowsService.Messages.GrpcArticleContentURI request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetContentPages, null, options, request);
      }
      public virtual AsyncUnaryCall<global::EditCMSWindowsService.Messages.GrpcArticlePageDetails> GetContentPagesAsync(global::EditCMSWindowsService.Messages.GrpcArticleContentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetContentPagesAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::EditCMSWindowsService.Messages.GrpcArticlePageDetails> GetContentPagesAsync(global::EditCMSWindowsService.Messages.GrpcArticleContentURI request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetContentPages, null, options, request);
      }
      public virtual global::EditCMSWindowsService.Messages.GrpcModelImageList GetModelPhotosList(global::EditCMSWindowsService.Messages.GrpcModelPhotoURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetModelPhotosList(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EditCMSWindowsService.Messages.GrpcModelImageList GetModelPhotosList(global::EditCMSWindowsService.Messages.GrpcModelPhotoURI request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetModelPhotosList, null, options, request);
      }
      public virtual AsyncUnaryCall<global::EditCMSWindowsService.Messages.GrpcModelImageList> GetModelPhotosListAsync(global::EditCMSWindowsService.Messages.GrpcModelPhotoURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetModelPhotosListAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::EditCMSWindowsService.Messages.GrpcModelImageList> GetModelPhotosListAsync(global::EditCMSWindowsService.Messages.GrpcModelPhotoURI request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetModelPhotosList, null, options, request);
      }
      public virtual global::EditCMSWindowsService.Messages.GrpcModelImageList GetArticlePhotos(global::EditCMSWindowsService.Messages.GrpcArticleContentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetArticlePhotos(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EditCMSWindowsService.Messages.GrpcModelImageList GetArticlePhotos(global::EditCMSWindowsService.Messages.GrpcArticleContentURI request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetArticlePhotos, null, options, request);
      }
      public virtual AsyncUnaryCall<global::EditCMSWindowsService.Messages.GrpcModelImageList> GetArticlePhotosAsync(global::EditCMSWindowsService.Messages.GrpcArticleContentURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetArticlePhotosAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::EditCMSWindowsService.Messages.GrpcModelImageList> GetArticlePhotosAsync(global::EditCMSWindowsService.Messages.GrpcArticleContentURI request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetArticlePhotos, null, options, request);
      }
      public virtual global::EditCMSWindowsService.Messages.GrpcInt GrpcGetFeaturedCar(global::EditCMSWindowsService.Messages.GrpcFeatureCarURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GrpcGetFeaturedCar(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EditCMSWindowsService.Messages.GrpcInt GrpcGetFeaturedCar(global::EditCMSWindowsService.Messages.GrpcFeatureCarURI request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GrpcGetFeaturedCar, null, options, request);
      }
      public virtual AsyncUnaryCall<global::EditCMSWindowsService.Messages.GrpcInt> GrpcGetFeaturedCarAsync(global::EditCMSWindowsService.Messages.GrpcFeatureCarURI request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GrpcGetFeaturedCarAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::EditCMSWindowsService.Messages.GrpcInt> GrpcGetFeaturedCarAsync(global::EditCMSWindowsService.Messages.GrpcFeatureCarURI request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GrpcGetFeaturedCar, null, options, request);
      }
      protected override EditCMSGrpcServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new EditCMSGrpcServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(EditCMSGrpcServiceBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetMostRecentArticles, serviceImpl.GetMostRecentArticles)
          .AddMethod(__Method_GetContentListByCategory, serviceImpl.GetContentListByCategory)
          .AddMethod(__Method_GetContentDetails, serviceImpl.GetContentDetails)
          .AddMethod(__Method_GetContentPages, serviceImpl.GetContentPages)
          .AddMethod(__Method_GetModelPhotosList, serviceImpl.GetModelPhotosList)
          .AddMethod(__Method_GetArticlePhotos, serviceImpl.GetArticlePhotos)
          .AddMethod(__Method_GrpcGetFeaturedCar, serviceImpl.GrpcGetFeaturedCar).Build();
    }

  }
}
#endregion
