const newsListAction = {
	FETCH_NEWSLIST: 'FETCH_NEWSLIST',
	FETCH_NEWSLIST_SUCCESS: 'FETCH_NEWSLIST_SUCCESS',
	FETCH_NEWSLIST_FAILURE: 'FETCH_NEWSLIST_FAILURE',
	NEWSLIST_RESET: 'NEWSLIST_RESET'
}

const newsDetailAction = {
	FETCH_NEWSDETAIL: 'FETCH_NEWSDETAIL',
	FETCH_NEWSDETAIL_WITH_INITIAL_DATA : 'FETCH_NEWSDETAIL_WITH_INITIAL_DATA',
	FETCH_NEWSDETAIL_SUCCESS: 'FETCH_NEWSDETAIL_SUCCESS',
	FETCH_NEWSDETAIL_FAILURE: 'FETCH_NEWSDETAIL_FAILURE',
	NEWSDETAIL_RESET: 'NEWSDETAIL_RESET'

}

const newBikesListAction = {
	FETCH_NEW_BIKES_LIST_FOR_NEWS_LIST : 'FETCH_NEW_BIKES_LIST_FOR_NEWS_LIST',
	FETCH_NEW_BIKES_LIST_SUCCESS_FOR_NEWS_LIST : 'FETCH_NEW_BIKES_LIST_SUCCESS_FOR_NEWS_LIST',
	FETCH_NEW_BIKES_LIST_FAILURE_FOR_NEWS_LIST : 'FETCH_NEW_BIKES_LIST_FAILURE_FOR_NEWS_LIST',
	NEW_BIKES_LIST_RESET_FOR_NEWS_LIST : 'NEW_BIKES_LIST_RESET_FOR_NEWS_LIST',
	FETCH_NEW_BIKES_LIST_FOR_NEWS_DETAIL : 'FETCH_NEW_BIKES_LIST_FOR_NEWS_DETAIL',
	FETCH_NEW_BIKES_LIST_SUCCESS_FOR_NEWS_DETAIL : 'FETCH_NEW_BIKES_LIST_SUCCESS_FOR_NEWS_DETAIL',
	FETCH_NEW_BIKES_LIST_FAILURE_FOR_NEWS_DETAIL : 'FETCH_NEW_BIKES_LIST_FAILURE_FOR_NEWS_DETAIL',
	NEW_BIKES_LIST_RESET_FOR_NEWS_DETAIL : 'NEW_BIKES_LIST_RESET_FOR_NEWS_DETAIL',
}

const modelObjectAction = {
	FETCH_MODEL_OBJECT_FOR_NEWS_DETAIL : 'FETCH_MODEL_OBJECT_FOR_NEWS_DETAIL',
	FETCH_MODEL_OBJECT_SUCCESS_FOR_NEWS_DETAIL : 'FETCH_MODEL_OBJECT_SUCCESS_FOR_NEWS_DETAIL',
	FETCH_MODEL_OBJECT_FAILURE_FOR_NEWS_DETAIL : 'FETCH_MODEL_OBJECT_FAILURE_FOR_NEWS_DETAIL',
	MODEL_OBJECT_RESET_FOR_NEWS_DETAIL : 'MODEL_OBJECT_RESET_FOR_NEWS_DETAIL'
}

const videosLandingAction = {
	FETCH_TOPVIDEOSLANDING : 'FETCH_TOPVIDEOSLANDING',
	FETCH_TOPVIDEOSLANDING_SUCCESS : 'FETCH_TOPVIDEOSLANDING_SUCCESS',
	FETCH_TOPVIDEOSLANDING_FAILURE : 'FETCH_TOPVIDEOSLANDING_FAILURE',
	FETCH_TOPVIDEOSLANDING_RESET : 'FETCH_TOPVIDEOSLANDING_RESET',
	FETCH_OTHERVIDEOSLANDING : 'FETCH_OTHERVIDEOSLANDING',
	FETCH_OTHERVIDEOSLANDING_SUCCESS : 'FETCH_OTHERVIDEOSLANDING_SUCCESS',
	FETCH_OTHERVIDEOSLANDING_FAILURE : 'FETCH_OTHERVIDEOSLANDING_FAILURE',
	FETCH_OTHERVIDEOSLANDING_RESET : 'FETCH_OTHERVIDEOSLANDING_RESET'
}

const videosByCategoryAction = {
	'FETCH' : 'FETCH',
	'FETCH_WITH_INITIAL_DATA' : 'FETCH_WITH_INITIAL_DATA',
	'FETCH_SUCCESS' : 'FETCH_SUCCESS',
	'FETCH_ERROR' : 'FETCH_ERROR',
	'FETCH_RESET' : 'FETCH_RESET',

}

const videosDetailAction = {
	FETCH_VIDEODETAIL : 'FETCH_VIDEODETAIL',
	FETCH_VIDEODETAIL_WITH_INITIAL_DATA : 'FETCH_VIDEODETAIL_WITH_INITIAL_DATA',
	FETCH_VIDEODETAIL_SUCCESS : 'FETCH_VIDEODETAIL_SUCCESS',
	FETCH_VIDEODETAIL_ERROR : 'FETCH_VIDEODETAIL_ERROR',
	FETCH_VIDEODETAIL_RESET : 'FETCH_MODELDETAIL_RESET',
	FETCH_MODELINFO : 'FETCH_MODELINFO',
	FETCH_MODELINFO_SUCCESS : 'FETCH_MODELINFO_SUCCESS',
	FETCH_MODELINFO_ERROR : 'FETCH_MODELINFO_ERROR',
	FETCH_MODELINFO_RESET : 'FETCH_MODELDETAIL_RESET',
	FETCH_RELATEDINFO : 'FETCH_RELATEDINFO',
	FETCH_RELATEDINFO_SUCCESS : 'FETCH_RELATEDINFO_SUCCESS',
	FETCH_RELATEDINFO_ERROR : 'FETCH_RELATEDINFO_ERROR',
	FETCH_RELATEDINFO_RESET : 'FETCH_RELATEDINFO_RESET'
}

const bikeImageCarouselAction = {
    FETCH_POPULAR_BIKELIST: 'FETCH_POPULAR_BIKELIST',
    FETCH_POPULAR_BIKELIST_SUCCESS: 'FETCH_POPULAR_BIKELIST_SUCCESS',
    FETCH_POPULAR_BIKELIST_FAILURE: 'FETCH_POPULAR_BIKELIST_FAILURE',
    POPULAR_BIKELIST_RESET: 'POPULAR_BIKELIST_RESET'

}

module.exports = {
	newsListAction : newsListAction,
	newsDetailAction : newsDetailAction,
	newBikesListAction : newBikesListAction,
	modelObjectAction : modelObjectAction,
	videosLandingAction : videosLandingAction,
	videosByCategoryAction : videosByCategoryAction,
	videosDetailAction : videosDetailAction,
	bikeImageCarouselAction : bikeImageCarouselAction
}

