const emiCalculatorAction = {
	OPEN_EMICALCULATOR : 'OPEN_EMICALCULATOR',
	UPDATE_DOWNPAYMENT_SLIDER_VALUE: 'UPDATE_DOWNPAYMENT_SLIDER_VALUE',
	UPDATE_TENURE_SLIDER_VALUE: 'UPDATE_TENURE_SLIDER_VALUE',
	UPDATE_INTEREST_SLIDER_VALUE: 'UPDATE_INTEREST_SLIDER_VALUE',
	UPDATE_PIE_VALUE: 'UPDATE_PIE_VALUE'
}

module.exports = {
	emiCalculatorAction: emiCalculatorAction
}

