const emiCalculatorAction = {
	UPDATE_DOWNPAYMENT_SLIDER_VALUE: 'UPDATE_DOWNPAYMENT_SLIDER_VALUE',
	UPDATE_TENURE_SLIDER_VALUE: 'UPDATE_TENURE_SLIDER_VALUE',
	UPDATE_INTEREST_SLIDER_VALUE: 'UPDATE_INTEREST_SLIDER_VALUE',
	UPDATE_PIE_VALUE: 'UPDATE_PIE_VALUE',
	START_PIE_ANIMATION: 'START_PIE_ANIMATION',
  	STOP_PIE_ANIMATION: 'STOP_PIE_ANIMATION',
}

module.exports = {
	emiCalculatorAction: emiCalculatorAction
}

