const emiCalculatorAction = {
	UPDATE_DOWNPAYMENT_SLIDER_VALUE: 'UPDATE_DOWNPAYMENT_SLIDER_VALUE',
	UPDATE_TENURE_SLIDER_VALUE: 'UPDATE_TENURE_SLIDER_VALUE',
	UPDATE_INTEREST_SLIDER_VALUE: 'UPDATE_INTEREST_SLIDER_VALUE'
}

module.exports = {
	emiCalculatorAction: emiCalculatorAction
}

