export const financeCityPopup = {
    FETCH_CITY: 'FETCH_CITY',
    FETCH_CITY_SUCCESS: 'FETCH_CITY_SUCCESS',
    FETCH_CITY_FAILURE: 'FETCH_CITY_FAILURE',
    OPEN_CITY_POPUP: 'OPEN_CITY_POPUP',
    CLOSE_CITY_POPUP: 'CLOSE_CITY_POPUP',
    SET_CITY: 'SET_CITY',
    CITY_NEXT: 'CITY_NEXT'
}
