export const selectBikePopup = {
  OPEN_BIKE_POPUP: 'OPEN_BIKE_POPUP',
  CLOSE_BIKE_POPUP: 'CLOSE_BIKE_POPUP',
  SELECT_MODEL: 'SELECT_MODEL',
  SET_BIKE_VERSION: 'SET_BIKE_VERSION',
  FETCH_BIKELIST_SUCCESS: 'FETCH_BIKELIST_SUCCESS',
  FETCH_BIKELIST_FAILURE: 'FETCH_BIKELIST_FAILURE',
  RESET_BIKELIST_FAILURE: 'RESET_BIKELIST_FAILURE',
  FETCHING_VERSIONLIST : 'FETCHING_VERSIONLIST',
  FETCH_VERSIONLIST_SUCCESS: 'FETCH_VERSIONLIST_SUCCESS',
  FETCH_VERSIONLIST_FAILURE: 'FETCH_VERSIONLIST_FAILURE',
  RESET_VERSIONLIST_FAILURE: 'RESET_VERSIONLIST_FAILURE',
  FETCH_MODEL_DETAIL: 'FETCH_MODEL_DETAIL',
  FETCH_MODEL_DETAIL_SUCCESS: 'FETCH_MODEL_DETAIL_SUCCESS',
  FETCH_MODEL_DETAIL_FAILURE: 'FETCH_MODEL_DETAIL_FAILURE',
  RESET_MODEL_DETAIL_FAILURE: 'RESET_MODEL_DETAIL_FAILURE'
}
