export const similarBikesEMI = {
  FETCH_SIMILAR_BIKES_EMI: 'FETCH_SIMILAR_BIKES_EMI',
  UPDATE_EMI: 'UPDATE_EMI',
  FETCH_SIMILAR_BIKES_FAILED : 'FETCH_SIMILAR_BIKES_FAILED',
  FETCHING_SIMILAR_BIKES: 'FETCHING_SIMILAR_BIKES'
}
