//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Bikewale.RabbitMq.LeadProcessingConsumer.RoyalEnfieldWebAPI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback affiliatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback Landing_pageOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrganicOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::Bikewale.RabbitMq.LeadProcessingConsumer.Properties.Settings.Default.Bikewale_RabbitMq_LeadProcessingConsumer_RoyalEnfieldWebAPI_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event affiliatesCompletedEventHandler affiliatesCompleted;
        
        /// <remarks/>
        public event Landing_pageCompletedEventHandler Landing_pageCompleted;
        
        /// <remarks/>
        public event OrganicCompletedEventHandler OrganicCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/affiliates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string affiliates(string Name, string mobile, string EMail, string State, string City, string Dealer_Name, string Bike_Detail, string Web_link, string Tocken, string UTM, string Dealer_Code) {
            object[] results = this.Invoke("affiliates", new object[] {
                        Name,
                        mobile,
                        EMail,
                        State,
                        City,
                        Dealer_Name,
                        Bike_Detail,
                        Web_link,
                        Tocken,
                        UTM,
                        Dealer_Code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void affiliatesAsync(string Name, string mobile, string EMail, string State, string City, string Dealer_Name, string Bike_Detail, string Web_link, string Tocken, string UTM, string Dealer_Code) {
            this.affiliatesAsync(Name, mobile, EMail, State, City, Dealer_Name, Bike_Detail, Web_link, Tocken, UTM, Dealer_Code, null);
        }
        
        /// <remarks/>
        public void affiliatesAsync(string Name, string mobile, string EMail, string State, string City, string Dealer_Name, string Bike_Detail, string Web_link, string Tocken, string UTM, string Dealer_Code, object userState) {
            if ((this.affiliatesOperationCompleted == null)) {
                this.affiliatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaffiliatesOperationCompleted);
            }
            this.InvokeAsync("affiliates", new object[] {
                        Name,
                        mobile,
                        EMail,
                        State,
                        City,
                        Dealer_Name,
                        Bike_Detail,
                        Web_link,
                        Tocken,
                        UTM,
                        Dealer_Code}, this.affiliatesOperationCompleted, userState);
        }
        
        private void OnaffiliatesOperationCompleted(object arg) {
            if ((this.affiliatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.affiliatesCompleted(this, new affiliatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Landing_page", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Landing_page(string Name, string mobile, string EMail, string State, string City, string Dealer_Name, string Bike_Detail, string Web_link, string Tocken, string UTM, string Dealer_Code) {
            object[] results = this.Invoke("Landing_page", new object[] {
                        Name,
                        mobile,
                        EMail,
                        State,
                        City,
                        Dealer_Name,
                        Bike_Detail,
                        Web_link,
                        Tocken,
                        UTM,
                        Dealer_Code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Landing_pageAsync(string Name, string mobile, string EMail, string State, string City, string Dealer_Name, string Bike_Detail, string Web_link, string Tocken, string UTM, string Dealer_Code) {
            this.Landing_pageAsync(Name, mobile, EMail, State, City, Dealer_Name, Bike_Detail, Web_link, Tocken, UTM, Dealer_Code, null);
        }
        
        /// <remarks/>
        public void Landing_pageAsync(string Name, string mobile, string EMail, string State, string City, string Dealer_Name, string Bike_Detail, string Web_link, string Tocken, string UTM, string Dealer_Code, object userState) {
            if ((this.Landing_pageOperationCompleted == null)) {
                this.Landing_pageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLanding_pageOperationCompleted);
            }
            this.InvokeAsync("Landing_page", new object[] {
                        Name,
                        mobile,
                        EMail,
                        State,
                        City,
                        Dealer_Name,
                        Bike_Detail,
                        Web_link,
                        Tocken,
                        UTM,
                        Dealer_Code}, this.Landing_pageOperationCompleted, userState);
        }
        
        private void OnLanding_pageOperationCompleted(object arg) {
            if ((this.Landing_pageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Landing_pageCompleted(this, new Landing_pageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Organic", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Organic(string Name, string mobile, string Country, string State, string City, string EMail, string Motorcycle, string Dealer_Name, string When_do_plan_to_buy, string Web_link, string Tocken, string UTM, string Dealer_Code) {
            object[] results = this.Invoke("Organic", new object[] {
                        Name,
                        mobile,
                        Country,
                        State,
                        City,
                        EMail,
                        Motorcycle,
                        Dealer_Name,
                        When_do_plan_to_buy,
                        Web_link,
                        Tocken,
                        UTM,
                        Dealer_Code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OrganicAsync(string Name, string mobile, string Country, string State, string City, string EMail, string Motorcycle, string Dealer_Name, string When_do_plan_to_buy, string Web_link, string Tocken, string UTM, string Dealer_Code) {
            this.OrganicAsync(Name, mobile, Country, State, City, EMail, Motorcycle, Dealer_Name, When_do_plan_to_buy, Web_link, Tocken, UTM, Dealer_Code, null);
        }
        
        /// <remarks/>
        public void OrganicAsync(string Name, string mobile, string Country, string State, string City, string EMail, string Motorcycle, string Dealer_Name, string When_do_plan_to_buy, string Web_link, string Tocken, string UTM, string Dealer_Code, object userState) {
            if ((this.OrganicOperationCompleted == null)) {
                this.OrganicOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrganicOperationCompleted);
            }
            this.InvokeAsync("Organic", new object[] {
                        Name,
                        mobile,
                        Country,
                        State,
                        City,
                        EMail,
                        Motorcycle,
                        Dealer_Name,
                        When_do_plan_to_buy,
                        Web_link,
                        Tocken,
                        UTM,
                        Dealer_Code}, this.OrganicOperationCompleted, userState);
        }
        
        private void OnOrganicOperationCompleted(object arg) {
            if ((this.OrganicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrganicCompleted(this, new OrganicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void affiliatesCompletedEventHandler(object sender, affiliatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class affiliatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal affiliatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Landing_pageCompletedEventHandler(object sender, Landing_pageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Landing_pageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Landing_pageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void OrganicCompletedEventHandler(object sender, OrganicCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrganicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrganicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591