using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Bikewale.DTO.UserProfile
{
    /// <summary>
    /// Created By : Deepak Israni on 6 July 2018
    /// Description : DTO for User Profiling Data generated by Bhrigu.
    /// </summary>
    public class UserProfileTargetingDTO
    {
        [JsonProperty("targetingData")]
        public IDictionary<string, string> TargetingData { get; set; }
    }
}
