CREATE TABLE [dbo].[TC_Insurance_Inquiries] (
    [TC_Insurance_InquiriesId] INT           IDENTITY (1, 1) NOT NULL,
    [TC_InquiriesLeadId]       INT           NULL,
    [TC_LeadDispositionId]     INT           NULL,
    [RegistrationNumber]       VARCHAR (20)  NULL,
    [VersionId]                INT           NULL,
    [EntryDate]                DATETIME      NULL,
    [ModifiedDate]             DATETIME      NULL,
    [ModifiedBy]               INT           NULL,
    [InsuranceProvider]        VARCHAR (50)  NULL,
    [PolicyNumber]             VARCHAR (50)  NULL,
    [ExpiryDate]               DATETIME      NULL,
    [IsClaimsExist]            BIT           NULL,
    [BranchId]                 INT           NULL,
    [PaymentCompletedDate]     DATETIME      NULL,
    [IDV]                      INT           NULL,
    [NCB]                      FLOAT (53)    NULL,
    [Discount]                 FLOAT (53)    NULL,
    [Premium]                  INT           NULL,
    [HypothecationId]          TINYINT       NULL,
    [CoverNote]                VARCHAR (25)  NULL,
    [PaymentFailedDate]        DATETIME      NULL,
    [PaymentMode]              TINYINT       NULL,
    [PaymentConfirmationId]    VARCHAR (100) NULL,
    [ChequeNumber]             VARCHAR (20)  NULL,
    [RenewalConfirmedDate]     DATETIME      NULL,
    [IsZeroDep]                BIT           NULL,
    [ChequePickUpAddress]      VARCHAR (200) NULL,
    [CollectionDateTime]       DATETIME      NULL,
    [PaymentMethod]            TINYINT       NULL,
    [AssignedTo]               INT           NULL,
    [CreatedBy]                INT           NULL,
    CONSTRAINT [PK__TC_Insur__054BEB3656302854] PRIMARY KEY CLUSTERED ([TC_Insurance_InquiriesId] ASC)
);

