CREATE TABLE [dbo].[TC_InquiriesLeadDispositionBkp] (
    [TC_InquiriesLeadId]           BIGINT        NOT NULL,
    [BranchId]                     NUMERIC (18)  NULL,
    [TC_CustomerId]                BIGINT        NULL,
    [TC_UserId]                    BIGINT        NULL,
    [InquiryCount]                 SMALLINT      NULL,
    [NextFollowUpDate]             DATETIME      NULL,
    [LastFollowUpDate]             DATETIME      NULL,
    [LastFollowUpComment]          VARCHAR (MAX) NULL,
    [TC_InquiryTypeId]             SMALLINT      NULL,
    [TC_InquiryStatusId]           SMALLINT      NULL,
    [TC_InquiriesFollowupActionId] SMALLINT      NULL,
    [CreatedBy]                    BIGINT        NULL,
    [CreatedDate]                  DATETIME      NULL,
    [ModifiedBy]                   BIGINT        NULL,
    [ModifiedDate]                 DATETIME      NULL,
    [IsActionTaken]                BIT           NULL,
    [TC_LeadTypeId]                TINYINT       NULL,
    [InqTypeDesc]                  VARCHAR (100) NULL,
    [IsActive]                     BIT           NULL,
    [Old_TC_CustomerId]            BIGINT        NULL,
    [TC_LeadId]                    INT           NULL,
    [TC_LeadInquiryTypeId]         TINYINT       NULL,
    [TC_LeadStageId]               TINYINT       NULL,
    [TC_LeadDispositionID]         TINYINT       NULL,
    [CarDetails]                   VARCHAR (MAX) NULL,
    [LatestInquiryDate]            DATETIME      NULL,
    [InqSourceId]                  SMALLINT      NULL,
    [TC_CampaignSchedulingId]      INT           NULL
);

