CREATE TABLE [dbo].[TC_Insurance_Reminder] (
    [TC_Insurance_ReminderId]  INT           IDENTITY (1, 1) NOT NULL,
    [RegistrationNumber]       VARCHAR (20)  NULL,
    [VersionId]                INT           NULL,
    [EntryDate]                DATETIME      NULL,
    [ModifiedDate]             DATETIME      NULL,
    [ModifiedBy]               INT           NULL,
    [InsuranceProvider]        VARCHAR (50)  NULL,
    [PolicyNumber]             VARCHAR (50)  NULL,
    [ExpiryDate]               DATETIME      NULL,
    [IsClaimsExist]            BIT           NULL,
    [BranchId]                 INT           NULL,
    [MfgYear]                  VARCHAR (5)   NULL,
    [EngineNumber]             VARCHAR (20)  NULL,
    [ChassisNumber]            VARCHAR (20)  NULL,
    [HypothecationId]          TINYINT       NULL,
    [PolicyPeriodFrom]         DATETIME      NULL,
    [MappingInqId]             INT           NULL,
    [LastIDV]                  INT           NULL,
    [LastNCB]                  FLOAT (53)    NULL,
    [LastDiscount]             FLOAT (53)    NULL,
    [LastPremium]              INT           NULL,
    [CustomerName]             VARCHAR (100) NULL,
    [MobileNumber]             VARCHAR (10)  NULL,
    [CarName]                  VARCHAR (100) NULL,
    [CustomerId]               INT           NULL,
    [RegistrationNumberSearch] VARCHAR (50)  NULL,
    [RegisteredAddress]        VARCHAR (100) NULL,
    [AlternateMobileNumber]    VARCHAR (10)  NULL,
    [AssignedTo]               INT           NULL
);

