CREATE TABLE [dbo].[TC_NewCarInquiries_MI0] (
    [TC_NewCarInquiriesId]       INT            IDENTITY (1, 1) NOT NULL,
    [TC_InquiriesLeadId]         BIGINT         NULL,
    [TC_InquirySourceId]         INT            NULL,
    [CreatedOn]                  DATETIME       NOT NULL,
    [CreatedBy]                  INT            NULL,
    [VersionId]                  NUMERIC (18)   NULL,
    [Buytime]                    TINYINT        NULL,
    [BuyDate]                    DATETIME       NULL,
    [TC_LeadDispositionId]       TINYINT        NULL,
    [PQDate]                     DATETIME       NULL,
    [PQStatus]                   TINYINT        NULL,
    [TDDate]                     DATETIME       NULL,
    [TDStatus]                   TINYINT        NULL,
    [BookingDate]                DATETIME       NULL,
    [BookingStatus]              TINYINT        NULL,
    [CityId]                     NUMERIC (18)   NULL,
    [PQRequestedDate]            DATETIME       NULL,
    [TDRequestedDate]            DATETIME       NULL,
    [TC_TDCalendarId]            BIGINT         NULL,
    [TransmissionType]           TINYINT        NULL,
    [FuelType]                   TINYINT        NULL,
    [TC_InquiryOtherSourceId]    TINYINT        NULL,
    [Comments]                   VARCHAR (5000) NULL,
    [IsCorporate]                BIT            NOT NULL,
    [CompanyName]                VARCHAR (150)  NULL,
    [IsWillingnessToExchange]    BIT            NULL,
    [IsFinanceRequired]          BIT            NULL,
    [IsAccessoriesRequired]      BIT            NULL,
    [IsSchemesOffered]           BIT            NULL,
    [ExcelInquiryId]             INT            NULL,
    [CarDeliveryDate]            DATETIME       NULL,
    [CarDeliveryStatus]          SMALLINT       NULL,
    [TC_SubDispositionId]        SMALLINT       NULL,
    [LostVersionId]              INT            NULL,
    [DispositionDate]            DATETIME       NULL,
    [BookingEventDate]           DATETIME       NULL,
    [BookingCancelDate]          DATETIME       NULL,
    [IsExchange]                 BIT            NULL,
    [TDStatusEntryDate]          DATETIME       NULL,
    [TC_CampaignSchedulingId]    INT            NULL,
    [TC_NewCarExchangeId]        INT            NULL,
    [DealerCampaignSchedulingId] INT            NULL,
    [NSCCampaignSchedulingId]    INT            NULL,
    [BookingRequest]             BIT            NULL,
    [BookingRequestDate]         DATETIME       NULL,
    [AppointmentRequest]         BIT            NULL,
    [AppointmentRequestDate]     DATETIME       NULL,
    [CwOfferId]                  INT            NULL,
    [CouponCode]                 VARCHAR (10)   NULL,
    [CWInquiryId]                INT            NULL,
    [TC_ActionApplicationId]     INT            NULL,
    [DMSScreenShotHostUrl]       VARCHAR (100)  NULL,
    [DMSScreenShotStatusId]      INT            NULL,
    [DMSScreenShotUrl]           VARCHAR (250)  NULL,
    [TC_LeadDispositionReason]   VARCHAR (200)  NULL,
    [OriginalImgPath]            VARCHAR (250)  NULL,
    [CampaignId]                 INT            NULL,
    [ContractId]                 INT            NULL,
    [MostInterested]             BIT            NULL
);

