CREATE TABLE [dbo].[TC_NewCarInquiriesDataCorrection] (
    [TC_NewCarInquiriesId]    INT            NOT NULL,
    [TC_InquiriesLeadId]      BIGINT         NULL,
    [TC_InquirySourceId]      INT            NULL,
    [CreatedOn]               DATETIME       NOT NULL,
    [CreatedBy]               INT            NULL,
    [VersionId]               NUMERIC (18)   NULL,
    [Buytime]                 TINYINT        NULL,
    [BuyDate]                 DATETIME       NULL,
    [TC_LeadDispositionId]    TINYINT        NULL,
    [PQDate]                  DATETIME       NULL,
    [PQStatus]                TINYINT        NULL,
    [TDDate]                  DATETIME       NULL,
    [TDStatus]                TINYINT        NULL,
    [BookingDate]             DATETIME       NULL,
    [BookingStatus]           TINYINT        NULL,
    [CityId]                  NUMERIC (18)   NULL,
    [PQRequestedDate]         DATETIME       NULL,
    [TDRequestedDate]         DATETIME       NULL,
    [TC_TDCalendarId]         BIGINT         NULL,
    [TransmissionType]        TINYINT        NULL,
    [FuelType]                TINYINT        NULL,
    [TC_InquiryOtherSourceId] TINYINT        NULL,
    [Comments]                VARCHAR (5000) NULL,
    [IsCorporate]             BIT            NOT NULL,
    [CompanyName]             VARCHAR (100)  NULL,
    [IsWillingnessToExchange] BIT            NULL,
    [IsFinanceRequired]       BIT            NULL,
    [IsAccessoriesRequired]   BIT            NULL,
    [IsSchemesOffered]        BIT            NULL,
    [ExcelInquiryId]          INT            NULL,
    [CarDeliveryDate]         DATETIME       NULL,
    [CarDeliveryStatus]       SMALLINT       NULL,
    [TC_SubDispositionId]     SMALLINT       NULL,
    [LostVersionId]           INT            NULL,
    [DispositionDate]         DATETIME       NULL,
    [BookingEventDate]        DATETIME       NULL,
    [BookingCancelDate]       DATETIME       NULL,
    [IsExchange]              BIT            NULL,
    [TDStatusEntryDate]       DATETIME       NULL,
    [TC_CampaignSchedulingId] INT            NULL
);

