CREATE TABLE [dbo].[TC_Service_Inquiries] (
    [TC_Service_InquiriesId] INT           IDENTITY (1, 1) NOT NULL,
    [TC_InquiriesLeadId]     INT           NOT NULL,
    [TC_LeadDispositionId]   INT           NULL,
    [RegistrationNumber]     VARCHAR (50)  NOT NULL,
    [VersionId]              INT           NOT NULL,
    [Kms]                    INT           NULL,
    [ServiceType]            TINYINT       NULL,
    [ServiceDate]            DATETIME      NULL,
    [LastServiceDate]        DATETIME      NULL,
    [BookComments]           VARCHAR (500) NULL,
    [IsPickUpRequested]      BIT           NULL,
    [PickUpRequestedDate]    DATETIME      NULL,
    [PickUpCompletedDate]    DATETIME      NULL,
    [EntryDate]              DATETIME      NULL,
    [ServiceCompletedDate]   DATETIME      NULL,
    [BookingStatus]          SMALLINT      NULL,
    [ModifiedDate]           DATETIME      NULL,
    [ModifiedBy]             INT           NULL,
    [ReopenComments]         VARCHAR (500) NULL,
    [Comments]               VARCHAR (500) NULL,
    [ServiceDeliveredDate]   DATETIME      NULL,
    [ServiceDueDate]         DATETIME      NULL,
    [FeedbackRating]         TINYINT       NULL,
    [DispositionComment]     VARCHAR (500) NULL,
    [DropRequestedDate]      DATETIME      NULL,
    [DropCompletedDate]      DATETIME      NULL,
    CONSTRAINT [PK_TC_Service_Inquiries] PRIMARY KEY CLUSTERED ([TC_Service_InquiriesId] ASC)
);

