CREATE TABLE [dbo].[TC_SpecialUsers] (
    [TC_SpecialUsersId]   INT                 IDENTITY (1, 1) NOT NULL,
    [UserName]            VARCHAR (100)       NOT NULL,
    [Email]               VARCHAR (100)       NOT NULL,
    [Password]            VARCHAR (20)        NOT NULL,
    [Mobile]              VARCHAR (10)        NULL,
    [Sex]                 VARCHAR (6)         NULL,
    [DOB]                 DATE                NULL,
    [Address]             VARCHAR (200)       NULL,
    [MakeId]              SMALLINT            NULL,
    [IsActive]            BIT                 CONSTRAINT [DF_TC_SpecialUsersTest_IsActive] DEFAULT ((1)) NOT NULL,
    [IsFirstTimeLoggedIn] BIT                 CONSTRAINT [DF_TC_SpecialUsersTest_IsFirstTimeLoggedIn] DEFAULT ((1)) NULL,
    [GCMRegistrationId]   VARCHAR (250)       NULL,
    [EntryDate]           DATETIME            CONSTRAINT [DF_TC_SpecialUsersTest_EntryDate] DEFAULT (getdate()) NOT NULL,
    [ModifiedDate]        DATETIME            NULL,
    [ModifiedBy]          INT                 NULL,
    [HierId]              [sys].[hierarchyid] NULL,
    [lvl]                 AS                  ([HierId].[GetLevel]()) PERSISTED,
    [NodeCode]            AS                  ([HierId].[ToString]()) PERSISTED,
    [ReportingType]       TINYINT             NULL,
    [Designation]         TINYINT             NULL,
    [ReportsTo]           INT                 NULL,
    [PwdRecoveryEmail]    VARCHAR (50)        NULL,
    [AliasUserId]         INT                 NULL,
    [UniqueId]            VARCHAR (50)        CONSTRAINT [DF_TC_SpecialUsers_UniqueId] DEFAULT (CONVERT([varchar](20),right(newid(),(12)),(0))+CONVERT([varchar](8),getdate(),(112))) NULL,
    CONSTRAINT [PK_TC_SpecialUsersTest] PRIMARY KEY CLUSTERED ([TC_SpecialUsersId] ASC),
    CONSTRAINT [UQ__TC_SpecialUsers_EmailTest] UNIQUE NONCLUSTERED ([Email] ASC)
);

