CREATE TABLE [dbo].[tempucalertrecomm] (
    [rownum]                     SMALLINT      NULL,
    [UsedCarAlert_Id]            INT           NOT NULL,
    [CustomerName]               VARCHAR (150) NULL,
    [CustomerAlert_Email]        VARCHAR (100) NULL,
    [ProfileId]                  VARCHAR (50)  NULL,
    [Car_City]                   VARCHAR (50)  NULL,
    [Car_SellerId]               INT           NULL,
    [Car_Price]                  INT           NULL,
    [Car_MakeId]                 INT           NULL,
    [Car_ModelId]                INT           NULL,
    [Car_Make]                   VARCHAR (50)  NULL,
    [Car_Model]                  VARCHAR (60)  NULL,
    [Car_Seller]                 VARCHAR (10)  NOT NULL,
    [Car_Kms]                    INT           NULL,
    [Car_Version]                VARCHAR (60)  NULL,
    [Car_Year]                   INT           NULL,
    [Car_Color]                  VARCHAR (50)  NULL,
    [Car_HasPhoto]               BIT           NULL,
    [Car_LastUpdated]            DATETIME      NULL,
    [CustomerAlert_City]         VARCHAR (50)  NULL,
    [CustomerAlert_Budget]       INT           NULL,
    [CustomerAlert_MakeYear]     INT           NULL,
    [CustomerAlert_Kms]          INT           NULL,
    [CustomerAlert_Make]         VARCHAR (80)  NULL,
    [CustomerAlert_Model]        VARCHAR (100) NULL,
    [CustomerAlert_FuelType]     INT           NULL,
    [CustomerAlert_BodyStyle]    INT           NULL,
    [CustomerAlert_Transmission] INT           NULL,
    [CustomerAlert_Seller]       INT           NULL,
    [alertUrl]                   VARCHAR (100) NULL,
    [ImageUrl]                   VARCHAR (200) NULL,
    [CustomerKey]                VARCHAR (50)  NOT NULL,
    [MatchingCars]               INT           NULL
);

