CREATE TABLE [dbo].[TempCustomers] (
    [Id]                   NUMERIC (18)  IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Name]                 VARCHAR (100) NOT NULL,
    [email]                VARCHAR (100) NOT NULL,
    [Address]              VARCHAR (250) NULL,
    [Area]                 VARCHAR (100) NULL,
    [City]                 VARCHAR (100) NULL,
    [State]                INT           NULL,
    [PinCode]              NUMERIC (18)  NULL,
    [phone1]               VARCHAR (20)  NULL,
    [phone2]               VARCHAR (20)  NULL,
    [Mobile]               VARCHAR (20)  NULL,
    [password]             VARCHAR (20)  NULL,
    [PrimaryPhone]         TINYINT       CONSTRAINT [DF_TempCustomers_PrimaryPhone] DEFAULT (1) NOT NULL,
    [Industry]             VARCHAR (100) NULL,
    [Designation]          VARCHAR (100) NULL,
    [Organization]         VARCHAR (100) NULL,
    [DOB]                  DATETIME      NULL,
    [ContactHours]         VARCHAR (50)  NULL,
    [ContactMode]          VARCHAR (10)  NULL,
    [CurrentVehicle]       VARCHAR (200) NULL,
    [InternetUsePlace]     VARCHAR (20)  NULL,
    [CarwaleContact]       VARCHAR (200) NULL,
    [InternetUseTime]      SMALLINT      NULL,
    [ReceiveNewsletters]   BIT           CONSTRAINT [DF_TempCustomers_ReceiveNewsletters] DEFAULT (1) NULL,
    [RegistrationDateTime] DATETIME      NOT NULL,
    CONSTRAINT [PK_TempCustomers] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [IX_TempCustomers] UNIQUE NONCLUSTERED ([email] ASC) WITH (FILLFACTOR = 90)
);

