CREATE TABLE [dbo].[UP_Tags] (
    [UPT_Id]  NUMERIC (18) IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [PhotoId] NUMERIC (18) NULL,
    [TagId]   NUMERIC (18) NULL,
    CONSTRAINT [PK_UP_Tags] PRIMARY KEY CLUSTERED ([UPT_Id] ASC) WITH (FILLFACTOR = 90)
);

