CREATE TABLE [dbo].[UsedCarChains] (
    [ID]       NUMERIC (18) IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Name]     VARCHAR (50) NOT NULL,
    [MakeId]   NUMERIC (18) NOT NULL,
    [IsActive] BIT          CONSTRAINT [DF_UsedCarChains_IsActive] DEFAULT (1) NOT NULL,
    CONSTRAINT [PK_UsedCarChains] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

