// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CarDataElasticDoc.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Entities.GrpcClass.ProtoClass {

  /// <summary>Holder for reflection information generated from CarDataElasticDoc.proto</summary>
  public static partial class CarDataElasticDocReflection {

    #region Descriptor
    /// <summary>File descriptor for CarDataElasticDoc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CarDataElasticDocReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdDYXJEYXRhRWxhc3RpY0RvYy5wcm90bxIdRW50aXRpZXMuR3JwY0NsYXNz",
            "LlByb3RvQ2xhc3MifgoRQ2FyRGF0YUVsYXN0aWNEb2MSDgoGTW9kZWxzGAEg",
            "AygFEhAKCFZlcnNpb25zGAIgAygFEg4KBkNpdGllcxgDIAMoBRI3CgRUeXBl",
            "GAQgASgOMikuRW50aXRpZXMuR3JwY0NsYXNzLlByb3RvQ2xhc3MuVXBkYXRl",
            "VHlwZSqCAgoKVXBkYXRlVHlwZRIKCgZEZWxldGUQABIRCg1Nb2RlbE92ZXJ2",
            "aWV3EAESEwoPVmVyc2lvbk92ZXJ2aWV3EAISDgoKQWxsQ2FyRGF0YRADEgsK",
            "B0NvbG91cnMQBBINCglOZXdzQ291bnQQBRIVChFFeHBlcnRSZXZpZXdDb3Vu",
            "dBAGEg4KClBob3RvQ291bnQQBxIOCgpWaWRlb0NvdW50EAgSFwoTU3BlY2lh",
            "bFJlcG9ydHNDb3VudBAJEgwKCFByaWNlQWRkEAoSDwoLUHJpY2VEZWxldGUQ",
            "CxITCg9CdWxrUHJpY2VVcGxvYWQQDBIQCgxBdmVyYWdlUHJpY2UQDWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Entities.GrpcClass.ProtoClass.UpdateType), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Entities.GrpcClass.ProtoClass.CarDataElasticDoc), global::Entities.GrpcClass.ProtoClass.CarDataElasticDoc.Parser, new[]{ "Models", "Versions", "Cities", "Type" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum UpdateType {
    [pbr::OriginalName("Delete")] Delete = 0,
    [pbr::OriginalName("ModelOverview")] ModelOverview = 1,
    [pbr::OriginalName("VersionOverview")] VersionOverview = 2,
    [pbr::OriginalName("AllCarData")] AllCarData = 3,
    [pbr::OriginalName("Colours")] Colours = 4,
    [pbr::OriginalName("NewsCount")] NewsCount = 5,
    [pbr::OriginalName("ExpertReviewCount")] ExpertReviewCount = 6,
    [pbr::OriginalName("PhotoCount")] PhotoCount = 7,
    [pbr::OriginalName("VideoCount")] VideoCount = 8,
    [pbr::OriginalName("SpecialReportsCount")] SpecialReportsCount = 9,
    [pbr::OriginalName("PriceAdd")] PriceAdd = 10,
    [pbr::OriginalName("PriceDelete")] PriceDelete = 11,
    [pbr::OriginalName("BulkPriceUpload")] BulkPriceUpload = 12,
    [pbr::OriginalName("AveragePrice")] AveragePrice = 13,
  }

  #endregion

  #region Messages
  public sealed partial class CarDataElasticDoc : pb::IMessage<CarDataElasticDoc> {
    private static readonly pb::MessageParser<CarDataElasticDoc> _parser = new pb::MessageParser<CarDataElasticDoc>(() => new CarDataElasticDoc());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CarDataElasticDoc> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Entities.GrpcClass.ProtoClass.CarDataElasticDocReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CarDataElasticDoc() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CarDataElasticDoc(CarDataElasticDoc other) : this() {
      models_ = other.models_.Clone();
      versions_ = other.versions_.Clone();
      cities_ = other.cities_.Clone();
      type_ = other.type_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CarDataElasticDoc Clone() {
      return new CarDataElasticDoc(this);
    }

    /// <summary>Field number for the "Models" field.</summary>
    public const int ModelsFieldNumber = 1;
    private static readonly pb::FieldCodec<int> _repeated_models_codec
        = pb::FieldCodec.ForInt32(10);
    private readonly pbc::RepeatedField<int> models_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Models {
      get { return models_; }
    }

    /// <summary>Field number for the "Versions" field.</summary>
    public const int VersionsFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_versions_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> versions_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Versions {
      get { return versions_; }
    }

    /// <summary>Field number for the "Cities" field.</summary>
    public const int CitiesFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_cities_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> cities_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Cities {
      get { return cities_; }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 4;
    private global::Entities.GrpcClass.ProtoClass.UpdateType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Entities.GrpcClass.ProtoClass.UpdateType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CarDataElasticDoc);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CarDataElasticDoc other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!models_.Equals(other.models_)) return false;
      if(!versions_.Equals(other.versions_)) return false;
      if(!cities_.Equals(other.cities_)) return false;
      if (Type != other.Type) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= models_.GetHashCode();
      hash ^= versions_.GetHashCode();
      hash ^= cities_.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      models_.WriteTo(output, _repeated_models_codec);
      versions_.WriteTo(output, _repeated_versions_codec);
      cities_.WriteTo(output, _repeated_cities_codec);
      if (Type != 0) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Type);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += models_.CalculateSize(_repeated_models_codec);
      size += versions_.CalculateSize(_repeated_versions_codec);
      size += cities_.CalculateSize(_repeated_cities_codec);
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CarDataElasticDoc other) {
      if (other == null) {
        return;
      }
      models_.Add(other.models_);
      versions_.Add(other.versions_);
      cities_.Add(other.cities_);
      if (other.Type != 0) {
        Type = other.Type;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10:
          case 8: {
            models_.AddEntriesFrom(input, _repeated_models_codec);
            break;
          }
          case 18:
          case 16: {
            versions_.AddEntriesFrom(input, _repeated_versions_codec);
            break;
          }
          case 26:
          case 24: {
            cities_.AddEntriesFrom(input, _repeated_cities_codec);
            break;
          }
          case 32: {
            type_ = (global::Entities.GrpcClass.ProtoClass.UpdateType) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
