//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carwale.BL.Chola {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.cholainsurance.com/CholaWebservice/CholaProductService.asmx", ConfigurationName="Chola.CholaProductServiceSoap")]
    public interface CholaProductServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.cholainsurance.com/CholaWebservice/CholaProductService.asmx/CholaCamp" +
            "aignService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CholaCampaignService(string Name, string EmailID, string MobileNo, string CarBrand, string CarModel, string policytype, string PolicyExpiryDate, string Vehicleno, string RTO, string Publisher, string ProductCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.cholainsurance.com/CholaWebservice/CholaProductService.asmx/CholaCamp" +
            "aignService", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CholaCampaignServiceAsync(string Name, string EmailID, string MobileNo, string CarBrand, string CarModel, string policytype, string PolicyExpiryDate, string Vehicleno, string RTO, string Publisher, string ProductCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CholaProductServiceSoapChannel : Carwale.BL.Chola.CholaProductServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CholaProductServiceSoapClient : System.ServiceModel.ClientBase<Carwale.BL.Chola.CholaProductServiceSoap>, Carwale.BL.Chola.CholaProductServiceSoap {
        
        public CholaProductServiceSoapClient() {
        }
        
        public CholaProductServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CholaProductServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CholaProductServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CholaProductServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CholaCampaignService(string Name, string EmailID, string MobileNo, string CarBrand, string CarModel, string policytype, string PolicyExpiryDate, string Vehicleno, string RTO, string Publisher, string ProductCode) {
            return base.Channel.CholaCampaignService(Name, EmailID, MobileNo, CarBrand, CarModel, policytype, PolicyExpiryDate, Vehicleno, RTO, Publisher, ProductCode);
        }
        
        public System.Threading.Tasks.Task<string> CholaCampaignServiceAsync(string Name, string EmailID, string MobileNo, string CarBrand, string CarModel, string policytype, string PolicyExpiryDate, string Vehicleno, string RTO, string Publisher, string ProductCode) {
            return base.Channel.CholaCampaignServiceAsync(Name, EmailID, MobileNo, CarBrand, CarModel, policytype, PolicyExpiryDate, Vehicleno, RTO, Publisher, ProductCode);
        }
    }
}
