CREATE TABLE [dbo].[DealerOffersTags] (
    [Id]  NUMERIC (18) IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Tag] VARCHAR (50) NULL,
    CONSTRAINT [PK_DealerOffersTag] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 90)
);

