CREATE TABLE [dbo].[DealerStockResponseAnalysis] (
    [DealerId]                 INT  NOT NULL,
    [Entrydate]                DATE NOT NULL,
    [CWStockCount]             INT  NULL,
    [TCStockCount]             INT  NULL,
    [Response]                 INT  NULL,
    [PhotoCount]               INT  NULL,
    [ResponsePhotoCount]       INT  NULL,
    [NoPhotoCount]             INT  NULL,
    [ResponseNoPhotoCount]     INT  NULL,
    [DescrCount]               INT  NULL,
    [ResponseDescrCount]       INT  NULL,
    [NoDescrCount]             INT  NULL,
    [ResponseNoDescrCount]     INT  NULL,
    [OverAgeCount]             INT  NULL,
    [ResponseOverAgeCount]     INT  NULL,
    [OverAgeNoCount]           INT  NULL,
    [ResponseNoOverAgeCount]   INT  NULL,
    [OverKMCount]              INT  NULL,
    [ResponseOverKMCount]      INT  NULL,
    [OverNoKMCount]            INT  NULL,
    [ResponseNoOverKMCount]    INT  NULL,
    [OverPriceCount]           INT  NULL,
    [ResponseOverPriceCount]   INT  NULL,
    [OverNoPriceCount]         INT  NULL,
    [ResponseNoOverPriceCount] INT  NULL,
    [StandardStock]            INT  NULL,
    [ResponseStandardStock]    INT  NULL,
    [NoStandardStock]          INT  NULL,
    [ResponseNoStandardStock]  INT  NULL,
    CONSTRAINT [PK_DealerStockResponseAnalysis] PRIMARY KEY CLUSTERED ([DealerId] ASC, [Entrydate] ASC)
);

