CREATE TABLE [dbo].[ESM_Region] (
    [id]   NUMERIC (18) IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Name] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_ESM_Region] PRIMARY KEY CLUSTERED ([id] ASC) WITH (FILLFACTOR = 90)
);

