CREATE TABLE [dbo].[FB_SkodaDealerDetails_backupJan2012] (
    [Id]                     NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [SkodaDealerId]          NUMERIC (18)  NOT NULL,
    [CityId]                 INT           NOT NULL,
    [DealerPrinciple]        VARCHAR (500) NULL,
    [DMobileNoAndEmail]      VARCHAR (500) NULL,
    [ContactPerson]          VARCHAR (500) NULL,
    [CMobileNoAndEmail]      VARCHAR (500) NULL,
    [ShowroomAddr]           VARCHAR (500) NULL,
    [ShowroomContactNo]      VARCHAR (500) NULL,
    [ShowroomEmail]          VARCHAR (500) NULL,
    [ShowroomFax]            VARCHAR (500) NULL,
    [ServiceCenter1Addr]     VARCHAR (500) NULL,
    [ServiceCenter2Addr]     VARCHAR (500) NULL,
    [ServiceCenterContactNo] VARCHAR (500) NULL,
    [ServiceCenterFax]       VARCHAR (500) NULL,
    [ServiceCenterEmail]     VARCHAR (500) NULL,
    [IsShowroom]             BIT           NOT NULL,
    [IsServiceCenter]        BIT           NOT NULL,
    [OutletName]             VARCHAR (50)  NULL,
    [OutletCode]             VARCHAR (50)  NULL,
    [SLattitude]             VARCHAR (50)  NULL,
    [SLongitude]             VARCHAR (50)  NULL,
    [WSLattitude]            VARCHAR (50)  NULL,
    [WSLongitude]            VARCHAR (50)  NULL,
    [WS2Lattitude]           VARCHAR (50)  NULL,
    [WS2Longitude]           VARCHAR (50)  NULL,
    [IsRapidOutlet]          BIT           NOT NULL
);

