CREATE TABLE [dbo].[LiveDeals] (
    [LiveDealsId]       INT            IDENTITY (1, 1) NOT NULL,
    [MakeId]            INT            NOT NULL,
    [Make]              VARCHAR (30)   NOT NULL,
    [ModelId]           INT            NOT NULL,
    [Model]             VARCHAR (30)   NOT NULL,
    [VersionId]         INT            NOT NULL,
    [Version]           VARCHAR (50)   NULL,
    [RootId]            SMALLINT       NULL,
    [RootName]          VARCHAR (80)   NULL,
    [MaskingName]       VARCHAR (50)   NULL,
    [StockId]           INT            NOT NULL,
    [ColorId]           INT            NOT NULL,
    [ColorCode]         VARCHAR (50)   NULL,
    [VersionColor]      VARCHAR (50)   NOT NULL,
    [MakeYear]          DATE           NOT NULL,
    [ActualOnroadPrice] INT            NOT NULL,
    [FinalOnRoadPrice]  INT            NOT NULL,
    [Offers]            VARCHAR (500)  NULL,
    [TermsConditions]   VARCHAR (500)  NULL,
    [CityId]            INT            NOT NULL,
    [CityName]          VARCHAR (50)   NOT NULL,
    [Savings]           INT            NULL,
    [DealerId]          INT            NOT NULL,
    [MaskingNumber]     VARCHAR (20)   NULL,
    [Organization]      VARCHAR (100)  NOT NULL,
    [StockCount]        INT            NULL,
    [FuelType]          TINYINT        NULL,
    [Transmission]      TINYINT        NULL,
    [BodyStyleId]       INT            NOT NULL,
    [HostURL]           VARCHAR (100)  NULL,
    [OriginalImgPath]   VARCHAR (150)  NULL,
    [SubSegmentId]      INT            NULL,
    [PriceUpdated]      BIT            NULL,
    [PriceBreakupId]    INT            NULL,
    [Offer_Value]       INT            NULL,
    [StockScore]        DECIMAL (8, 5) NULL,
    [ExtraSavings]      INT            NULL,
    [ShowExtraSavings]  BIT            NOT NULL,
    [DeliveryTimeline]  INT            NULL,
    CONSTRAINT [pk_LiveDealsID] PRIMARY KEY CLUSTERED ([StockId] ASC, [CityId] ASC)
);

