CREATE TABLE [dbo].[MakeGroups] (
    [ID]   NUMERIC (18) IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Name] VARCHAR (50) NULL,
    CONSTRAINT [PK_MakeGroups] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

