CREATE TABLE [dbo].[NewCarStandardFeatures] (
    [CarVersionId]          NUMERIC (18) NOT NULL,
    [PowerWindows]          CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_PowerWindows] DEFAULT ('N') NOT NULL,
    [PowerDoorLocks]        CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_PowerDoorLocks] DEFAULT ('N') NOT NULL,
    [PowerSteering]         CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_PowerSteering] DEFAULT ('N') NOT NULL,
    [AirConditioner]        CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_AirConditioner] DEFAULT ('N') NOT NULL,
    [ABS]                   CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_ABS] DEFAULT ('N') NOT NULL,
    [SteeringAdjustment]    CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_SteeringAdjustment] DEFAULT ('N') NOT NULL,
    [Tachometer]            CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_Tachometer] DEFAULT ('N') NOT NULL,
    [ChildSafetyLocks]      CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_ChildSafetyLocks] DEFAULT ('N') NOT NULL,
    [FrontFogLights]        CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_FrontFogLights] DEFAULT ('N') NOT NULL,
    [RearDefroster]         CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_RearDefroster] DEFAULT ('N') NOT NULL,
    [Defogger]              CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_Defogger] DEFAULT ('N') NOT NULL,
    [LeatherSeats]          CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_LeatherSeats] DEFAULT ('N') NOT NULL,
    [PowerSeats]            CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_PowerSeats] DEFAULT ('N') NOT NULL,
    [Radio]                 CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_Radio] DEFAULT ('N') NOT NULL,
    [CassettePlayer]        CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_CassettePlayer] DEFAULT ('N') NOT NULL,
    [CDPlayer]              CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_CDPlayer] DEFAULT ('N') NOT NULL,
    [SunRoof]               CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_SunRoof] DEFAULT ('N') NOT NULL,
    [MoonRoof]              CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_MoonRoof] DEFAULT ('N') NOT NULL,
    [TractionControl]       CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_TractionControl] DEFAULT ('-') NOT NULL,
    [Immobilizer]           CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_Immobilizer] DEFAULT ('-') NOT NULL,
    [DriverAirBags]         CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_DriverAirBags] DEFAULT ('-') NOT NULL,
    [PassengerAirBags]      CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_PassengerAirBags] DEFAULT ('-') NOT NULL,
    [RemoteBootFuelLid]     CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_RemoteBootFuelLid] DEFAULT ('-') NOT NULL,
    [CupHolder]             CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_CupHolder] DEFAULT ('-') NOT NULL,
    [SplitFoldingRearSeats] CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_SplitFoldingRearSeats] DEFAULT ('-') NOT NULL,
    [RearWashWiper]         CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_RearWashWiper] DEFAULT ('-') NOT NULL,
    [CentralLocking]        CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_CentralLocking] DEFAULT ('-') NOT NULL,
    [AlloyWheels]           CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_AlloyWheels] DEFAULT ('-') NOT NULL,
    [TubelessTyres]         CHAR (1)     CONSTRAINT [DF_NewCarStandardFeatures_TubelessTyres] DEFAULT ('-') NOT NULL,
    CONSTRAINT [PK_NewCarStandardFeatures] PRIMARY KEY CLUSTERED ([CarVersionId] ASC) WITH (FILLFACTOR = 90)
);

