CREATE TABLE [dbo].[NewCarSpecifications] (
    [CarVersionId]            INT             NOT NULL,
    [Length]                  INT             NULL,
    [Width]                   INT             NULL,
    [Height]                  INT             NULL,
    [Wheelbase]               INT             NULL,
    [GroundClearance]         INT             NULL,
    [FrontTrack]              INT             NULL,
    [RearTrack]               INT             NULL,
    [FrontHeadroom]           INT             NULL,
    [FrontLegroom]            INT             NULL,
    [RearLegroom]             INT             NULL,
    [Bootspace]               INT             NULL,
    [GrossWeight]             INT             NULL,
    [KerbWeight]              INT             NULL,
    [SeatingCapacity]         SMALLINT        NULL,
    [FuelTankCapacity]        INT             NULL,
    [Doors]                   INT             NULL,
    [MileageHighway]          FLOAT (53)      NULL,
    [MileageCity]             FLOAT (53)      NULL,
    [MileageOverall]          FLOAT (53)      NULL,
    [EngineType]              VARCHAR (200)   NULL,
    [Displacement]            INT             NULL,
    [Power]                   VARCHAR (50)    NULL,
    [Torque]                  VARCHAR (50)    NULL,
    [ValueMechanism]          VARCHAR (200)   NULL,
    [Bore]                    FLOAT (53)      NULL,
    [Stroke]                  FLOAT (53)      NULL,
    [CompressionRatio]        FLOAT (53)      NULL,
    [NoOfCylinders]           SMALLINT        NULL,
    [CylinderConfiguration]   VARCHAR (200)   NULL,
    [ValvesPerCylinder]       SMALLINT        NULL,
    [EngineBlockMaterial]     VARCHAR (50)    NULL,
    [BlockHeadMaterial]       VARCHAR (50)    NULL,
    [FuelType]                VARCHAR (50)    NULL,
    [FuelSystem]              VARCHAR (200)   NULL,
    [IgnitionType]            VARCHAR (200)   NULL,
    [Speeds]                  SMALLINT        NULL,
    [MaxSpeed]                INT             NULL,
    [TransmissionType]        VARCHAR (50)    NULL,
    [Drive]                   VARCHAR (50)    NULL,
    [ClutchType]              VARCHAR (50)    NULL,
    [FinalGearReductionRatio] FLOAT (53)      NULL,
    [SuspensionFront]         VARCHAR (200)   NULL,
    [SuspensionRear]          VARCHAR (200)   NULL,
    [BrakesType]              VARCHAR (200)   NULL,
    [BrakesFront]             VARCHAR (200)   NULL,
    [BrakesRear]              VARCHAR (200)   NULL,
    [WheelType]               VARCHAR (200)   NULL,
    [WheelSize]               VARCHAR (50)    NULL,
    [Tyres]                   VARCHAR (200)   NULL,
    [SteeringType]            VARCHAR (200)   NULL,
    [PowerAssisted]           VARCHAR (50)    NULL,
    [MinimumTurningRadius]    FLOAT (53)      NULL,
    [RearShoulder]            INT             NULL,
    [ZeroToHundred]           FLOAT (53)      NULL,
    [QuarterMile]             FLOAT (53)      NULL,
    [BrakingHundredToZero]    FLOAT (53)      NULL,
    [BrakingEightyToZero]     FLOAT (53)      NULL,
    [FrontWheelDiameter]      INT             NULL,
    [FrontTyreProfile]        INT             NULL,
    [FrontWheelSectionWidth]  INT             NULL,
    [RearWheelDiameter]       INT             NULL,
    [RearTyreProfile]         INT             NULL,
    [RearWheelSectionWidth]   INT             NULL,
    [Power_BHP]               DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_NewCarSpecificationSubCategories] PRIMARY KEY CLUSTERED ([CarVersionId] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [ix_NewCarSpecifications__FuelType]
    ON [dbo].[NewCarSpecifications]([FuelType] ASC)
    INCLUDE([CarVersionId], [SeatingCapacity], [MileageOverall], [Displacement], [Power], [Speeds], [TransmissionType]);

