CREATE TABLE [dbo].[NewCarInquiriesSummary] (
    [NewCarPurchaseInquiriesId] INT           NULL,
    [CustomerId]                INT           NULL,
    [CustomerName]              VARCHAR (100) NULL,
    [CustomerEmail]             VARCHAR (100) NULL,
    [CustomerMobile]            VARCHAR (20)  NULL,
    [CarMakeId]                 SMALLINT      NULL,
    [CarMakeName]               VARCHAR (50)  NULL,
    [CarModelId]                INT           NULL,
    [CarModelName]              VARCHAR (50)  NULL,
    [CarVersionId]              INT           NULL,
    [CarVersionName]            VARCHAR (50)  NULL,
    [Price]                     INT           NULL,
    [CustomerCityId]            SMALLINT      NULL,
    [CustomerCityName]          VARCHAR (50)  NULL,
    [CustomerStateId]           SMALLINT      NULL,
    [CustomerStateName]         VARCHAR (50)  NULL,
    [CarInquiryCityId]          SMALLINT      NULL,
    [CarInquiryCityName]        VARCHAR (50)  NULL,
    [CarInquiryStateId]         SMALLINT      NULL,
    [CarInquiryStateName]       VARCHAR (50)  NULL,
    [BuyTime]                   VARCHAR (50)  NULL,
    [CarFuelTypesId]            INT           NULL,
    [CarFuelType]               VARCHAR (50)  NULL,
    [CarBodyStylesId]           INT           NULL,
    [CarBodyStyle]              VARCHAR (50)  NULL,
    [CarSegmentsId]             INT           NULL,
    [CarSegment]                VARCHAR (50)  NULL,
    [CarSubSegmentsId]          INT           NULL,
    [CarSubSegment]             VARCHAR (50)  NULL,
    [RequestDateTime]           DATETIME      NULL,
    [RequestMonth]              AS            (datepart(month,[RequestDateTime])) PERSISTED,
    [RequestYear]               AS            (datepart(year,[RequestDateTime])) PERSISTED,
    [CarTransmissionId]         TINYINT       NULL,
    [CarTransmission]           VARCHAR (50)  NULL
);

