CREATE TABLE [dbo].[OLM_BookingData] (
    [Id]                  NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [CustomerName]        VARCHAR (50)   NOT NULL,
    [Mobile]              VARCHAR (15)   NOT NULL,
    [Email]               VARCHAR (50)   NOT NULL,
    [CityId]              INT            NOT NULL,
    [ModelId]             INT            NOT NULL,
    [Color]               VARCHAR (20)   NULL,
    [ColorCode]           VARCHAR (20)   NULL,
    [Price]               VARCHAR (15)   NULL,
    [VersionId]           INT            NULL,
    [VariantCode]         VARCHAR (20)   NULL,
    [EngineFuelTrans]     VARCHAR (20)   NULL,
    [TransmissionType]    SMALLINT       NULL,
    [EngineType]          VARCHAR (15)   NULL,
    [ShowroomId]          INT            NULL,
    [PaymentType]         SMALLINT       NULL,
    [OutletName]          VARCHAR (50)   NULL,
    [OutletCode]          VARCHAR (50)   NULL,
    [SkodaBookingId]      VARCHAR (50)   NULL,
    [IsPaymentSuccessful] BIT            NULL,
    [LeadTokenNo]         VARCHAR (50)   NULL,
    [TokenDateTime]       DATETIME       NULL,
    [PushSuccess]         BIT            NULL,
    [PushErrorMsg]        VARCHAR (2000) NULL,
    [BookingXMLSent]      VARCHAR (2000) NULL,
    [BookingXMLResult]    VARCHAR (2000) NULL,
    [DealerXMLSend]       VARCHAR (2000) NULL,
    [DealerXMLResult]     VARCHAR (2000) NULL,
    [IpAddress]           VARCHAR (20)   NULL,
    [EnrtyDate]           DATETIME       CONSTRAINT [DF_OLM_BookingData_EnrtyDate] DEFAULT (getdate()) NULL,
    [ChkAddress]          VARCHAR (1000) NULL,
    [ChkCity]             VARCHAR (50)   NULL,
    [ChkState]            VARCHAR (50)   NULL,
    [ChkPincode]          VARCHAR (10)   NULL,
    [FuelType]            SMALLINT       NULL,
    CONSTRAINT [PK_OLM_BookingData] PRIMARY KEY CLUSTERED ([Id] ASC)
);

