CREATE TABLE [dbo].[PQ_DealerSponsoredDailyLogs] (
    [AsOnDate]               DATE          NULL,
    [Id]                     INT           NULL,
    [ModelId]                INT           NULL,
    [CityId]                 INT           NULL,
    [DealerId]               INT           NOT NULL,
    [DealerName]             VARCHAR (80)  NOT NULL,
    [Phone]                  VARCHAR (50)  NOT NULL,
    [IsActive]               BIT           NOT NULL,
    [DealerEmailId]          VARCHAR (250) NULL,
    [StartDate]              DATE          NULL,
    [EndDate]                DATE          NULL,
    [ZoneId]                 INT           NULL,
    [UpdatedBy]              INT           NULL,
    [UpdatedOn]              DATETIME      NULL,
    [DealerLeadBusinessType] SMALLINT      NULL,
    [IsDesktop]              BIT           NOT NULL,
    [IsMobile]               BIT           NOT NULL,
    [IsAndroid]              BIT           NOT NULL,
    [IsIPhone]               BIT           NOT NULL,
    [Type]                   INT           NULL,
    [TotalGoal]              INT           NULL,
    [DailyGoal]              INT           NULL,
    [TotalCount]             INT           NULL,
    [DailyCount]             INT           NULL,
    [LeadPanel]              TINYINT       NULL,
    [EnableUserEmail]        BIT           NULL,
    [EnableUserSMS]          BIT           NULL,
    [CampaignPriority]       SMALLINT      NULL,
    [LinkText]               VARCHAR (250) NULL,
    [IsMailerSent]           BIT           NULL,
    [EnableDealerEmail]      BIT           NULL,
    [EnableDealerSMS]        BIT           NULL,
    [CostPerLead]            FLOAT (53)    NULL,
    [ShowEmail]              BIT           NULL,
    [PausedDate]             DATETIME      NULL
);

