CREATE TABLE [dbo].[RecommendCarSearchData] (
    [ID]                    NUMERIC (18)  IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CustomerId]            NUMERIC (18)  NULL,
    [StartPrice]            NUMERIC (18)  NULL,
    [EndPrice]              NUMERIC (18)  NULL,
    [CityKm]                NUMERIC (18)  NULL,
    [HighwayKm]             NUMERIC (18)  NULL,
    [FuelEconomy]           SMALLINT      NULL,
    [PreferredBrands]       VARCHAR (500) NULL,
    [AC]                    BIT           NULL,
    [PowerSteering]         BIT           NULL,
    [PowerWindows]          BIT           NULL,
    [CentralLocking]        BIT           NULL,
    [AutomaticTransmission] BIT           NULL,
    [ABS]                   BIT           NULL,
    [SeatingCapacity]       SMALLINT      NULL,
    [Petrol]                BIT           NULL,
    [Diesel]                BIT           NULL,
    [LPG]                   BIT           NULL,
    [MaintenanceCost]       SMALLINT      NULL,
    [PreferredSegments]     VARCHAR (200) NULL,
    [PreferredBodyStyles]   VARCHAR (200) NULL,
    [Tall]                  BIT           NULL,
    [RearSeat]              BIT           NULL,
    [WomenDriven]           BIT           NULL,
    [HighSpeed]             BIT           NULL,
    [EntryDateTime]         DATETIME      NOT NULL,
    [IPAdress]              VARCHAR (200) NULL,
    [NewCar]                BIT           NULL,
    [Safety]                SMALLINT      NULL,
    [Comfort]               SMALLINT      NULL,
    [Performance]           SMALLINT      NULL,
    [Resale]                SMALLINT      NULL,
    [VFM]                   SMALLINT      NULL,
    CONSTRAINT [PK_RecommendCarSearchData] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

