CREATE TABLE [dbo].[RecommendCar_FeaturesPrices] (
    [Id]                           NUMERIC (18) IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [AC]                           NUMERIC (18) NULL,
    [ACMax]                        NUMERIC (18) NULL,
    [PowerSteering]                NUMERIC (18) NULL,
    [PowerSteeringMax]             NUMERIC (18) NULL,
    [PowerWindows]                 NUMERIC (18) NULL,
    [PowerWindowsMax]              NUMERIC (18) NULL,
    [CentralLocking]               NUMERIC (18) NULL,
    [CentralLockingMax]            NUMERIC (18) NULL,
    [AutomaticTransmission]        NUMERIC (18) NULL,
    [AutomaticTransmissionMax]     NUMERIC (18) NULL,
    [ABSR]                         NUMERIC (18) NULL,
    [ABSRMax]                      NUMERIC (18) NULL,
    [ACUsed]                       NUMERIC (18) NULL,
    [ACUsedMax]                    NUMERIC (18) NULL,
    [PowerSteeringUsed]            NUMERIC (18) NULL,
    [PowerSteeringUsedMax]         NUMERIC (18) NULL,
    [PowerWindowsUsed]             NUMERIC (18) NULL,
    [PowerWindowsUsedMax]          NUMERIC (18) NULL,
    [CentralLockingUsed]           NUMERIC (18) NULL,
    [CentralLockingUsedMax]        NUMERIC (18) NULL,
    [AutomaticTransmissionUsed]    NUMERIC (18) NULL,
    [AutomaticTransmissionUsedMax] NUMERIC (18) NULL,
    [ABSRUsed]                     NUMERIC (18) NULL,
    [ABSRUsedMax]                  NUMERIC (18) NULL,
    CONSTRAINT [PK_RecommendCar_FeaturesPrices] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 90)
);

