CREATE TABLE [dbo].[RecommendCarData] (
    [MakeId]                 NUMERIC (18) CONSTRAINT [DF_RecommendCarData_MakeId] DEFAULT (0) NOT NULL,
    [ModelId]                NUMERIC (18) CONSTRAINT [DF_RecommendCarData_ModelId] DEFAULT (0) NOT NULL,
    [VersionId]              NUMERIC (18) NOT NULL,
    [CityR]                  SMALLINT     NOT NULL,
    [HighwayR]               SMALLINT     NOT NULL,
    [FuelEconomyR]           SMALLINT     NOT NULL,
    [ACR]                    SMALLINT     NOT NULL,
    [PowerSteeringR]         SMALLINT     NOT NULL,
    [PowerWindowsR]          SMALLINT     NOT NULL,
    [CentralLockingR]        SMALLINT     NOT NULL,
    [AutomaticTransmissionR] SMALLINT     NOT NULL,
    [ABSR]                   SMALLINT     NOT NULL,
    [SeatingCapacityA]       SMALLINT     NOT NULL,
    [SeatingCapacityR]       SMALLINT     NOT NULL,
    [FuelType]               SMALLINT     NOT NULL,
    [CarMaintenanceR]        SMALLINT     NOT NULL,
    [TallR]                  SMALLINT     NOT NULL,
    [RearSeatComfortR]       SMALLINT     NOT NULL,
    [WomenR]                 SMALLINT     NOT NULL,
    [HighSpeedR]             SMALLINT     NOT NULL,
    [ExpertsRatingR]         SMALLINT     NOT NULL,
    [SafetyR]                SMALLINT     CONSTRAINT [DF_RecommendCarData_SafetyR] DEFAULT (0) NOT NULL,
    [PerformanceR]           SMALLINT     CONSTRAINT [DF_RecommendCarData_PerformanceR] DEFAULT (0) NOT NULL,
    [ComfortR]               SMALLINT     CONSTRAINT [DF_RecommendCarData_ComfortR] DEFAULT (0) NOT NULL,
    [ResaleR]                SMALLINT     CONSTRAINT [DF_RecommendCarData_ResaleR] DEFAULT (0) NOT NULL,
    [VFMR]                   SMALLINT     CONSTRAINT [DF_RecommendCarData_VFMR] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_RecommendCarData] PRIMARY KEY CLUSTERED ([VersionId] ASC) WITH (FILLFACTOR = 90)
);

