CREATE TABLE [dbo].[RVN_DealerPackageFeaturesBkp041214] (
    [DealerPackageFeatureID] INT             IDENTITY (1, 1) NOT NULL,
    [DealerId]               INT             NULL,
    [PackageId]              INT             NULL,
    [EntryDate]              DATETIME        NULL,
    [AmountPaid]             BIGINT          NULL,
    [LeadCount]              INT             NULL,
    [DeliveryCount]          INT             NULL,
    [PackageStartDate]       DATETIME        NULL,
    [PackageEndDate]         DATETIME        NULL,
    [IsActive]               BIT             NULL,
    [LeadType]               TINYINT         NULL,
    [PackageStatus]          TINYINT         NULL,
    [OprUserId]              SMALLINT        NULL,
    [SalesDealerId]          INT             NULL,
    [ModelId]                SMALLINT        NULL,
    [PackageStatusDate]      DATETIME        NULL,
    [IsReminderSent]         BIT             NULL,
    [ReminderDate]           DATETIME        NULL,
    [MakeId]                 SMALLINT        NULL,
    [AttachedFileExtension]  VARCHAR (50)    NULL,
    [Comments]               VARCHAR (1000)  NULL,
    [HostURL]                VARCHAR (100)   NULL,
    [ClosingAmount]          INT             NULL,
    [PaymentMode]            TINYINT         NULL,
    [DiscountAmount]         INT             NULL,
    [ProductAmount]          INT             NULL,
    [ServiceTax]             FLOAT (53)      NULL,
    [IsTDSGiven]             BIT             NULL,
    [TDSAmount]              DECIMAL (18, 2) NULL,
    [UpdatedBy]              INT             NULL,
    [UpdatedOn]              DATETIME        NULL,
    [ApprovedBy]             INT             NULL,
    [PANNumber]              VARCHAR (10)    NULL,
    [TANNumber]              VARCHAR (10)    NULL,
    [PackageQuantity]        INT             NULL,
    [IsRenew]                BIT             NULL,
    [RenewDate]              DATETIME        NULL,
    [ApprovedOn]             DATETIME        NULL,
    [RenewSalesDealerId]     NUMERIC (18)    NULL,
    [ProductSalesDealerId]   NUMERIC (18)    NULL,
    [SuspendedBy]            INT             NULL
);

