CREATE TABLE [dbo].[SalesExecutives] (
    [ID]   NUMERIC (18)  IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Name] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_SalesExecutives] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

