CREATE TABLE [dbo].[SkodaRapidBooking] (
    [ID]                  INT            IDENTITY (1, 1) NOT NULL,
    [CustomerName]        VARCHAR (100)  NOT NULL,
    [Mobile]              VARCHAR (20)   NOT NULL,
    [CityID]              INT            NOT NULL,
    [Email]               VARCHAR (250)  NOT NULL,
    [EntryDate]           DATETIME       CONSTRAINT [DF_SkodaRapidBooking_EntryDate] DEFAULT (getdate()) NOT NULL,
    [Engine]              VARCHAR (50)   NULL,
    [Transmission]        VARCHAR (50)   NULL,
    [Colour]              VARCHAR (50)   NULL,
    [ColourCode]          VARCHAR (50)   NULL,
    [VersionName]         VARCHAR (50)   NULL,
    [VersionCode]         VARCHAR (50)   NULL,
    [DealerID]            INT            NULL,
    [EstimatedDelivery]   DATETIME       NULL,
    [BookingAmount]       VARCHAR (10)   NULL,
    [ExShowroomPrice]     VARCHAR (10)   NULL,
    [DeliveryPoint]       VARCHAR (50)   NULL,
    [DeliveryLocation]    VARCHAR (500)  NULL,
    [SkodaBookingId]      VARCHAR (50)   NULL,
    [DeliveryLocation2]   VARCHAR (500)  NULL,
    [DealerCode]          VARCHAR (50)   NULL,
    [OutletCode]          VARCHAR (50)   NULL,
    [OutletName]          VARCHAR (50)   NULL,
    [IsPaymentSuccessful] BIT            NULL,
    [TokenDateTime]       DATETIME       NULL,
    [PushSuccess]         BIT            NULL,
    [PushErrorMsg]        VARCHAR (2000) NULL,
    [LeadTokenNo]         VARCHAR (50)   NULL,
    [BookingXMLSent]      VARCHAR (MAX)  NULL,
    [BookingXMLResult]    VARCHAR (MAX)  NULL,
    [DealerXMLSend]       VARCHAR (MAX)  NULL,
    [DealerXMLResult]     VARCHAR (MAX)  NULL,
    CONSTRAINT [PK_SkodaRapidBooking] PRIMARY KEY CLUSTERED ([ID] ASC)
);

