CREATE TABLE [dbo].[SponsoredCampaigns] (
    [Id]                 NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [ModelId]            NUMERIC (18)  NULL,
    [AdScript]           VARCHAR (MAX) NULL,
    [IsActive]           BIT           NULL,
    [CampaignCategoryId] TINYINT       NULL,
    [IsDeleted]          BIT           CONSTRAINT [DF_SponsoredCampaigns_IsDeleted] DEFAULT ((0)) NULL,
    [StartDate]          DATETIME      NULL,
    [EndDate]            DATETIME      NULL,
    [SponsoredTitle]     VARCHAR (200) NULL,
    [IsSponsored]        BIT           DEFAULT ((0)) NULL,
    [IsDefault]          BIT           CONSTRAINT [DF_SponsoredCampaigns_IsDefault] DEFAULT ((0)) NULL,
    [PlatformId]         INT           NULL,
    [CreatedBy]          INT           NULL,
    [CreatedOn]          DATETIME      CONSTRAINT [DF_SponsoredCampaigns_CreatedOn] DEFAULT (getdate()) NULL,
    [UpdatedBy]          INT           NULL,
    [UpdatedOn]          DATETIME      NULL,
    [ImageUrl]           VARCHAR (300) NULL,
    [JumbotronPos]       SMALLINT      NULL,
    [VPosition]          VARCHAR (10)  NULL,
    [HPosition]          VARCHAR (10)  NULL,
    [BackGroundColor]    VARCHAR (10)  NULL,
    [CategorySection]    SMALLINT      NULL,
    [MakeId]             INT           NULL,
    [Subtitle]           VARCHAR (200) NULL,
    [CardHeader]         VARCHAR (200) NULL,
    [POSITION]           VARCHAR (200) NULL
);

