CREATE TABLE [dbo].[TC_CarTradeCertificationData] (
    [TC_CarTradeCertificationDataId] INT           IDENTITY (1, 1) NOT NULL,
    [ListingId]                      INT           NULL,
    [Id]                             INT           NULL,
    [State]                          VARCHAR (50)  NULL,
    [City]                           VARCHAR (50)  NULL,
    [Area]                           VARCHAR (40)  NULL,
    [Type]                           VARCHAR (15)  NULL,
    [Make]                           VARCHAR (25)  NULL,
    [Model]                          VARCHAR (25)  NULL,
    [Variant]                        VARCHAR (100) NULL,
    [Color]                          VARCHAR (25)  NULL,
    [PowerSteering]                  VARCHAR (5)   NULL,
    [Fuel]                           VARCHAR (25)  NULL,
    [FuelEndors]                     CHAR (15)     NULL,
    [Shape]                          VARCHAR (10)  NULL,
    [Mileage]                        INT           NULL,
    [MfgMonth]                       INT           NULL,
    [MfgYear]                        INT           NULL,
    [Owner]                          VARCHAR (15)  NULL,
    [RegType]                        VARCHAR (25)  NULL,
    [RegDate]                        VARCHAR (25)  NULL,
    [RegNum]                         VARCHAR (15)  NULL,
    [RegCity]                        VARCHAR (25)  NULL,
    [LastRegDate]                    VARCHAR (25)  NULL,
    [Octroi]                         CHAR (5)      NULL,
    [RtoTaxDate]                     VARCHAR (25)  NULL,
    [Insurance]                      VARCHAR (25)  NULL,
    [InsExp]                         VARCHAR (25)  NULL,
    [ClaimBonus]                     CHAR (5)      NULL,
    [ClaimPercent]                   INT           NULL,
    [IdvValue]                       INT           NULL,
    [Hypo]                           CHAR (5)      NULL,
    [BankName]                       VARCHAR (25)  NULL,
    [LoanOff]                        CHAR (5)      NULL,
    [Noc]                            CHAR (5)      NULL,
    [ListRemarks]                    TEXT          NULL,
    [WheelFrontLeft]                 INT           NULL,
    [WheelFrontRight]                INT           NULL,
    [WheelBackLeft]                  INT           NULL,
    [WheelBackRight]                 INT           NULL,
    [WheelSt]                        INT           NULL,
    [RefurbCostExp]                  INT           NULL,
    [RefurbCostAct]                  INT           NULL,
    [InvCertifiedDate]               DATETIME      NULL,
    [VRemark]                        VARCHAR (250) NULL,
    [Transmission]                   VARCHAR (50)  NULL,
    [DamageImage]                    VARCHAR (200) NULL,
    [IsWarranty]                     BIT           NULL,
    [CertificateLink]                VARCHAR (250) NULL,
    CONSTRAINT [PK_TC_CarTradeCertificationData] PRIMARY KEY CLUSTERED ([TC_CarTradeCertificationDataId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_TC_CarTradeCertificationData_ListingId]
    ON [dbo].[TC_CarTradeCertificationData]([ListingId] ASC);

