CREATE TABLE [dbo].[TC_CustomerDetailsChangesLog] (
    [Id]                          INT           IDENTITY (1, 1) NOT NULL,
    [CustomerId]                  BIGINT        NULL,
    [OLdLostReasonId]             INT           NULL,
    [LostReasonId]                INT           NULL,
    [OldCustomerName]             VARCHAR (100) NULL,
    [CustomerName]                VARCHAR (100) NULL,
    [OldCustomerEmail]            VARCHAR (50)  NULL,
    [CustomerEmail]               VARCHAR (50)  NULL,
    [OldCustomerMobile]           VARCHAR (12)  NULL,
    [CustomerMobile]              VARCHAR (12)  NULL,
    [OldLastName]                 VARCHAR (50)  NULL,
    [LastName]                    VARCHAR (50)  NULL,
    [OldSalutation]               VARCHAR (10)  NULL,
    [Salutation]                  VARCHAR (10)  NULL,
    [OldAddress]                  VARCHAR (200) NULL,
    [Address]                     VARCHAR (200) NULL,
    [OldCustomerCity]             INT           NULL,
    [CustomerCity]                INT           NULL,
    [OldInquirySourceId]          INT           NULL,
    [InquirySourceId]             INT           NULL,
    [OldCarModelId]               INT           NULL,
    [CarModelId]                  INT           NULL,
    [OldCarVersionId]             INT           NULL,
    [CarVersionId]                INT           NULL,
    [OldTestDriveDate]            DATETIME      NULL,
    [TestDriveDate]               DATETIME      NULL,
    [OldBookingDate]              DATETIME      NULL,
    [BookingDate]                 DATETIME      NULL,
    [OldBookingCancelDate]        DATETIME      NULL,
    [BookingCancelDate]           DATETIME      NULL,
    [OldCarDeliveryDate]          DATETIME      NULL,
    [CarDeliveryDate]             DATETIME      NULL,
    [OldRetailDate]               DATETIME      NULL,
    [RetailDate]                  DATETIME      NULL,
    [OldLostDate]                 DATETIME      NULL,
    [LostDate]                    DATETIME      NULL,
    [OldBookingAmount]            INT           NULL,
    [BookingAmount]               INT           NULL,
    [OldEngionNumber]             VARCHAR (50)  NULL,
    [EngionNumber]                VARCHAR (50)  NULL,
    [OldInsuranceCoverNo]         VARCHAR (50)  NULL,
    [InsuranceCoverNo]            VARCHAR (50)  NULL,
    [OldInvoiceNo]                VARCHAR (50)  NULL,
    [InvoiceNo]                   VARCHAR (50)  NULL,
    [OldModelCode]                INT           NULL,
    [ModelCode]                   INT           NULL,
    [OldRegistrationNo]           VARCHAR (50)  NULL,
    [RegistrationNo]              VARCHAR (50)  NULL,
    [OldPanNo]                    VARCHAR (50)  NULL,
    [PanNo]                       VARCHAR (50)  NULL,
    [OldVinNo]                    VARCHAR (50)  NULL,
    [VinNo]                       VARCHAR (50)  NULL,
    [OldRetailCustomerName]       VARCHAR (20)  NULL,
    [RetailCustomerName]          VARCHAR (20)  NULL,
    [OldRetailCustomerMobile]     VARCHAR (15)  NULL,
    [RetailCustomerMobile]        VARCHAR (15)  NULL,
    [OldRetailCustomerEmail]      VARCHAR (50)  NULL,
    [RetailCustomerEmail]         VARCHAR (50)  NULL,
    [OldLostReason]               VARCHAR (50)  NULL,
    [LostReason]                  VARCHAR (50)  NULL,
    [OldLostToMake]               INT           NULL,
    [LostToMake]                  INT           NULL,
    [OldLostToModel]              INT           NULL,
    [LostToModel]                 INT           NULL,
    [OldLostToVersion]            INT           NULL,
    [LostToVersion]               INT           NULL,
    [OldLostSubDisposition]       INT           NULL,
    [LostSubDisposition]          INT           NULL,
    [OldModelColorCode]           INT           NULL,
    [ModelColorCode]              INT           NULL,
    [OldModelYear]                VARCHAR (10)  NULL,
    [ModelYear]                   VARCHAR (10)  NULL,
    [OldExchangeCarMake]          INT           NULL,
    [ExchangeCarMake]             INT           NULL,
    [OldExchangeCarModel]         INT           NULL,
    [ExchangeCarModel]            INT           NULL,
    [OldExchangeCarVersion]       INT           NULL,
    [ExchangeCarVersion]          INT           NULL,
    [OldExchangeCarYear]          VARCHAR (20)  NULL,
    [ExchangeCarYear]             VARCHAR (20)  NULL,
    [OldExchangeCarKMDriven]      VARCHAR (20)  NULL,
    [ExchangeCarKMDriven]         VARCHAR (20)  NULL,
    [OldExchangeCarExpectedPrice] VARCHAR (50)  NULL,
    [ExchangeCarExpectedPrice]    VARCHAR (50)  NULL,
    [OldUserId]                   INT           NULL,
    [UserId]                      INT           NULL,
    [OldCompanyName]              VARCHAR (200) NULL,
    [CompanyName]                 VARCHAR (200) NULL,
    [OldInquiryDate]              DATETIME      NULL,
    [InquiryDate]                 DATETIME      NULL,
    [ModifiedDate]                DATETIME      NULL,
    [ModifiedBy]                  INT           NULL
);

