CREATE TABLE [dbo].[TC_CarCondition] (
    [StockId]                  NUMERIC (18)  NOT NULL,
    [Owners]                   VARCHAR (50)  NULL,
    [RegistrationPlace]        VARCHAR (50)  NULL,
    [OneTimeTax]               VARCHAR (50)  NULL,
    [Insurance]                VARCHAR (50)  NULL,
    [InsuranceExpiry]          DATETIME      NULL,
    [LastUpdatedDate]          DATETIME      NULL,
    [InteriorColor]            VARCHAR (50)  NULL,
    [InteriorColorCode]        VARCHAR (6)   NULL,
    [CityMileage]              VARCHAR (50)  NULL,
    [AdditionalFuel]           VARCHAR (50)  NULL,
    [CarDriven]                VARCHAR (50)  NULL,
    [Accidental]               BIT           CONSTRAINT [DF_TC_CarCondition_Accidental] DEFAULT ((0)) NOT NULL,
    [FloodAffected]            BIT           CONSTRAINT [DF_TC_CarCondition_FloodAffected] DEFAULT ((0)) NOT NULL,
    [Warranties]               VARCHAR (500) NULL,
    [Modifications]            VARCHAR (500) NULL,
    [Comments]                 VARCHAR (500) NULL,
    [ACCondition]              VARCHAR (50)  NULL,
    [BatteryCondition]         VARCHAR (50)  NULL,
    [BrakesCondition]          VARCHAR (50)  NULL,
    [ElectricalsCondition]     VARCHAR (50)  NULL,
    [EngineCondition]          VARCHAR (50)  NULL,
    [ExteriorCondition]        VARCHAR (50)  NULL,
    [InteriorCondition]        VARCHAR (50)  NULL,
    [SeatsCondition]           VARCHAR (50)  NULL,
    [SuspensionsCondition]     VARCHAR (50)  NULL,
    [TyresCondition]           VARCHAR (50)  NULL,
    [OverallCondition]         VARCHAR (50)  NULL,
    [Features_SafetySecurity]  VARCHAR (200) NULL,
    [Features_Comfort]         VARCHAR (200) NULL,
    [Features_Others]          VARCHAR (200) NULL,
    [EntryDate]                DATETIME      DEFAULT (getdate()) NULL,
    [ModifiedBy]               INT           NULL,
    [MissingInstalledFeatures] VARCHAR (500) NULL,
    CONSTRAINT [FK_StockID] FOREIGN KEY ([StockId]) REFERENCES [dbo].[TC_Stock] ([Id]) ON UPDATE CASCADE,
    CONSTRAINT [UK_TC_CarCondition_StockId] UNIQUE NONCLUSTERED ([StockId] ASC)
);

