export const NEXT_FILTER = 'NEXT_FILTER'
export const SET_CURRENT_SCREEN = 'SET_CURRENT_SCREEN'
export const SET_ALL_FILTER_SCREEN = 'SET_ALL_FILTER_SCREEN'

export const REQUEST_CAR_FEATURE = 'REQUEST_CAR_FEATURE'
export const RECEIVE_CAR_FEATURE = 'RECEIVE_CAR_FEATURE'
export const CAR_FEATURE_SELECTION = 'CAR_FEATURE_SELECTION'

// budget
export const UPDATE_BUDGET_SLIDER_VALUE = 'UPDATE_BUDGET_SLIDER_VALUE'
export const UPDATE_BUDGET_INPUT_VALUE = 'UPDATE_BUDGET_INPUT_VALUE'

// body type
export const REQUEST_BODY_TYPE = 'REQUEST_BODY_TYPE'
export const RECEIVE_BODY_TYPE = 'RECEIVE_BODY_TYPE'
export const BODY_TYPE_SELECTION = 'BODY_TYPE_SELECTION'
export const SET_BODY_STORED_FILTERS = 'SET_BODY_STORED_FILTERS'


// fuel type
export const REQUEST_FUEL_TYPE = 'REQUEST_FUEL_TYPE'
export const RECEIVE_FUEL_TYPE = 'RECEIVE_FUEL_TYPE'
export const FUEL_TYPE_SELECTION = 'FUEL_TYPE_SELECTION'
export const SET_FUEL_STORED_FILTERS = 'SET_FUEL_STORED_FILTERS'

// fuel type
export const REQUEST_MAKE = 'REQUEST_MAKE'
export const RECEIVE_MAKE = 'RECEIVE_MAKE'
export const MAKE_SELECTION = 'MAKE_SELECTION'
export const SET_MAKE_STORED_FILTERS = 'SET_MAKE_STORED_FILTERS'



// listing
// model list RECEIVE_MODEL_LIST
export const REQUEST_MODEL_LIST = 'REQUEST_MODEL_LIST'
export const RECEIVE_MODEL_LIST = 'RECEIVE_MODEL_LIST'
export const APPEND_MODEL_LIST = 'APPEND_MODEL_LIST'

// filter screen
export const OPEN_FILTER_SCREEN = 'OPEN_FILTER_SCREEN'
export const CLOSE_FILTER_SCREEN = 'CLOSE_FILTER_SCREEN'

// compare cars
export const ADD_MODEL_TO_COMPARE = 'ADD_MODEL_TO_COMPARE'
export const REMOVE_MODEL_FROM_COMPARE = 'REMOVE_MODEL_FROM_COMPARE'
// header
export const MAKE_HEADER_STICKY = 'MAKE_HEADER_STICKY'
export const MAKE_HEADER_NORMAL = 'MAKE_HEADER_NORMAL'
