export const HIDE_SHORTLIST_POPUP = 'HIDE_SHORTLIST_POPUP'
export const SHOW_SHORTLIST_POPUP = 'SHOW_SHORTLIST_POPUP'
export const ADD_MODEL_TO_SHORTLIST = 'ADD_MODEL_TO_SHORTLIST'
export const REMOVE_MODEL_FROM_SHORTLIST = 'REMOVE_MODEL_FROM_SHORTLIST'
export const BLACKLIST_CAR = 'BLACKLIST_CAR'
export const RESET_SHORTLIST_CARS = 'RESET_SHORTLIST_CARS'

export const SHOW_SHORTLIST_ICON = 'SHOW_SHORTLIST_ICON'
export const HIDE_SHORTLIST_ICON = 'HIDE_SHORTLIST_ICON'

