CREATE TABLE [dba].[DealerStockPerformance] (
    [DealerId]        NUMERIC (18)  NOT NULL,
    [Inquiryid]       NUMERIC (18)  NULL,
    [MakeId]          NUMERIC (18)  NULL,
    [MakeName]        VARCHAR (100) NULL,
    [ModelId]         NUMERIC (18)  NULL,
    [ModelName]       VARCHAR (100) NULL,
    [VersionId]       NUMERIC (18)  NULL,
    [VersionName]     VARCHAR (100) NULL,
    [CityId]          NUMERIC (18)  NULL,
    [CityName]        VARCHAR (100) NULL,
    [MakeYear]        DATETIME      NULL,
    [Price]           NUMERIC (18)  NULL,
    [PhotoCount]      SMALLINT      NOT NULL,
    [Kilometers]      NUMERIC (18)  NULL,
    [InquiryAdded]    DATETIME      NULL,
    [AdditionalFuel]  VARCHAR (50)  NULL,
    [Owners]          VARCHAR (50)  NULL,
    [Insurance]       VARCHAR (50)  NULL,
    [InsuranceExpiry] DATETIME      NULL,
    [CertificationId] SMALLINT      NULL,
    [CarFuelType]     TINYINT       NULL,
    [OneTimeTax]      VARCHAR (50)  NULL,
    [Warranties]      VARCHAR (500) NULL,
    [Response]        INT           NULL,
    [CarAge]          INT           NULL,
    [CreatedOn]       DATETIME      CONSTRAINT [DF_DealerStockPerformance_CreatedOn] DEFAULT (getdate()) NULL
);

