CREATE TABLE [dba].[ProcLog] (
    [AsOnDate]             DATETIME     NULL,
    [dbname]               VARCHAR (50) NULL,
    [schemaName]           VARCHAR (50) NULL,
    [Procname]             VARCHAR (50) NULL,
    [CreateDate]           DATETIME     NULL,
    [ModifiedDate]         DATETIME     NULL,
    [cached_time]          DATETIME     NULL,
    [last_execution_time]  DATETIME     NULL,
    [execution_count]      BIGINT       NULL,
    [total_worker_time]    BIGINT       NULL,
    [last_worker_time]     BIGINT       NULL,
    [min_worker_time]      BIGINT       NULL,
    [max_worker_time]      BIGINT       NULL,
    [total_physical_reads] BIGINT       NULL,
    [last_physical_reads]  BIGINT       NULL,
    [min_physical_reads]   BIGINT       NULL,
    [max_physical_reads]   BIGINT       NULL,
    [total_logical_writes] BIGINT       NULL,
    [last_logical_writes]  BIGINT       NULL,
    [min_logical_writes]   BIGINT       NULL,
    [max_logical_writes]   BIGINT       NULL,
    [total_logical_reads]  BIGINT       NULL,
    [last_logical_reads]   BIGINT       NULL,
    [min_logical_reads]    BIGINT       NULL,
    [max_logical_reads]    BIGINT       NULL,
    [total_elapsed_time]   BIGINT       NULL,
    [last_elapsed_time]    BIGINT       NULL,
    [min_elapsed_time]     BIGINT       NULL,
    [max_elapsed_time]     BIGINT       NULL
);

