CREATE TABLE [dba].[sysProcessesLogs] (
    [AsOnDate]     DATETIME       NULL,
    [spid]         SMALLINT       NULL,
    [kpid]         SMALLINT       NULL,
    [blocked]      SMALLINT       NULL,
    [waittype]     BINARY (2)     NULL,
    [waittime]     BIGINT         NULL,
    [lastwaittype] NVARCHAR (32)  NULL,
    [waitresource] NVARCHAR (256) NULL,
    [dbid]         SMALLINT       NULL,
    [uid]          SMALLINT       NULL,
    [cpu]          INT            NULL,
    [physical_io]  BIGINT         NULL,
    [memusage]     INT            NULL,
    [login_time]   DATETIME       NULL,
    [last_batch]   DATETIME       NULL,
    [ecid]         SMALLINT       NULL,
    [open_tran]    SMALLINT       NULL,
    [status]       NVARCHAR (30)  NULL,
    [sid]          BINARY (86)    NULL,
    [hostname]     NVARCHAR (128) NULL,
    [program_name] NVARCHAR (128) NULL,
    [hostprocess]  NVARCHAR (10)  NULL,
    [cmd]          NCHAR (16)     NULL,
    [nt_domain]    NCHAR (128)    NULL,
    [nt_username]  NCHAR (128)    NULL,
    [net_address]  NCHAR (12)     NULL,
    [net_library]  NCHAR (12)     NULL,
    [loginame]     NCHAR (128)    NULL,
    [context_info] BINARY (128)   NULL,
    [sql_handle]   BINARY (20)    NULL,
    [stmt_start]   INT            NULL,
    [stmt_end]     INT            NULL,
    [request_id]   INT            NULL
);

