CREATE TABLE [dbo].[AA_ActiveDealer] (
    [DealerId]            FLOAT (53)     NULL,
    [Camp#]               FLOAT (53)     NULL,
    [AutoBiz]             BIT            NULL,
    [Organization]        NVARCHAR (255) NULL,
    [FirstName]           NVARCHAR (255) NULL,
    [IsActive]            BIT            NULL,
    [Orig Dealer]         NVARCHAR (255) NULL,
    [EmailId]             NVARCHAR (255) NULL,
    [Address1]            NVARCHAR (255) NULL,
    [CityId]              FLOAT (53)     NULL,
    [CityName]            NVARCHAR (255) NULL,
    [MakeName]            NVARCHAR (255) NULL,
    [StateName]           NVARCHAR (255) NULL,
    [Pincode]             NVARCHAR (255) NULL,
    [PhoneNo]             NVARCHAR (255) NULL,
    [FaxNo]               NVARCHAR (255) NULL,
    [MobileNo]            NVARCHAR (255) NULL,
    [WebsiteUrl]          NVARCHAR (255) NULL,
    [ContactPerson]       NVARCHAR (255) NULL,
    [OwnerMobile]         NVARCHAR (255) NULL,
    [AreaName]            NVARCHAR (255) NULL,
    [ShowroomStartTime]   NVARCHAR (255) NULL,
    [ShowroomEndTime]     NVARCHAR (255) NULL,
    [Lattitude]           FLOAT (53)     NULL,
    [Longitude]           FLOAT (53)     NULL,
    [DealerLocatorActive] FLOAT (53)     NULL,
    [AAA]                 NVARCHAR (255) NULL
);

