CREATE TABLE [dbo].[AbSure_WarrantyActivationPending] (
    [AbSure_WarrantyActivationPendingId]  INT           IDENTITY (1, 1) NOT NULL,
    [AbSure_CarDetailsId]                 INT           NOT NULL,
    [CustName]                            VARCHAR (150) NULL,
    [Address]                             VARCHAR (500) NULL,
    [Mobile]                              VARCHAR (20)  NULL,
    [AlternatePhone]                      VARCHAR (20)  NULL,
    [Email]                               VARCHAR (50)  NULL,
    [Model]                               VARCHAR (100) NULL,
    [MakeYear]                            DATETIME      NULL,
    [RegNumber]                           VARCHAR (50)  NULL,
    [RegistrationDate]                    DATETIME      NULL,
    [Kilometer]                           INT           NULL,
    [WarrantyStartDate]                   DATETIME      NULL,
    [WarrantyEndDate]                     DATETIME      NULL,
    [DealerId]                            INT           NULL,
    [UserId]                              INT           NULL,
    [EntryDate]                           DATETIME      NULL,
    [WarrantyTypeId]                      INT           NULL,
    [EngineNo]                            VARCHAR (50)  NULL,
    [ChassisNo]                           VARCHAR (50)  NULL,
    [IsActivated]                         BIT           NULL,
    [ActivationDate]                      DATETIME      NULL,
    [TC_ActionApplicationId]              INT           NULL,
    [ActivatedBy]                         INT           NULL,
    [OriginalStockId]                     BIGINT        NULL,
    [IsActive]                            BIT           NULL,
    [Absure_WarrantyActivationStatusesId] INT           NULL,
    [DuplicateCarId]                      BIGINT        NULL,
    [IsCarTradeWarranty]                  BIT           NULL,
    CONSTRAINT [PK_AbSWarrantyActiPending] PRIMARY KEY CLUSTERED ([AbSure_WarrantyActivationPendingId] ASC)
);

