CREATE TABLE [dbo].[AbSure_ActivatedWarranty] (
    [AbSure_ActivatedWarrantyId] INT           IDENTITY (1, 1) NOT NULL,
    [AbSure_CarDetailsId]        INT           NOT NULL,
    [CustName]                   VARCHAR (150) NULL,
    [Address]                    VARCHAR (500) NULL,
    [Mobile]                     VARCHAR (20)  NULL,
    [AlternatePhone]             VARCHAR (20)  NULL,
    [Email]                      VARCHAR (50)  NULL,
    [Model]                      VARCHAR (100) NULL,
    [MakeYear]                   DATETIME      NULL,
    [RegNumber]                  VARCHAR (50)  NULL,
    [RegistrationDate]           DATETIME      NULL,
    [Kilometer]                  INT           NULL,
    [WarrantyStartDate]          DATETIME      NULL,
    [WarrantyEndDate]            DATETIME      NULL,
    [DealerId]                   INT           NULL,
    [UserId]                     INT           NULL,
    [EntryDate]                  DATETIME      DEFAULT (getdate()) NULL,
    [WarrantyTypeId]             INT           NULL,
    [EngineNo]                   VARCHAR (50)  NULL,
    [ChassisNo]                  VARCHAR (50)  NULL,
    [IsActivated]                BIT           NULL,
    [ActivationDate]             DATETIME      NULL,
    [TC_ActionApplicationId]     INT           NULL,
    [ActivatedBy]                INT           NULL,
    [OriginalStockId]            BIGINT        NULL,
    [DuplicateCarId]             BIGINT        NULL,
    [IsCarTradeWarranty]         BIT           NULL,
    CONSTRAINT [PK_AbSure_ActivatedWarranty] PRIMARY KEY CLUSTERED ([AbSure_ActivatedWarrantyId] ASC)
);

