CREATE TABLE [dbo].[AdClients] (
    [Id]       NUMERIC (18) IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Name]     VARCHAR (50) NOT NULL,
    [isActive] BIT          CONSTRAINT [DF_AdClients_isActive] DEFAULT (1) NOT NULL,
    CONSTRAINT [PK_AdClients] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 90)
);

