CREATE TABLE [dbo].[AE_Auctioner] (
    [Id]   NUMERIC (18)  IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Name] VARCHAR (100) NOT NULL,
    [Type] SMALLINT      NOT NULL,
    CONSTRAINT [PK_AE_Auctioner] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 90)
);

