CREATE TABLE [dbo].[AE_CarDetails] (
    [CarId]               NUMERIC (18)   IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [AERefNumber]         VARCHAR (50)   NULL,
    [VersionId]           NUMERIC (18)   NOT NULL,
    [CarType]             SMALLINT       NULL,
    [SaleType]            SMALLINT       NULL,
    [YardId]              INT            NULL,
    [AuctionerId]         INT            NULL,
    [TBoard]              BIT            CONSTRAINT [DF_AE_CarDetails_TBoard] DEFAULT ((0)) NULL,
    [MakeYear]            DATETIME       NULL,
    [Kms]                 VARCHAR (50)   NULL,
    [BasePrice]           NUMERIC (18)   NULL,
    [ValuationPrice]      NUMERIC (18)   NULL,
    [ReservePrice]        NUMERIC (18)   NULL,
    [Color]               VARCHAR (50)   NULL,
    [RegistrationNumber]  VARCHAR (50)   NULL,
    [RegistrationPlace]   VARCHAR (50)   NULL,
    [ChasisNo]            VARCHAR (100)  NULL,
    [EngineNo]            VARCHAR (100)  NULL,
    [Owners]              INT            NULL,
    [DocumentsAvailable]  BIT            CONSTRAINT [DF_AE_CarDetails_DocumentsAvailable] DEFAULT ((0)) NULL,
    [StatusId]            SMALLINT       NULL,
    [Grade]               SMALLINT       NULL,
    [Comments]            VARCHAR (1000) NULL,
    [InsuranceType]       VARCHAR (50)   NULL,
    [InsuranceExpiryDate] DATETIME       NULL,
    [FuelType]            SMALLINT       NULL,
    [TransmissionType]    SMALLINT       NULL,
    [PhotoAvailable]      BIT            CONSTRAINT [DF_AE_CarDetails_PhotoAvailable] DEFAULT ((0)) NULL,
    [VideoAvailable]      BIT            CONSTRAINT [DF_AE_CarDetails_VideoAvailable] DEFAULT ((0)) NULL,
    [RepoDate]            DATETIME       NULL,
    [CreatedOn]           DATETIME       CONSTRAINT [DF_AE_CarDetails_CreatedOn] DEFAULT (getdate()) NULL,
    [UpdatedOn]           DATETIME       NULL,
    [UpdatedBy]           NUMERIC (18)   NULL,
    CONSTRAINT [PK_AE_CarDetails] PRIMARY KEY CLUSTERED ([CarId] ASC) WITH (FILLFACTOR = 90)
);

