CREATE TABLE [dbo].[AW_Year] (
    [Id]        INT IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [AwardYear] INT NULL,
    CONSTRAINT [PK_AW_Year] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 90)
);

