CREATE TABLE [dbo].[Budgets] (
    [ID]     NUMERIC (18) IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Budget] NUMERIC (18) NOT NULL,
    CONSTRAINT [PK_Budgets] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

