CREATE TABLE [dbo].[Cancellled_AbSure_CarDetails] (
    [Id]                     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [Make]                   VARCHAR (100)  NULL,
    [Model]                  VARCHAR (100)  NULL,
    [Version]                VARCHAR (100)  NULL,
    [VersionId]              INT            NULL,
    [VIN]                    VARCHAR (50)   NULL,
    [RegNumber]              VARCHAR (50)   NULL,
    [EntryDate]              DATETIME       NULL,
    [Source]                 SMALLINT       NULL,
    [DealerId]               BIGINT         NULL,
    [StockId]                BIGINT         NULL,
    [MakeYear]               DATETIME       NULL,
    [Kilometer]              INT            NULL,
    [Owners]                 VARCHAR (50)   NULL,
    [Colour]                 VARCHAR (50)   NULL,
    [Insurance]              VARCHAR (50)   NULL,
    [InsuranceExpiry]        DATETIME       NULL,
    [IsOrigionalRC]          BIT            NULL,
    [IsBankHypothecation]    BIT            NULL,
    [RegisteredAt]           VARCHAR (50)   NULL,
    [AvailableAt]            VARCHAR (50)   NULL,
    [FuelType]               SMALLINT       NULL,
    [Transmission]           SMALLINT       NULL,
    [RegistrationDate]       DATETIME       NULL,
    [RegistrationType]       SMALLINT       NULL,
    [IsRejected]             BIT            NULL,
    [IsSurveyDone]           BIT            NULL,
    [RejectedDateTime]       DATETIME       NULL,
    [ModifiedDate]           DATETIME       NULL,
    [ImgLargeUrl]            VARCHAR (250)  NULL,
    [ImgThumbUrl]            VARCHAR (250)  NULL,
    [CarScore]               INT            NULL,
    [AbSure_WarrantyTypesId] INT            NULL,
    [FinalWarrantyTypeId]    INT            NULL,
    [WarrantyGivenBy]        BIGINT         NULL,
    [FinalWarrantyDate]      DATETIME       NULL,
    [SurveyDate]             DATETIME       NULL,
    [IsSoldOut]              BIT            NULL,
    [OwnerName]              VARCHAR (50)   NULL,
    [OwnerAddress]           VARCHAR (500)  NULL,
    [OwnerPhoneNo]           VARCHAR (50)   NULL,
    [OwnerEmail]             VARCHAR (150)  NULL,
    [OwnerCityId]            INT            NULL,
    [OwnerAreaId]            INT            NULL,
    [Status]                 TINYINT        NULL,
    [CancelReason]           VARCHAR (1000) NULL,
    [CancelledBy]            BIGINT         NULL,
    [CancelledOn]            DATETIME       NULL,
    [CarFittedWith]          TINYINT        NULL,
    [ReqWarranty]            INT            NULL,
    [EngineNo]               VARCHAR (50)   NULL,
    [IsActive]               BIT            NULL,
    [AppointmentDate]        DATETIME       NULL,
    [PolicyNo]               VARCHAR (50)   NULL,
    [AppointmentTime]        VARCHAR (50)   NULL,
    [AdId]                   VARCHAR (50)   NULL
);

