CREATE TABLE [dbo].[CarModels_Bkp15082015] (
    [ID]                   NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [Name]                 VARCHAR (30)    NOT NULL,
    [CarMakeId]            NUMERIC (18)    NOT NULL,
    [IsDeleted]            BIT             NOT NULL,
    [Used]                 BIT             NOT NULL,
    [New]                  BIT             NOT NULL,
    [Indian]               BIT             NOT NULL,
    [Imported]             BIT             NOT NULL,
    [Futuristic]           BIT             NOT NULL,
    [Classic]              BIT             NOT NULL,
    [Modified]             BIT             NOT NULL,
    [ReviewRate]           DECIMAL (18, 2) NULL,
    [ReviewCount]          NUMERIC (18)    NULL,
    [Looks]                DECIMAL (18, 2) NULL,
    [Performance]          DECIMAL (18, 2) NULL,
    [Comfort]              DECIMAL (18, 2) NULL,
    [ValueForMoney]        DECIMAL (18, 2) NULL,
    [FuelEconomy]          DECIMAL (18, 2) NULL,
    [SmallPic]             VARCHAR (200)   NULL,
    [LargePic]             VARCHAR (200)   NULL,
    [MoCreatedOn]          DATETIME        NULL,
    [MoUpdatedBy]          NUMERIC (18)    NULL,
    [MoUpdatedOn]          DATETIME        NULL,
    [IsReplicated]         BIT             NULL,
    [HostURL]              VARCHAR (100)   NULL,
    [comment]              VARCHAR (5000)  NULL,
    [Discontinuation_date] DATETIME        NULL,
    [ReplacedByModelId]    SMALLINT        NULL,
    [DiscontinuationId]    INT             NULL,
    [MinPrice]             INT             NULL,
    [MaxPrice]             INT             NULL,
    [CarVersionID_Top]     INT             NULL,
    [SubSegmentID]         INT             NULL,
    [Summary]              NVARCHAR (MAX)  NULL,
    [MaskingName]          VARCHAR (50)    NULL,
    [RootId]               SMALLINT        NULL,
    [Platform]             VARCHAR (500)   NULL,
    [Generation]           TINYINT         NULL,
    [Upgrade]              TINYINT         NULL,
    [ModelLaunchDate]      DATETIME        NULL,
    [UsedCarRating]        FLOAT (53)      NULL,
    [VideoCount]           INT             NULL,
    [ModelBodyStyle]       TINYINT         NULL,
    [XLargePic]            VARCHAR (150)   NULL,
    [OriginalImgPath]      VARCHAR (150)   NULL
);

