CREATE TABLE [dbo].[CDMCarspec1] (
    [CarVersionId] INT           NOT NULL,
    [1]            INT           NULL,
    [2]            INT           NULL,
    [3]            INT           NULL,
    [4]            INT           NULL,
    [5]            INT           NULL,
    [8]            INT           NULL,
    [6]            INT           NULL,
    [9]            SMALLINT      NULL,
    [10]           INT           NULL,
    [11]           INT           NULL,
    [12]           FLOAT (53)    NULL,
    [13]           VARCHAR (200) NULL,
    [14]           INT           NULL,
    [249]          VARCHAR (50)  NULL,
    [250]          VARCHAR (50)  NULL,
    [20]           FLOAT (53)    NULL,
    [21]           FLOAT (53)    NULL,
    [22]           FLOAT (53)    NULL,
    [23]           SMALLINT      NULL,
    [24]           VARCHAR (200) NULL,
    [25]           SMALLINT      NULL,
    [26]           VARCHAR (50)  NULL,
    [27]           VARCHAR (200) NULL,
    [28]           VARCHAR (200) NULL,
    [30]           SMALLINT      NULL,
    [29]           VARCHAR (50)  NULL,
    [31]           VARCHAR (50)  NULL,
    [32]           VARCHAR (50)  NULL,
    [33]           FLOAT (53)    NULL,
    [39]           VARCHAR (200) NULL,
    [40]           VARCHAR (200) NULL,
    [41]           VARCHAR (200) NULL,
    [43]           VARCHAR (200) NULL,
    [201]          VARCHAR (200) NULL,
    [47]           VARCHAR (200) NULL,
    [45]           VARCHAR (200) NULL,
    [72]           VARCHAR (50)  NULL,
    [46]           FLOAT (53)    NULL,
    [48]           INT           NULL,
    [49]           INT           NULL,
    [50]           INT           NULL,
    [51]           INT           NULL,
    [52]           INT           NULL,
    [53]           INT           NULL
);

