CREATE TABLE [dbo].[CeoReport] (
    [ID]                NUMERIC (18) IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ReportMonth]       DATETIME     NOT NULL,
    [Valuations]        NUMERIC (18) NULL,
    [Recommendations]   NUMERIC (18) NULL,
    [UCProfileView]     NUMERIC (18) NULL,
    [NCProfileView]     NUMERIC (18) NULL,
    [ReviewView]        NUMERIC (18) NULL,
    [AnswersView]       NUMERIC (18) NULL,
    [AveragePageView]   NUMERIC (18) NULL,
    [AverageAlexaRank]  NUMERIC (18) NULL,
    [ReachPerMillion]   NUMERIC (18) NULL,
    [AdSpend]           NUMERIC (18) NULL,
    [GoogleAdSpend]     NUMERIC (18) NULL,
    [AdRealized]        NUMERIC (18) NULL,
    [RevenuePotentialI] NUMERIC (18) NULL,
    [RevenueRealizedI]  NUMERIC (18) NULL,
    [TotalDealers]      NUMERIC (18) NULL,
    [ActiveDealers]     NUMERIC (18) NULL,
    [RevenuePotentialD] NUMERIC (18) NULL,
    [RevenueRealizedD]  NUMERIC (18) NULL,
    [DivisionCostI]     NUMERIC (18) NULL,
    [DivisionCostD]     NUMERIC (18) NULL,
    [TotalUsers]        NUMERIC (18) NULL,
    [AvgLiveStockI]     NUMERIC (18) NULL,
    [AvgLiveStockD]     NUMERIC (18) NULL,
    [GoogleAdClicks]    NUMERIC (18) NULL,
    [LeadRevenue]       NUMERIC (18) NULL,
    CONSTRAINT [PK_CeoReport] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

