CREATE TABLE [dbo].[classified_analysis_leadincrease] (
    [ID]                   NUMERIC (18)  NOT NULL,
    [CustomerId]           NUMERIC (18)  NOT NULL,
    [CityId]               INT           NULL,
    [CarVersionId]         NUMERIC (18)  NOT NULL,
    [CarRegNo]             VARCHAR (50)  NOT NULL,
    [EntryDate]            DATETIME      NOT NULL,
    [Price]                DECIMAL (18)  NOT NULL,
    [MakeYear]             DATETIME      NOT NULL,
    [Kilometers]           NUMERIC (18)  NOT NULL,
    [Color]                VARCHAR (100) NULL,
    [ColorCode]            VARCHAR (6)   NULL,
    [Comments]             VARCHAR (500) NULL,
    [IsArchived]           BIT           NOT NULL,
    [IsApproved]           BIT           NOT NULL,
    [ForwardDealers]       BIT           NOT NULL,
    [ListInClassifieds]    BIT           NOT NULL,
    [IsFake]               BIT           NOT NULL,
    [StatusId]             SMALLINT      NOT NULL,
    [LastBidDate]          DATETIME      NULL,
    [ClassifiedExpiryDate] DATETIME      NULL,
    [ViewCount]            NUMERIC (18)  NULL,
    [PaidInqLeft]          INT           NOT NULL,
    [FreeInqLeft]          INT           NOT NULL,
    [PackageType]          SMALLINT      NOT NULL,
    [PackageExpiryDate]    DATETIME      NULL,
    [SourceId]             SMALLINT      NOT NULL,
    [IsVerified]           BIT           NULL,
    [CarRegState]          CHAR (4)      NULL,
    [PinCode]              INT           NULL,
    [SellInquiryId]        NUMERIC (18)  NULL,
    [RequestDateTime]      DATETIME      NULL
);

