CREATE TABLE [dbo].[Con_TestimonialCategory] (
    [Id]   NUMERIC (18)  IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Name] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_Con_TestimonialCategory] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 90)
);

