CREATE TABLE [dbo].[Con_EditCms_Basic_Bkp191114] (
    [Id]                        NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [CategoryId]                NUMERIC (18)   NULL,
    [Title]                     VARCHAR (250)  NULL,
    [Url]                       VARCHAR (200)  NULL,
    [DisplayDate]               DATETIME       NULL,
    [AuthorName]                VARCHAR (100)  NULL,
    [AuthorId]                  NUMERIC (18)   NOT NULL,
    [Description]               VARCHAR (8000) NULL,
    [IsActive]                  BIT            NULL,
    [EnteredBy]                 NUMERIC (18)   NOT NULL,
    [EntryDate]                 DATETIME       NOT NULL,
    [IsPublished]               BIT            NULL,
    [PublishedDate]             DATETIME       NULL,
    [LastUpdatedTime]           DATETIME       NULL,
    [LastUpdatedBy]             NUMERIC (18)   NULL,
    [ShowGallery]               BIT            NULL,
    [ForumThreadId]             INT            NULL,
    [Views]                     INT            NOT NULL,
    [MainImageSet]              BIT            NOT NULL,
    [RoadTestId]                INT            NULL,
    [IsUpdated]                 BIT            NOT NULL,
    [HostURL]                   VARCHAR (100)  NULL,
    [IsReplicated]              BIT            NULL,
    [HasCustomImg]              BIT            NULL,
    [IsDealerFriendly]          BIT            NULL,
    [MainImgCaption]            VARCHAR (250)  NULL,
    [StickyFromDate]            DATETIME       NULL,
    [StickyToDate]              DATETIME       NULL,
    [IsSticky]                  BIT            NULL,
    [ReasonToUnpublish]         VARCHAR (500)  NULL,
    [UnPublishedBy]             BIGINT         NULL,
    [UnPublishedDate]           DATETIME       NULL,
    [IsFeatured]                BIT            NULL,
    [IsCompatibleForNewsLetter] BIT            NULL,
    [SocialMediaLine]           VARCHAR (120)  NULL,
    [ApplicationID]             TINYINT        NULL
);

