CREATE TABLE [dbo].[CRM_BMW_APIData] (
    [Id]                     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [CBDId]                  BIGINT         NOT NULL,
    [Salutation]             VARCHAR (5)    NULL,
    [SalutationValue]        VARCHAR (100)  NULL,
    [Mobile]                 VARCHAR (15)   NULL,
    [AlternateMobile]        VARCHAR (15)   NULL,
    [FirstName]              VARCHAR (25)   NULL,
    [LastName]               VARCHAR (25)   NULL,
    [Email]                  VARCHAR (100)  NULL,
    [DealerNameValue]        VARCHAR (100)  NULL,
    [DealerId]               NUMERIC (18)   NULL,
    [City]                   VARCHAR (50)   NULL,
    [MakeNameValue]          VARCHAR (100)  NULL,
    [ModelNameValue]         VARCHAR (100)  NULL,
    [VersionNameValue]       VARCHAR (100)  NULL,
    [MakeId]                 NUMERIC (18)   NULL,
    [ModelId]                NUMERIC (18)   NULL,
    [VersionId]              NUMERIC (18)   NULL,
    [IsFinaceRequired]       VARCHAR (5)    NULL,
    [PurchaseIntention]      VARCHAR (100)  NULL,
    [PurchaseIntentionValue] VARCHAR (100)  NULL,
    [LookingFor]             VARCHAR (20)   NULL,
    [TradeCarMake]           VARCHAR (50)   NULL,
    [TradeCarModel]          VARCHAR (50)   NULL,
    [TradeCarVersion]        VARCHAR (50)   NULL,
    [TradeCarYear]           VARCHAR (20)   NULL,
    [TradeCarKms]            VARCHAR (20)   NULL,
    [GeneralRemarks]         VARCHAR (5000) NULL,
    [CreatedOn]              DATETIME       CONSTRAINT [DF_CRM_BMW_APIData_CreatedOn] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]              BIGINT         NULL,
    [BMWRefId]               VARCHAR (250)  NULL,
    [UpdatedOn]              DATETIME       NULL,
    [OtherCars]              VARCHAR (150)  NULL,
    [OtherBMWCars]           VARCHAR (150)  NULL,
    [CurrentCarOwned]        VARCHAR (250)  NULL,
    CONSTRAINT [PK_CRM_BMW_APIData_1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

