CREATE TABLE [dbo].[CRM_OEMZones] (
    [ID]       NUMERIC (18) NOT NULL,
    [MakeId]   NUMERIC (18) NOT NULL,
    [ZoneName] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CRM_OEMZones] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

