CREATE TABLE [dbo].[CRM_CustomerOtherDetails] (
    [CRM_CustomerId]     NUMERIC (18)  NOT NULL,
    [DOB]                VARCHAR (50)  NULL,
    [Sex]                VARCHAR (50)  NULL,
    [MaritalStatus]      VARCHAR (50)  NULL,
    [Qualification]      VARCHAR (100) NULL,
    [ResAddress]         VARCHAR (500) NULL,
    [Fax]                VARCHAR (50)  NULL,
    [PinCode]            VARCHAR (50)  NULL,
    [ResStatus]          VARCHAR (100) NULL,
    [YearsAtRes]         VARCHAR (50)  NULL,
    [MonthsAtRes]        VARCHAR (50)  NULL,
    [NoOfDependents]     VARCHAR (50)  NULL,
    [GrossMonthlyIncome] VARCHAR (50)  NULL,
    [IdType]             VARCHAR (50)  NULL,
    [IdNumber]           VARCHAR (50)  NULL,
    [OccupationType]     VARCHAR (50)  NULL,
    [CompanyName]        VARCHAR (200) NULL,
    [CompanyType]        VARCHAR (100) NULL,
    [NatureOfBusiness]   VARCHAR (50)  NULL,
    [Designation]        VARCHAR (50)  NULL,
    [YearsInBusiness]    VARCHAR (50)  NULL,
    [MonthsInBusiness]   VARCHAR (50)  NULL,
    [OfficeAddress]      VARCHAR (500) NULL,
    [OfficeLandLine]     VARCHAR (50)  NULL,
    [OfficePinCode]      VARCHAR (50)  NULL,
    [OfficeCityId]       NUMERIC (18)  NULL,
    [CreatedOn]          DATETIME      NOT NULL,
    [UpdatedOn]          DATETIME      NOT NULL,
    [UpdatedBy]          NUMERIC (18)  CONSTRAINT [DF_CRM_CustomerOtherDetails_UpdatedBy] DEFAULT ((-1)) NOT NULL,
    CONSTRAINT [PK_CNS_CustomerOtherDetails] PRIMARY KEY CLUSTERED ([CRM_CustomerId] ASC) WITH (FILLFACTOR = 90)
);

