CREATE TABLE [dbo].[CrossListingDupListingCustomerSellInquiryDetails] (
    [InquiryId]               NUMERIC (18)  NOT NULL,
    [RegistrationPlace]       VARCHAR (50)  NULL,
    [Insurance]               VARCHAR (50)  NULL,
    [InsuranceExpiry]         DATETIME      NULL,
    [Owners]                  NUMERIC (10)  NULL,
    [Tax]                     VARCHAR (50)  NULL,
    [InteriorColor]           VARCHAR (50)  NULL,
    [InteriorColorCode]       VARCHAR (6)   NULL,
    [CityMileage]             VARCHAR (50)  NULL,
    [AdditionalFuel]          VARCHAR (50)  NULL,
    [CarDriven]               VARCHAR (50)  NULL,
    [Accidental]              BIT           NULL,
    [FloodAffected]           BIT           NULL,
    [Accessories]             VARCHAR (500) NULL,
    [Warranties]              VARCHAR (500) NULL,
    [Modifications]           VARCHAR (500) NULL,
    [ACCondition]             VARCHAR (50)  NULL,
    [BatteryCondition]        VARCHAR (50)  NULL,
    [BrakesCondition]         VARCHAR (50)  NULL,
    [ElectricalsCondition]    VARCHAR (50)  NULL,
    [EngineCondition]         VARCHAR (50)  NULL,
    [ExteriorCondition]       VARCHAR (50)  NULL,
    [SeatsCondition]          VARCHAR (50)  NULL,
    [SuspensionsCondition]    VARCHAR (50)  NULL,
    [TyresCondition]          VARCHAR (50)  NULL,
    [InteriorCondition]       VARCHAR (50)  NULL,
    [OverallCondition]        VARCHAR (50)  NULL,
    [Features_SafetySecurity] VARCHAR (200) NULL,
    [Features_Others]         VARCHAR (200) NULL,
    [Features_Comfort]        VARCHAR (200) NULL,
    [YoutubeVideo]            VARCHAR (200) NULL,
    [IsYouTubeVideoApproved]  BIT           NULL
);

