CREATE TABLE [dbo].[CustomerSellInquiriesEditRequest] (
    [ID]                   NUMERIC (18)  IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [InquiryId]            NUMERIC (18)  NOT NULL,
    [CustomerId]           NUMERIC (18)  NOT NULL,
    [CarVersionId]         NUMERIC (18)  NOT NULL,
    [CarRegNo]             VARCHAR (15)  NOT NULL,
    [EntryDate]            DATETIME      NOT NULL,
    [Price]                DECIMAL (18)  NOT NULL,
    [MakeYear]             DATETIME      NOT NULL,
    [Kilometers]           NUMERIC (18)  NOT NULL,
    [Color]                VARCHAR (30)  NULL,
    [Comments]             VARCHAR (500) NULL,
    [RegistrationPlace]    VARCHAR (50)  NULL,
    [Insurance]            VARCHAR (50)  NULL,
    [InsuranceExpiry]      DATETIME      NULL,
    [Owners]               NUMERIC (10)  NULL,
    [Tax]                  VARCHAR (50)  NULL,
    [InteriorColor]        VARCHAR (50)  NULL,
    [CityMileage]          VARCHAR (50)  NULL,
    [AdditionalFuel]       VARCHAR (50)  NULL,
    [CarDriven]            VARCHAR (50)  NULL,
    [Accidental]           BIT           CONSTRAINT [DF_CustomerSellInquiriesEditRequest_Accidental] DEFAULT (0) NOT NULL,
    [FloodAffected]        BIT           CONSTRAINT [DF_CustomerSellInquiriesEditRequest_FloodAffected] DEFAULT (0) NOT NULL,
    [Accessories]          VARCHAR (500) NULL,
    [Warranties]           VARCHAR (500) NULL,
    [Modifications]        VARCHAR (500) NULL,
    [BatteryCondition]     VARCHAR (50)  NULL,
    [BrakesCondition]      VARCHAR (50)  NULL,
    [ElectricalsCondition] VARCHAR (50)  NULL,
    [EngineCondition]      VARCHAR (50)  NULL,
    [ExteriorCondition]    VARCHAR (50)  NULL,
    [SeatsCondition]       VARCHAR (50)  NULL,
    [SuspensionsCondition] VARCHAR (50)  NULL,
    [TyresCondition]       VARCHAR (50)  NULL,
    [OverallCondition]     VARCHAR (50)  NULL,
    [isUpdated]            BIT           CONSTRAINT [DF_CustomerSellInquiriesEditRequest_isUpdated] DEFAULT (0) NOT NULL,
    [isDiscarded]          BIT           CONSTRAINT [DF_CustomerSellInquiriesEditRequest_isDiscarded] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_CustSellInqEditRQ] PRIMARY KEY CLUSTERED ([ID] ASC)
);

