CREATE TABLE [dbo].[CW_FinanceLeads] (
    [Id]                      NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [First_Name]              VARCHAR (100) NULL,
    [Last_Name]               VARCHAR (100) NULL,
    [Email]                   VARCHAR (100) NULL,
    [Mobile]                  VARCHAR (15)  NULL,
    [CityId]                  INT           NULL,
    [VersionId]               INT           NULL,
    [LeadClickSource]         INT           NULL,
    [Pan_No]                  VARCHAR (20)  NULL,
    [Res_address]             VARCHAR (500) NULL,
    [Res_address2]            VARCHAR (500) NULL,
    [Res_address3]            VARCHAR (500) NULL,
    [Resi_type]               VARCHAR (200) NULL,
    [Res_City]                VARCHAR (50)  NULL,
    [Resi_City_other]         VARCHAR (50)  NULL,
    [Resi_City_other1]        VARCHAR (50)  NULL,
    [Res_Pin]                 VARCHAR (10)  NULL,
    [Company_Name]            VARCHAR (200) NULL,
    [DateOfBirth]             DATETIME      NULL,
    [Designation]             VARCHAR (50)  NULL,
    [Emp_Type]                VARCHAR (50)  NULL,
    [Monthly_Income]          INT           NULL,
    [Card_Held]               VARCHAR (50)  NULL,
    [Source_Code]             VARCHAR (50)  NULL,
    [Promo_Code]              VARCHAR (50)  NULL,
    [Lead_Date_Time]          DATETIME      NULL,
    [Product_Applied_For]     VARCHAR (50)  NULL,
    [ExistingCust]            VARCHAR (50)  NULL,
    [YearsInEmp]              INT           NULL,
    [Emi_Paid]                VARCHAR (20)  NULL,
    [Car_Make]                VARCHAR (50)  NULL,
    [Car_Model]               VARCHAR (50)  NULL,
    [TypeOfLoan]              VARCHAR (50)  NULL,
    [IP_Address]              VARCHAR (50)  NULL,
    [Indigo_UniqueKey]        VARCHAR (50)  NULL,
    [Indigo_RequestFromYesNo] VARCHAR (10)  NULL,
    [LoanAmount]              FLOAT (53)    NULL,
    [ROI]                     FLOAT (53)    NULL,
    [LTV]                     FLOAT (53)    NULL,
    [CarPrice]                INT           NULL,
    [IsPermitted]             BIT           NULL,
    [IsPushSuccess]           BIT           NULL,
    [BankTypeId]              SMALLINT      NULL,
    [ApiResponse]             VARCHAR (100) NULL,
    [EntryDateTime]           DATETIME      CONSTRAINT [DF_CW_FinanceLeads_EntryDateTime] DEFAULT (getdate()) NULL,
    [BuyingPeriod]            VARCHAR (50)  NULL,
    [IncomeTypeId]            INT           NULL,
    [YearsInRes]              INT           NULL,
    [UpdatedOn]               DATETIME      NULL,
    [FailureReason]           VARCHAR (200) NULL,
    [ClientId]                SMALLINT      NULL,
    [PlatformId]              SMALLINT      NULL,
    [UtmCode]                 VARCHAR (20)  NULL,
    CONSTRAINT [PK_CW_FinanceLeads] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ix_CW_FinanceLeads_Mobile]
    ON [dbo].[CW_FinanceLeads]([Mobile] ASC)
    INCLUDE([EntryDateTime], [IsPushSuccess]);

