CREATE TABLE [dbo].[DCRM_PaymentDetails] (
    [ID]                      INT             IDENTITY (1, 1) NOT NULL,
    [Mode]                    INT             NOT NULL,
    [Amount]                  NUMERIC (18, 2) NULL,
    [CheckDDPdcNumber]        VARCHAR (50)    NULL,
    [BankName]                VARCHAR (100)   NULL,
    [PaymentDate]             DATETIME        NULL,
    [AddedBy]                 INT             NOT NULL,
    [AddedOn]                 DATETIME        NOT NULL,
    [SalesDealerID]           INT             NULL,
    [IsApproved]              BIT             CONSTRAINT [DF_DCRM_PaymentDetails_IsApproved] DEFAULT ((0)) NULL,
    [ApprovedBy]              INT             NULL,
    [ApprovedOn]              DATETIME        NULL,
    [DealerPackageFeatureId]  INT             NULL,
    [TransactionId]           INT             NULL,
    [DrawerName]              VARCHAR (100)   NULL,
    [BranchName]              VARCHAR (100)   NULL,
    [InFavorOf]               VARCHAR (100)   NULL,
    [PaymentType]             INT             NULL,
    [DepositedBy]             VARCHAR (100)   NULL,
    [UtrTransactionId]        VARCHAR (100)   NULL,
    [ChequeDDPdcDate]         DATETIME        NULL,
    [DepositedDate]           DATETIME        NULL,
    [UpdatedBy]               INT             NULL,
    [UpdatedOn]               DATETIME        NULL,
    [ServiceTax]              FLOAT (53)      NULL,
    [IsTDSGiven]              BIT             NULL,
    [TDSAmount]               NUMERIC (18, 2) NULL,
    [PANNumber]               VARCHAR (10)    NULL,
    [TANNumber]               VARCHAR (10)    NULL,
    [PaymentReceived]         NUMERIC (18, 2) NULL,
    [AttachedFile]            VARCHAR (500)   NULL,
    [FileHostUrl]             VARCHAR (100)   NULL,
    [AmountReceived]          NUMERIC (18, 2) NULL,
    [ReceivedDate]            DATETIME        NULL,
    [RejectedReason]          VARCHAR (250)   NULL,
    [PaymentRejectedReasonId] INT             NULL,
    [DepSlipHostUrl]          VARCHAR (50)    NULL,
    [DepSlipOriginalImgPath]  VARCHAR (300)   NULL,
    [Source]                  SMALLINT        DEFAULT ((1)) NULL,
    [HostUrl]                 VARCHAR (50)    NULL,
    [OriginalImgPath]         VARCHAR (300)   NULL,
    [IssuerBankName]          VARCHAR (300)   NULL,
    [Comments]                VARCHAR (500)   NULL,
    CONSTRAINT [PK_DCRM_PaymentDetails] PRIMARY KEY CLUSTERED ([ID] ASC)
);

