CREATE TABLE [dbo].[DCRM_SalesDealerBkp041214] (
    [Id]                  NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [DealerId]            NUMERIC (18)    NOT NULL,
    [EntryDate]           DATETIME        NOT NULL,
    [LeadSource]          INT             NOT NULL,
    [DealerType]          INT             NOT NULL,
    [ClosingProbability]  INT             NOT NULL,
    [ClosingDate]         DATETIME        NULL,
    [ClosingAmount]       NUMERIC (18)    NULL,
    [PitchingProduct]     INT             NULL,
    [PitchDuration]       INT             NULL,
    [LeadStatus]          INT             NULL,
    [UpdatedBy]           INT             NULL,
    [UpdatedOn]           DATETIME        NULL,
    [PackageExpiryDate]   DATETIME        NULL,
    [CreatedOn]           DATETIME        NOT NULL,
    [BOExecutive]         INT             NULL,
    [FieldExecutive]      INT             NULL,
    [LostReason]          INT             NULL,
    [IsSalesAppointment]  BIT             NULL,
    [InitiatedBy]         NUMERIC (18)    NULL,
    [OtherResons]         VARCHAR (100)   NULL,
    [StartMeetingId]      NUMERIC (18)    NULL,
    [ClosedMeetingID]     NUMERIC (18)    NULL,
    [RVNPackageFeatureId] INT             NULL,
    [DiscountAmount]      INT             NULL,
    [ProductAmount]       INT             NULL,
    [ServiceTax]          FLOAT (53)      NULL,
    [TotalAmount]         DECIMAL (18, 2) NULL,
    [TDSAmount]           DECIMAL (18, 2) NULL,
    [IsTDSGiven]          BIT             NULL,
    [DiscountDays]        INT             NULL,
    [PANNumber]           VARCHAR (10)    NULL,
    [TANNumber]           VARCHAR (10)    NULL,
    [Quantity]            INT             NULL
);

