CREATE TABLE [dbo].[DCRM_VerifiedDealerPool] (
    [ID]              NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [Organization]    VARCHAR (60)  NOT NULL,
    [Name]            VARCHAR (50)  NULL,
    [EmailId]         VARCHAR (60)  NOT NULL,
    [StateId]         NUMERIC (18)  NOT NULL,
    [CityId]          NUMERIC (18)  NOT NULL,
    [AreaId]          NUMERIC (18)  NULL,
    [Address1]        VARCHAR (100) NOT NULL,
    [Pincode]         VARCHAR (6)   NULL,
    [MobileNo]        VARCHAR (15)  NOT NULL,
    [PhoneNo]         VARCHAR (15)  NULL,
    [FaxNo]           VARCHAR (15)  NULL,
    [EntryDate]       DATETIME      NOT NULL,
    [ContactPerson]   VARCHAR (60)  NOT NULL,
    [ContactHours]    VARCHAR (60)  NULL,
    [ContactEmail]    VARCHAR (60)  NULL,
    [UpdatedBy]       NUMERIC (18)  NULL,
    [UpdatedOn]       DATETIME      NULL,
    [IsDeleted]       BIT           NULL,
    [LeadSource]      SMALLINT      NULL,
    [ReferredBy]      INT           NULL,
    [VerifiedBy]      INT           NULL,
    [VerifiedOn]      DATETIME      NULL,
    [DealerStatus]    INT           NULL,
    [TC_DealerTypeId] TINYINT       NULL,
    [Dealer_Id]       NUMERIC (18)  NULL,
    [ApplicationId]   INT           DEFAULT ((1)) NULL,
    CONSTRAINT [PK_DCRM_VerifiedDealerPool] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

