CREATE TABLE [dbo].[DCRM_SalesDealer] (
    [Id]                  NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [DealerId]            NUMERIC (18)    NOT NULL,
    [EntryDate]           DATETIME        NOT NULL,
    [LeadSource]          INT             NOT NULL,
    [DealerType]          INT             NULL,
    [ClosingProbability]  INT             NOT NULL,
    [ClosingDate]         DATETIME        NULL,
    [ClosingAmount]       NUMERIC (18)    NULL,
    [PitchingProduct]     INT             NULL,
    [PitchDuration]       INT             NULL,
    [LeadStatus]          INT             NULL,
    [UpdatedBy]           INT             NULL,
    [UpdatedOn]           DATETIME        NULL,
    [PackageExpiryDate]   DATETIME        NULL,
    [CreatedOn]           DATETIME        CONSTRAINT [DF_DCRM_SalesDealer_CreatedOn] DEFAULT (getdate()) NOT NULL,
    [BOExecutive]         INT             NULL,
    [FieldExecutive]      INT             NULL,
    [LostReason]          INT             NULL,
    [IsSalesAppointment]  BIT             NULL,
    [InitiatedBy]         NUMERIC (18)    NULL,
    [OtherResons]         VARCHAR (100)   NULL,
    [StartMeetingId]      NUMERIC (18)    NULL,
    [ClosedMeetingID]     NUMERIC (18)    NULL,
    [RVNPackageFeatureId] INT             NULL,
    [DiscountAmount]      INT             NULL,
    [ProductAmount]       INT             NULL,
    [ServiceTax]          FLOAT (53)      NULL,
    [TotalAmount]         DECIMAL (18, 2) NULL,
    [TDSAmount]           DECIMAL (18, 2) NULL,
    [IsTDSGiven]          BIT             NULL,
    [DiscountDays]        INT             NULL,
    [PANNumber]           VARCHAR (10)    NULL,
    [TANNumber]           VARCHAR (15)    NULL,
    [Quantity]            INT             NULL,
    [TransactionId]       INT             NULL,
    [IsFromMobile]        BIT             NULL,
    [IsFreeTrial]         BIT             NULL,
    [IsLPAUploaded]       BIT             NULL,
    [FileHostURL]         VARCHAR (100)   NULL,
    [ProductStatus]       INT             NULL,
    [PercentageSlab]      FLOAT (53)      NULL,
    [AttachedLPA]         VARCHAR (250)   NULL,
    [CampaignType]        SMALLINT        NULL,
    [NoOfLeads]           INT             NULL,
    [Comments]            VARCHAR (1000)  NULL,
    [Model]               VARCHAR (100)   NULL,
    [ExceptionModel]      VARCHAR (100)   NULL,
    [LeadPerDay]          INT             NULL,
    [StartDate]           DATETIME        NULL,
    [ContractType]        INT             NULL,
    [Source]              SMALLINT        DEFAULT ((1)) NULL,
    [IsMultiOutlet]       BIT             NULL,
    [LPANumber]           INT             NULL,
    CONSTRAINT [PK_DCRM_SalesDealer] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DCRM_SalesDealer_TransactionId]
    ON [dbo].[DCRM_SalesDealer]([TransactionId] ASC)
    INCLUDE([DealerId]);

