CREATE TABLE [dbo].[DealerOffers_Bkp15082015] (
    [ID]                 NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [CityId]             NUMERIC (18)  NULL,
    [DealerId]           NUMERIC (18)  NULL,
    [OfferTitle]         VARCHAR (200) NULL,
    [OfferDescription]   VARCHAR (MAX) NULL,
    [MaxOfferValue]      NUMERIC (18)  NULL,
    [Conditions]         VARCHAR (MAX) NULL,
    [StartDate]          DATETIME      NULL,
    [EndDate]            DATETIME      NULL,
    [EntryDate]          DATETIME      NULL,
    [EnteredBy]          NUMERIC (18)  NULL,
    [SourceCategory]     NUMERIC (18)  NULL,
    [SourceDescription]  VARCHAR (MAX) NULL,
    [IsActive]           BIT           NULL,
    [IsApproved]         BIT           NOT NULL,
    [IsCountryWide]      BIT           NOT NULL,
    [OfferType]          SMALLINT      NULL,
    [OfferUnits]         INT           NULL,
    [ClaimedUnits]       INT           NULL,
    [UpdatedOn]          DATETIME      NULL,
    [UpdatedBy]          INT           NULL,
    [HostURL]            VARCHAR (250) NULL,
    [ImageName]          VARCHAR (150) NULL,
    [ImagePath]          VARCHAR (150) NULL,
    [PreBookingEmailIds] VARCHAR (200) NULL,
    [PreBookingMobile]   VARCHAR (200) NULL,
    [CouponEmailIds]     VARCHAR (200) NULL,
    [CouponMobile]       VARCHAR (200) NULL,
    [DispOnDesk]         BIT           NULL,
    [DispOnMobile]       BIT           NULL
);

