CREATE TABLE [dbo].[Dealer_Newcar_Bkp101114] (
    [Id]                NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [MakeId]            NUMERIC (18)  NULL,
    [CityId]            NUMERIC (18)  NULL,
    [Name]              VARCHAR (100) NULL,
    [Address]           VARCHAR (500) NULL,
    [Pincode]           VARCHAR (50)  NULL,
    [ContactNo]         VARCHAR (200) NULL,
    [FaxNo]             VARCHAR (50)  NULL,
    [EMailId]           VARCHAR (100) NULL,
    [WebSite]           VARCHAR (100) NULL,
    [WorkingHours]      VARCHAR (50)  NULL,
    [LastUpdated]       DATETIME      NULL,
    [IsActive]          BIT           NULL,
    [IsNCD]             BIT           NOT NULL,
    [IsReplicated]      BIT           NULL,
    [HostURL]           VARCHAR (100) NULL,
    [TcDealerId]        NUMERIC (18)  NULL,
    [ContactPerson]     VARCHAR (200) NULL,
    [DealerMobileNo]    VARCHAR (50)  NULL,
    [NCSId]             NUMERIC (18)  NULL,
    [Mobile]            VARCHAR (10)  NULL,
    [IsPriority]        BIT           NULL,
    [IsNewDealer]       BIT           NULL,
    [PackageStartDate]  DATETIME      NULL,
    [PackageEndDate]    DATETIME      NULL,
    [CampaignId]        INT           NULL,
    [IsPremium]         BIT           NULL,
    [Latitude]          FLOAT (53)    NULL,
    [Longitude]         FLOAT (53)    NULL,
    [LeadPanelDealerId] INT           NULL,
    [ShowroomStartTime] VARCHAR (30)  NULL,
    [ShowroomEndTime]   VARCHAR (30)  NULL,
    [PrimaryMobileNo]   VARCHAR (20)  NULL,
    [SecondaryMobileNo] VARCHAR (20)  NULL,
    [LandLineNo]        VARCHAR (20)  NULL
);

