CREATE TABLE [dbo].[DealersLogs] (
    [DealerId]                 INT           NULL,
    [LoginId]                  VARCHAR (30)  NULL,
    [Passwd]                   VARCHAR (50)  NULL,
    [FirstName]                VARCHAR (100) NOT NULL,
    [LastName]                 VARCHAR (100) NULL,
    [EmailId]                  VARCHAR (250) NOT NULL,
    [Organization]             VARCHAR (100) NOT NULL,
    [Address1]                 VARCHAR (500) NOT NULL,
    [Address2]                 VARCHAR (500) NULL,
    [AreaId]                   NUMERIC (18)  NOT NULL,
    [CityId]                   NUMERIC (18)  NOT NULL,
    [StateId]                  NUMERIC (18)  NOT NULL,
    [Pincode]                  VARCHAR (50)  NULL,
    [PhoneNo]                  VARCHAR (200) NULL,
    [FaxNo]                    VARCHAR (50)  NULL,
    [MobileNo]                 VARCHAR (250) NULL,
    [BPContactPerson]          VARCHAR (60)  NULL,
    [JoiningDate]              DATETIME      NULL,
    [ExpiryDate]               DATETIME      NULL,
    [WebsiteUrl]               VARCHAR (100) NULL,
    [ContactPerson]            VARCHAR (200) NOT NULL,
    [ContactHours]             VARCHAR (50)  NULL,
    [ContactEmail]             VARCHAR (250) NULL,
    [LogoUrl]                  VARCHAR (100) NULL,
    [ROLE]                     VARCHAR (20)  NOT NULL,
    [Status]                   BIT           NOT NULL,
    [Preference]               SMALLINT      NOT NULL,
    [WeAreOpen]                TINYINT       NULL,
    [LastUpdatedOn]            DATETIME      NULL,
    [CertificationId]          SMALLINT      NOT NULL,
    [ConversionProb]           SMALLINT      NULL,
    [BPMobileNo]               VARCHAR (15)  NULL,
    [IsTCDealer]               BIT           NOT NULL,
    [IsWKitSent]               BIT           NOT NULL,
    [IsTCTrainingGiven]        BIT           NULL,
    [LastServiceVisit]         DATETIME      NOT NULL,
    [IsMultiOutlet]            BIT           NOT NULL,
    [HostURL]                  VARCHAR (100) NULL,
    [IsReplicated]             BIT           NULL,
    [TC_DealerTypeId]          TINYINT       NULL,
    [Lattitude]                FLOAT (53)    NULL,
    [Longitude]                FLOAT (53)    NULL,
    [DealerSource]             INT           NOT NULL,
    [IsDealerActive]           INT           NULL,
    [IsDealerDeleted]          BIT           NULL,
    [DeletedBy]                INT           NULL,
    [DeletedOn]                DATETIME      NULL,
    [DeletedReason]            SMALLINT      NULL,
    [DeletedComment]           VARCHAR (500) NULL,
    [HavingWebsite]            BIT           NULL,
    [PaidDealer]               BIT           NULL,
    [ActiveMaskingNumber]      VARCHAR (20)  NULL,
    [DealerVerificationStatus] SMALLINT      NULL,
    [IsNcs]                    BIT           NULL,
    [RegDealerId]              NUMERIC (18)  NULL,
    [MailerName]               VARCHAR (200) NULL,
    [MailerEmailId]            VARCHAR (200) NULL,
    [TC_BrandZoneId]           INT           NULL,
    [TC_RMID]                  INT           NULL,
    [TC_AMId]                  INT           NULL,
    [DealerCode]               VARCHAR (50)  NULL,
    [IsPremium]                BIT           NULL,
    [SendTextMail]             BIT           NULL,
    [WebsiteContactPerson]     VARCHAR (100) NULL,
    [WebsiteContactMobile]     VARCHAR (50)  NULL,
    [DealerLeadBusinessType]   SMALLINT      NULL,
    [HasMultipleBranch]        BIT           NULL,
    [ApplicationId]            TINYINT       NULL,
    [IsWarranty]               BIT           NULL,
    [LeadServingDistance]      SMALLINT      NULL,
    [OutletCnt]                INT           NULL,
    [IsInspection]             BIT           NULL,
    [ProfilePhotoHostUrl]      VARCHAR (100) NULL,
    [ProfilePhotoUrl]          VARCHAR (250) NULL,
    [ProfilePhotoStatusId]     INT           NULL,
    [TC_UserId]                INT           NULL,
    [AutoInspection]           BIT           NOT NULL,
    [InspectionOnSunday]       BIT           NOT NULL,
    [RCNotMandatory]           BIT           NULL,
    [OriginalImgPath]          VARCHAR (250) NULL,
    [OwnerMobile]              VARCHAR (20)  NULL,
    [ShowroomStartTime]        VARCHAR (30)  NULL,
    [ShowroomEndTime]          VARCHAR (30)  NULL,
    [Dealer_NewCarID]          INT           NULL,
    [DealerCreatedOn]          DATETIME      NULL,
    [DealerCreatedBy]          INT           NULL,
    [DealerLastUpdatedBy]      INT           NULL,
    [ActionDate]               DATETIME      DEFAULT (getdate()) NULL,
    [ActionTaken]              VARCHAR (30)  NULL,
    [ActionTakenBy]            VARCHAR (50)  NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_DealersLogs_DealerId]
    ON [dbo].[DealersLogs]([DealerId] ASC);

