CREATE TABLE [dbo].[dealers_Sep26] (
    [ID]                NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [LoginId]           VARCHAR (30)  NOT NULL,
    [Passwd]            VARCHAR (20)  NOT NULL,
    [FirstName]         VARCHAR (50)  NOT NULL,
    [LastName]          VARCHAR (50)  NULL,
    [EmailId]           VARCHAR (60)  NOT NULL,
    [Organization]      VARCHAR (60)  NOT NULL,
    [Address1]          VARCHAR (100) NOT NULL,
    [Address2]          VARCHAR (100) NULL,
    [AreaId]            NUMERIC (18)  NOT NULL,
    [CityId]            NUMERIC (18)  NOT NULL,
    [StateId]           NUMERIC (18)  NOT NULL,
    [Pincode]           VARCHAR (6)   NOT NULL,
    [PhoneNo]           VARCHAR (15)  NULL,
    [FaxNo]             VARCHAR (15)  NULL,
    [MobileNo]          VARCHAR (15)  NULL,
    [JoiningDate]       DATETIME      NOT NULL,
    [ExpiryDate]        DATETIME      NULL,
    [WebsiteUrl]        VARCHAR (50)  NULL,
    [ContactPerson]     VARCHAR (60)  NOT NULL,
    [ContactHours]      VARCHAR (20)  NOT NULL,
    [ContactEmail]      VARCHAR (60)  NULL,
    [LogoUrl]           VARCHAR (100) NULL,
    [ROLE]              VARCHAR (20)  NOT NULL,
    [Status]            BIT           NOT NULL,
    [Preference]        SMALLINT      NOT NULL,
    [WeAreOpen]         TINYINT       NOT NULL,
    [LastUpdatedOn]     DATETIME      NULL,
    [CertificationId]   SMALLINT      NOT NULL,
    [ConversionProb]    SMALLINT      NULL,
    [BPMobileNo]        VARCHAR (15)  NULL,
    [BPContactPerson]   VARCHAR (60)  NULL,
    [IsTCDealer]        BIT           NULL,
    [IsWKitSent]        BIT           NOT NULL,
    [LastServiceVisit]  DATETIME      NOT NULL,
    [IsTCTrainingGiven] BIT           NOT NULL,
    [IsMultiOutlet]     BIT           NOT NULL
);

