CREATE TABLE [NCAlert].[CustomerEligibleForMail] (
    [CustomerEligibleForMailId] INT           IDENTITY (1, 1) NOT NULL,
    [CustomerID]                INT           NULL,
    [NewCarPurchaseInquiriesId] BIGINT        NULL,
    [PQVersionId]               INT           NULL,
    [CustomerName]              VARCHAR (100) NULL,
    [CustomerEmail]             VARCHAR (100) NULL,
    [CustomerMobile]            VARCHAR (20)  NULL,
    [PQRequestDate]             DATETIME      NULL,
    [IsActive]                  BIT           NULL,
    [CustomerKey]               VARCHAR (50)  NULL,
    [CityId]                    INT           NULL,
    [CityName]                  VARCHAR (60)  NULL,
    [ShowroomPrice]             INT           NULL,
    [RTO]                       INT           NULL,
    [Insurance]                 INT           NULL,
    [DepotCharges]              INT           NULL,
    [MT1ShowroomPrice]          INT           NULL,
    [MT1RTO]                    INT           NULL,
    [MT1Insurance]              INT           NULL,
    [MT1DepotCharges]           INT           NULL,
    [MT2ShowroomPrice]          INT           NULL,
    [MT2RTO]                    INT           NULL,
    [MT2Insurance]              INT           NULL,
    [MT2DepotCharges]           INT           NULL,
    [MT3ShowroomPrice]          INT           NULL,
    [MT3RTO]                    INT           NULL,
    [MT3Insurance]              INT           NULL,
    [MT3DepotCharges]           INT           NULL
);

