CREATE TABLE [NCAlert].[NewCarAlertEmailEntireCarData] (
    [NewCarAlertEmailEntireCarDataId] INT           IDENTITY (1, 1) NOT NULL,
    [MakeId]                          INT           NULL,
    [MakeName]                        VARCHAR (50)  NULL,
    [ModelId]                         INT           NULL,
    [ModelName]                       VARCHAR (50)  NULL,
    [ModelMaskingName]                VARCHAR (50)  NULL,
    [VersionId]                       INT           NOT NULL,
    [VersionName]                     VARCHAR (50)  NULL,
    [ImageUrl]                        VARCHAR (250) NULL,
    [ExShowroomPrice]                 INT           NULL,
    [RTO]                             INT           NULL,
    [Insurance]                       INT           NULL,
    [DepotCharges]                    INT           NULL,
    [MT1VersionId]                    INT           NULL,
    [MT1MakeId]                       INT           NULL,
    [MT1MakeName]                     VARCHAR (50)  NULL,
    [MT1ModelId]                      INT           NULL,
    [MT1ModelName]                    VARCHAR (50)  NULL,
    [MT1ModelMaskingName]             VARCHAR (50)  NULL,
    [MT1VersionName]                  VARCHAR (50)  NULL,
    [MT1ImageUrl]                     VARCHAR (250) NULL,
    [MT1ShowroomPrice]                INT           NULL,
    [MT1RTO]                          INT           NULL,
    [MT1Insurance]                    INT           NULL,
    [MT1DepotCharges]                 INT           NULL,
    [MT2VersionId]                    INT           NULL,
    [MT2MakeId]                       INT           NULL,
    [MT2MakeName]                     VARCHAR (50)  NULL,
    [MT2ModelId]                      INT           NULL,
    [MT2ModelName]                    VARCHAR (50)  NULL,
    [MT2ModelMaskingName]             VARCHAR (50)  NULL,
    [MT2VersionName]                  VARCHAR (50)  NULL,
    [MT2ImageUrl]                     VARCHAR (250) NULL,
    [MT2ShowroomPrice]                INT           NULL,
    [MT2RTO]                          INT           NULL,
    [MT2Insurance]                    INT           NULL,
    [MT2DepotCharges]                 INT           NULL,
    [MT3VersionId]                    INT           NULL,
    [MT3MakeId]                       INT           NULL,
    [MT3MakeName]                     VARCHAR (50)  NULL,
    [MT3ModelId]                      INT           NULL,
    [MT3ModelName]                    VARCHAR (50)  NULL,
    [MT3ModelMaskingName]             VARCHAR (50)  NULL,
    [MT3VersionName]                  VARCHAR (50)  NULL,
    [MT3ImageUrl]                     VARCHAR (250) NULL,
    [MT3ShowroomPrice]                INT           NULL,
    [MT3RTO]                          INT           NULL,
    [MT3Insurance]                    INT           NULL,
    [MT3DepotCharges]                 INT           NULL,
    [Sm1ModelId]                      INT           NULL,
    [Sm1MakeId]                       INT           NULL,
    [Sm1MakeName]                     VARCHAR (50)  NULL,
    [Sm1ModelName]                    VARCHAR (50)  NULL,
    [Sm1ModelMaskingName]             VARCHAR (50)  NULL,
    [Sm1ImageUrl]                     VARCHAR (250) NULL,
    [Sm1MinPrice]                     INT           NULL,
    [Sm2ModelId]                      INT           NULL,
    [Sm2MakeId]                       INT           NULL,
    [Sm2MakeName]                     VARCHAR (50)  NULL,
    [Sm2ModelName]                    VARCHAR (50)  NULL,
    [Sm2ModelMaskingName]             VARCHAR (50)  NULL,
    [Sm2ImageUrl]                     VARCHAR (250) NULL,
    [Sm2MinPrice]                     INT           NULL,
    [Sm3ModelId]                      INT           NULL,
    [Sm3MakeId]                       INT           NULL,
    [Sm3MakeName]                     VARCHAR (50)  NULL,
    [Sm3ModelName]                    VARCHAR (50)  NULL,
    [Sm3ModelMaskingName]             VARCHAR (50)  NULL,
    [Sm3ImageUrl]                     VARCHAR (250) NULL,
    [Sm3MinPrice]                     INT           NULL,
    [Sm4ModelId]                      INT           NULL,
    [Sm4MakeId]                       INT           NULL,
    [Sm4MakeName]                     VARCHAR (50)  NULL,
    [Sm4ModelName]                    VARCHAR (50)  NULL,
    [Sm4ModelMaskingName]             VARCHAR (50)  NULL,
    [Sm4ImageUrl]                     VARCHAR (250) NULL,
    [Sm4MinPrice]                     INT           NULL,
    CONSTRAINT [PK_NewCarAlertEmailEntireCarData_VersionId] PRIMARY KEY NONCLUSTERED ([VersionId] ASC)
);

