//Action type for Screen
export const SET_MLA_SCREEN = "SET_MLA_SCREEN";
export const SET_RECOMMENDATION_SCREEN = "SET_RECOMMENDATION_SCREEN";
export const SET_THANKYOU_SCREEN = "SET_THANKYOU_SCREEN";
export const SET_SORRY_SCREEN = "SET_SORRY_SCREEN";
export const SET_HIDE = "SET_HIDE";
export const SET_SHOW = "SET_SHOW";
export const SET_LOCATION_SCREEN = "SET_LOCATION_SCREEN";
export const SET_FORM_SCREEN = "SET_FORM_SCREEN";
export const SET_WHATSAPP_FORM_SCREEN = "SET_WHATSAPP_FORM_SCREEN";
