//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carwale.BL.CRM {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.carwale.com/webservices/", ConfigurationName="CRM.PushCRMSoap")]
    public interface PushCRMSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.carwale.com/webservices/CheckService", ReplyAction="*")]
        bool CheckService();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.carwale.com/webservices/CheckService", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CheckServiceAsync();
        
        // CODEGEN: Generating message contract since element name xmlData from namespace https://www.carwale.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.carwale.com/webservices/PushToCRM", ReplyAction="*")]
        Carwale.BL.CRM.PushToCRMResponse PushToCRM(Carwale.BL.CRM.PushToCRMRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.carwale.com/webservices/PushToCRM", ReplyAction="*")]
        System.Threading.Tasks.Task<Carwale.BL.CRM.PushToCRMResponse> PushToCRMAsync(Carwale.BL.CRM.PushToCRMRequest request);
        
        // CODEGEN: Generating message contract since element name xmlData from namespace https://www.carwale.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.carwale.com/webservices/UpdateDMSData", ReplyAction="*")]
        Carwale.BL.CRM.UpdateDMSDataResponse UpdateDMSData(Carwale.BL.CRM.UpdateDMSDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.carwale.com/webservices/UpdateDMSData", ReplyAction="*")]
        System.Threading.Tasks.Task<Carwale.BL.CRM.UpdateDMSDataResponse> UpdateDMSDataAsync(Carwale.BL.CRM.UpdateDMSDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PushToCRMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PushToCRM", Namespace="https://www.carwale.com/webservices/", Order=0)]
        public Carwale.BL.CRM.PushToCRMRequestBody Body;
        
        public PushToCRMRequest() {
        }
        
        public PushToCRMRequest(Carwale.BL.CRM.PushToCRMRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.carwale.com/webservices/")]
    public partial class PushToCRMRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        public PushToCRMRequestBody() {
        }
        
        public PushToCRMRequestBody(string xmlData, string type) {
            this.xmlData = xmlData;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PushToCRMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PushToCRMResponse", Namespace="https://www.carwale.com/webservices/", Order=0)]
        public Carwale.BL.CRM.PushToCRMResponseBody Body;
        
        public PushToCRMResponse() {
        }
        
        public PushToCRMResponse(Carwale.BL.CRM.PushToCRMResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.carwale.com/webservices/")]
    public partial class PushToCRMResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PushToCRMResult;
        
        public PushToCRMResponseBody() {
        }
        
        public PushToCRMResponseBody(string PushToCRMResult) {
            this.PushToCRMResult = PushToCRMResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDMSDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDMSData", Namespace="https://www.carwale.com/webservices/", Order=0)]
        public Carwale.BL.CRM.UpdateDMSDataRequestBody Body;
        
        public UpdateDMSDataRequest() {
        }
        
        public UpdateDMSDataRequest(Carwale.BL.CRM.UpdateDMSDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.carwale.com/webservices/")]
    public partial class UpdateDMSDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string saveId;
        
        public UpdateDMSDataRequestBody() {
        }
        
        public UpdateDMSDataRequestBody(string xmlData, string saveId) {
            this.xmlData = xmlData;
            this.saveId = saveId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDMSDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDMSDataResponse", Namespace="https://www.carwale.com/webservices/", Order=0)]
        public Carwale.BL.CRM.UpdateDMSDataResponseBody Body;
        
        public UpdateDMSDataResponse() {
        }
        
        public UpdateDMSDataResponse(Carwale.BL.CRM.UpdateDMSDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateDMSDataResponseBody {
        
        public UpdateDMSDataResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PushCRMSoapChannel : Carwale.BL.CRM.PushCRMSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PushCRMSoapClient : System.ServiceModel.ClientBase<Carwale.BL.CRM.PushCRMSoap>, Carwale.BL.CRM.PushCRMSoap {
        
        public PushCRMSoapClient() {
        }
        
        public PushCRMSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PushCRMSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PushCRMSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PushCRMSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckService() {
            return base.Channel.CheckService();
        }
        
        public System.Threading.Tasks.Task<bool> CheckServiceAsync() {
            return base.Channel.CheckServiceAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carwale.BL.CRM.PushToCRMResponse Carwale.BL.CRM.PushCRMSoap.PushToCRM(Carwale.BL.CRM.PushToCRMRequest request) {
            return base.Channel.PushToCRM(request);
        }
        
        public string PushToCRM(string xmlData, string type) {
            Carwale.BL.CRM.PushToCRMRequest inValue = new Carwale.BL.CRM.PushToCRMRequest();
            inValue.Body = new Carwale.BL.CRM.PushToCRMRequestBody();
            inValue.Body.xmlData = xmlData;
            inValue.Body.type = type;
            Carwale.BL.CRM.PushToCRMResponse retVal = ((Carwale.BL.CRM.PushCRMSoap)(this)).PushToCRM(inValue);
            return retVal.Body.PushToCRMResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carwale.BL.CRM.PushToCRMResponse> Carwale.BL.CRM.PushCRMSoap.PushToCRMAsync(Carwale.BL.CRM.PushToCRMRequest request) {
            return base.Channel.PushToCRMAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carwale.BL.CRM.PushToCRMResponse> PushToCRMAsync(string xmlData, string type) {
            Carwale.BL.CRM.PushToCRMRequest inValue = new Carwale.BL.CRM.PushToCRMRequest();
            inValue.Body = new Carwale.BL.CRM.PushToCRMRequestBody();
            inValue.Body.xmlData = xmlData;
            inValue.Body.type = type;
            return ((Carwale.BL.CRM.PushCRMSoap)(this)).PushToCRMAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Carwale.BL.CRM.UpdateDMSDataResponse Carwale.BL.CRM.PushCRMSoap.UpdateDMSData(Carwale.BL.CRM.UpdateDMSDataRequest request) {
            return base.Channel.UpdateDMSData(request);
        }
        
        public void UpdateDMSData(string xmlData, string saveId) {
            Carwale.BL.CRM.UpdateDMSDataRequest inValue = new Carwale.BL.CRM.UpdateDMSDataRequest();
            inValue.Body = new Carwale.BL.CRM.UpdateDMSDataRequestBody();
            inValue.Body.xmlData = xmlData;
            inValue.Body.saveId = saveId;
            Carwale.BL.CRM.UpdateDMSDataResponse retVal = ((Carwale.BL.CRM.PushCRMSoap)(this)).UpdateDMSData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Carwale.BL.CRM.UpdateDMSDataResponse> Carwale.BL.CRM.PushCRMSoap.UpdateDMSDataAsync(Carwale.BL.CRM.UpdateDMSDataRequest request) {
            return base.Channel.UpdateDMSDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Carwale.BL.CRM.UpdateDMSDataResponse> UpdateDMSDataAsync(string xmlData, string saveId) {
            Carwale.BL.CRM.UpdateDMSDataRequest inValue = new Carwale.BL.CRM.UpdateDMSDataRequest();
            inValue.Body = new Carwale.BL.CRM.UpdateDMSDataRequestBody();
            inValue.Body.xmlData = xmlData;
            inValue.Body.saveId = saveId;
            return ((Carwale.BL.CRM.PushCRMSoap)(this)).UpdateDMSDataAsync(inValue);
        }
    }
}
