// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BhriguService/Bhrigu.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Bhrigu {
  public static partial class Bhrigu
  {
    static readonly string __ServiceName = "Bhrigu.Bhrigu";

    static readonly grpc::Marshaller<global::Bhrigu.TrackingRequest> __Marshaller_TrackingRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bhrigu.TrackingRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bhrigu.TrackingResponse> __Marshaller_TrackingResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bhrigu.TrackingResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bhrigu.UserProfileRequest> __Marshaller_UserProfileRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bhrigu.UserProfileRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bhrigu.UserProfileResponse> __Marshaller_UserProfileResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bhrigu.UserProfileResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bhrigu.RecommendationRequest> __Marshaller_RecommendationRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bhrigu.RecommendationRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bhrigu.RecommendationResponse> __Marshaller_RecommendationResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bhrigu.RecommendationResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bhrigu.RefreshRequest> __Marshaller_RefreshRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bhrigu.RefreshRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bhrigu.RefreshResponse> __Marshaller_RefreshResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bhrigu.RefreshResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bhrigu.ScoreRequest> __Marshaller_ScoreRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bhrigu.ScoreRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bhrigu.ScoreResponse> __Marshaller_ScoreResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bhrigu.ScoreResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bhrigu.MmvChangeEventData> __Marshaller_MmvChangeEventData = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bhrigu.MmvChangeEventData.Parser.ParseFrom);

    static readonly grpc::Method<global::Bhrigu.TrackingRequest, global::Bhrigu.TrackingResponse> __Method_TrackEvent = new grpc::Method<global::Bhrigu.TrackingRequest, global::Bhrigu.TrackingResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TrackEvent",
        __Marshaller_TrackingRequest,
        __Marshaller_TrackingResponse);

    static readonly grpc::Method<global::Bhrigu.UserProfileRequest, global::Bhrigu.UserProfileResponse> __Method_GetUserProfile = new grpc::Method<global::Bhrigu.UserProfileRequest, global::Bhrigu.UserProfileResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetUserProfile",
        __Marshaller_UserProfileRequest,
        __Marshaller_UserProfileResponse);

    static readonly grpc::Method<global::Bhrigu.RecommendationRequest, global::Bhrigu.RecommendationResponse> __Method_GetRecommendation = new grpc::Method<global::Bhrigu.RecommendationRequest, global::Bhrigu.RecommendationResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRecommendation",
        __Marshaller_RecommendationRequest,
        __Marshaller_RecommendationResponse);

    static readonly grpc::Method<global::Bhrigu.RefreshRequest, global::Bhrigu.RefreshResponse> __Method_RefreshRecommendation = new grpc::Method<global::Bhrigu.RefreshRequest, global::Bhrigu.RefreshResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RefreshRecommendation",
        __Marshaller_RefreshRequest,
        __Marshaller_RefreshResponse);

    static readonly grpc::Method<global::Bhrigu.ScoreRequest, global::Bhrigu.ScoreResponse> __Method_GetModelScore = new grpc::Method<global::Bhrigu.ScoreRequest, global::Bhrigu.ScoreResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetModelScore",
        __Marshaller_ScoreRequest,
        __Marshaller_ScoreResponse);

    static readonly grpc::Method<global::Bhrigu.MmvChangeEventData, global::Bhrigu.RefreshResponse> __Method_MakeChangeEvent = new grpc::Method<global::Bhrigu.MmvChangeEventData, global::Bhrigu.RefreshResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "MakeChangeEvent",
        __Marshaller_MmvChangeEventData,
        __Marshaller_RefreshResponse);

    static readonly grpc::Method<global::Bhrigu.MmvChangeEventData, global::Bhrigu.RefreshResponse> __Method_ModelChangeEvent = new grpc::Method<global::Bhrigu.MmvChangeEventData, global::Bhrigu.RefreshResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ModelChangeEvent",
        __Marshaller_MmvChangeEventData,
        __Marshaller_RefreshResponse);

    static readonly grpc::Method<global::Bhrigu.MmvChangeEventData, global::Bhrigu.RefreshResponse> __Method_VersionChangeEvent = new grpc::Method<global::Bhrigu.MmvChangeEventData, global::Bhrigu.RefreshResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "VersionChangeEvent",
        __Marshaller_MmvChangeEventData,
        __Marshaller_RefreshResponse);

    static readonly grpc::Method<global::Bhrigu.MmvChangeEventData, global::Bhrigu.RefreshResponse> __Method_ModelRootChangeEvent = new grpc::Method<global::Bhrigu.MmvChangeEventData, global::Bhrigu.RefreshResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ModelRootChangeEvent",
        __Marshaller_MmvChangeEventData,
        __Marshaller_RefreshResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Bhrigu.BhriguReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Bhrigu</summary>
    public abstract partial class BhriguBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Bhrigu.TrackingResponse> TrackEvent(global::Bhrigu.TrackingRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bhrigu.UserProfileResponse> GetUserProfile(global::Bhrigu.UserProfileRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bhrigu.RecommendationResponse> GetRecommendation(global::Bhrigu.RecommendationRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bhrigu.RefreshResponse> RefreshRecommendation(global::Bhrigu.RefreshRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bhrigu.ScoreResponse> GetModelScore(global::Bhrigu.ScoreRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bhrigu.RefreshResponse> MakeChangeEvent(global::Bhrigu.MmvChangeEventData request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bhrigu.RefreshResponse> ModelChangeEvent(global::Bhrigu.MmvChangeEventData request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bhrigu.RefreshResponse> VersionChangeEvent(global::Bhrigu.MmvChangeEventData request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bhrigu.RefreshResponse> ModelRootChangeEvent(global::Bhrigu.MmvChangeEventData request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Bhrigu</summary>
    public partial class BhriguClient : grpc::ClientBase<BhriguClient>
    {
      /// <summary>Creates a new client for Bhrigu</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public BhriguClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Bhrigu that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public BhriguClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected BhriguClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected BhriguClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Bhrigu.TrackingResponse TrackEvent(global::Bhrigu.TrackingRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return TrackEvent(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bhrigu.TrackingResponse TrackEvent(global::Bhrigu.TrackingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TrackEvent, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bhrigu.TrackingResponse> TrackEventAsync(global::Bhrigu.TrackingRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return TrackEventAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bhrigu.TrackingResponse> TrackEventAsync(global::Bhrigu.TrackingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TrackEvent, null, options, request);
      }
      public virtual global::Bhrigu.UserProfileResponse GetUserProfile(global::Bhrigu.UserProfileRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetUserProfile(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bhrigu.UserProfileResponse GetUserProfile(global::Bhrigu.UserProfileRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetUserProfile, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bhrigu.UserProfileResponse> GetUserProfileAsync(global::Bhrigu.UserProfileRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetUserProfileAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bhrigu.UserProfileResponse> GetUserProfileAsync(global::Bhrigu.UserProfileRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetUserProfile, null, options, request);
      }
      public virtual global::Bhrigu.RecommendationResponse GetRecommendation(global::Bhrigu.RecommendationRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetRecommendation(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bhrigu.RecommendationResponse GetRecommendation(global::Bhrigu.RecommendationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRecommendation, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bhrigu.RecommendationResponse> GetRecommendationAsync(global::Bhrigu.RecommendationRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetRecommendationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bhrigu.RecommendationResponse> GetRecommendationAsync(global::Bhrigu.RecommendationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRecommendation, null, options, request);
      }
      public virtual global::Bhrigu.RefreshResponse RefreshRecommendation(global::Bhrigu.RefreshRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RefreshRecommendation(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bhrigu.RefreshResponse RefreshRecommendation(global::Bhrigu.RefreshRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RefreshRecommendation, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bhrigu.RefreshResponse> RefreshRecommendationAsync(global::Bhrigu.RefreshRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RefreshRecommendationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bhrigu.RefreshResponse> RefreshRecommendationAsync(global::Bhrigu.RefreshRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RefreshRecommendation, null, options, request);
      }
      public virtual global::Bhrigu.ScoreResponse GetModelScore(global::Bhrigu.ScoreRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetModelScore(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bhrigu.ScoreResponse GetModelScore(global::Bhrigu.ScoreRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetModelScore, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bhrigu.ScoreResponse> GetModelScoreAsync(global::Bhrigu.ScoreRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetModelScoreAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bhrigu.ScoreResponse> GetModelScoreAsync(global::Bhrigu.ScoreRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetModelScore, null, options, request);
      }
      public virtual global::Bhrigu.RefreshResponse MakeChangeEvent(global::Bhrigu.MmvChangeEventData request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return MakeChangeEvent(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bhrigu.RefreshResponse MakeChangeEvent(global::Bhrigu.MmvChangeEventData request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_MakeChangeEvent, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bhrigu.RefreshResponse> MakeChangeEventAsync(global::Bhrigu.MmvChangeEventData request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return MakeChangeEventAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bhrigu.RefreshResponse> MakeChangeEventAsync(global::Bhrigu.MmvChangeEventData request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_MakeChangeEvent, null, options, request);
      }
      public virtual global::Bhrigu.RefreshResponse ModelChangeEvent(global::Bhrigu.MmvChangeEventData request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ModelChangeEvent(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bhrigu.RefreshResponse ModelChangeEvent(global::Bhrigu.MmvChangeEventData request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ModelChangeEvent, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bhrigu.RefreshResponse> ModelChangeEventAsync(global::Bhrigu.MmvChangeEventData request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ModelChangeEventAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bhrigu.RefreshResponse> ModelChangeEventAsync(global::Bhrigu.MmvChangeEventData request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ModelChangeEvent, null, options, request);
      }
      public virtual global::Bhrigu.RefreshResponse VersionChangeEvent(global::Bhrigu.MmvChangeEventData request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return VersionChangeEvent(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bhrigu.RefreshResponse VersionChangeEvent(global::Bhrigu.MmvChangeEventData request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_VersionChangeEvent, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bhrigu.RefreshResponse> VersionChangeEventAsync(global::Bhrigu.MmvChangeEventData request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return VersionChangeEventAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bhrigu.RefreshResponse> VersionChangeEventAsync(global::Bhrigu.MmvChangeEventData request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_VersionChangeEvent, null, options, request);
      }
      public virtual global::Bhrigu.RefreshResponse ModelRootChangeEvent(global::Bhrigu.MmvChangeEventData request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ModelRootChangeEvent(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bhrigu.RefreshResponse ModelRootChangeEvent(global::Bhrigu.MmvChangeEventData request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ModelRootChangeEvent, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bhrigu.RefreshResponse> ModelRootChangeEventAsync(global::Bhrigu.MmvChangeEventData request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ModelRootChangeEventAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bhrigu.RefreshResponse> ModelRootChangeEventAsync(global::Bhrigu.MmvChangeEventData request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ModelRootChangeEvent, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override BhriguClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new BhriguClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(BhriguBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_TrackEvent, serviceImpl.TrackEvent)
          .AddMethod(__Method_GetUserProfile, serviceImpl.GetUserProfile)
          .AddMethod(__Method_GetRecommendation, serviceImpl.GetRecommendation)
          .AddMethod(__Method_RefreshRecommendation, serviceImpl.RefreshRecommendation)
          .AddMethod(__Method_GetModelScore, serviceImpl.GetModelScore)
          .AddMethod(__Method_MakeChangeEvent, serviceImpl.MakeChangeEvent)
          .AddMethod(__Method_ModelChangeEvent, serviceImpl.ModelChangeEvent)
          .AddMethod(__Method_VersionChangeEvent, serviceImpl.VersionChangeEvent)
          .AddMethod(__Method_ModelRootChangeEvent, serviceImpl.ModelRootChangeEvent).Build();
    }

  }
}
#endregion
